feat101 네비게이션 바
woowacourse-teams/2023-pium pull request #137
Opened 2023-07-26 04:23 UTC by bassyu

# 🔥 연관 이슈

- close #101

# 🚀 작업 내용

# 💬 리뷰 중점사항

2023-07-26 12:12 UTC, hozzijeong requested changes
너무 예쁩니다. 멋있어요 쵸파! 코멘트 한번 확인해주세요

2023-07-26 12:12 UTC, hozzijeong commented on frontend/src/components/@common/Navbar/index.tsx
> +        const active = currentPath === path;
### R

currentPath를 직접 넣어주는 것보다 router hooks를 통해서 값을 전달 받는 것은 어떤가요?  여기서 받으면, 일일히 다 넣을 필요도 없고 경로에 대한 신뢰성도 좀 더 높을 것 같아서 제안드립니다! 

Path들을 Type으로 받아서 괜찮을 것 같으면서도... ` /:id`와 같은 값들도 정상적으로 받을 수 있는지가 의문이 듭니다

2023-07-27 05:38 UTC, WaiNaat requested changes
너무 이뻐요 👍 고생하셨습니다 쵸파!

2023-07-27 05:38 UTC, WaiNaat commented on frontend/src/components/@common/Navbar/index.tsx
> +              <NavItem>
### C

이거 세 개를 합치지 않고 따로 가져가신 이유가 있나요??

2023-07-27 05:57 UTC, bassyu commented on frontend/src/components/@common/Navbar/index.tsx
> +        const active = currentPath === path;
그러네요! useLocation을 활용해볼게요!

2023-07-27 05:58 UTC, bassyu commented on frontend/src/components/@common/Navbar/Navbar.style.ts
> +export const Wrapper = styled.div`
nav 태그가 있었군요! 좋아요.

2023-07-27 06:00 UTC, bassyu commented on frontend/src/components/@common/Navbar/index.tsx
> +              <NavItem>
Link와 아이템 영역을 나눈 것은 필수는 아닙니다! Link에 스타일을 최대한 줄이고 그냥 감싸주기만 하고 싶었어요.
아이템 영역과 아이템을 나눈 이유는 가운데 정렬을 해주고 높이는 고정하려고 나눴습니다!

2023-07-27 06:21 UTC, bassyu commented on frontend/src/components/@common/Navbar/index.tsx
> +  const navItems = [
이 부분은 조금만 더 고민해볼게요!

2023-07-27 07:27 UTC, WaiNaat commented on frontend/src/components/@common/Navbar/index.tsx
> +              <NavItem>
Link에 스타일을 줄인다는 의도는 이해가 갑니다
근데 가운데 정렬이랑 높이를 고정하기 위해서 두 개로 나눴다는 건 잘 이해가 안 가네요.. 코드만 봤을 때는 그냥 area나 item증 히니에 width랑 height를 고정값으로 줘도 될 것 같은데 svg 크기가 다 달라서 그런건가요?

2023-07-27 07:58 UTC, bassyu commented on frontend/src/components/@common/Navbar/index.tsx
> +              <NavItem>
맞습니다! 그냥 가운데 정렬을 하고 margin을 주면 아이콘 크기에 따라서 높이가 재각각일 것 같아서 그냥 영역의 높이를 주고자 했습니다.

2023-07-27 09:01 UTC, hozzijeong approved these changes
고생하셨습니다 쵸파! 멋져요

2023-07-27 09:07 UTC, hozzijeong commented on frontend/src/pages/Root/Root.style.tsx
>    background: white;
![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/9ef1d8f7-7a2b-4281-9aa9-0bbc0efc7259)

height가 작아졌을 때 위와같이 나타나는데 한번 확인 부탁드려요

2023-07-27 17:02 UTC, WaiNaat commented on frontend/src/pages/Root/Root.style.tsx
>    background: white;
![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/b3cb587b-065a-4f03-b6b9-1b5d6ecd15c9)

저는 저런 증상이 없어서 뭔가 제대로 확인된 후에 approve 하겠습니다

2023-07-28 11:50 UTC, WaiNaat requested changes
변경하신 부분들 확인했습니다!
오늘 수업을 듣고 svg에도 신경을 써야겠다는 생각이 들어 마지막으로 리뷰 남겨봐요...

2023-07-28 11:50 UTC, WaiNaat commented on frontend/src/components/@common/Navbar/index.tsx
> +                <Icon stroke={active ? theme.color.primary : '#888888'} />
### R

```suggestion
                <Icon stroke={active ? theme.color.primary : '#888888'} aria-hidden="true" />
```
윈도우 내레이터 기준 아무 설명 없는 SVG를 '이미지'라고 읽네요
어차피 아이콘은 단순한 꾸미기용으로 쓰이는거니까 아예 읽지 못하도록 막는 게 좋을 것 같아요

2023-07-29 02:50 UTC, bassyu commented on frontend/src/components/@common/Navbar/index.tsx
> +                <Icon stroke={active ? theme.color.primary : '#888888'} />
섬세한 접근성 좋네요!!

2023-07-29 02:56 UTC, WaiNaat approved these changes
귀찮을 텐데 작업해주셔서 감사해요 쵸파!!

2023-07-29 02:57 UTC, merged