feat: 리마인더 구현
woowacourse-teams/2023-pium pull request #142
Opened 2023-07-26 12:50 UTC by hozzijeong

# 🔥 연관 이슈

- close #125 

# 🚀 작업 내용
- [x] 식물 리마인더 데이터 불러오기
- [x] 날짜에 따른 카드 분리하기
- [x] 관리 기록 관련 이벤트를 등록한다.
    - [x] 체크박스 클릭 시에 오늘 날짜 넘어가기
    - [x] 미루기 클릭 시에 하루 추가하기
    - [x] 날짜 입력 선택 시에 달력창으로 현재 날짜 입력할 수 있도록 하기 (직접 물을 준 날짜를 선택하는 기능으로, 최대값이 '오늘'이 되도록 설정했습니다.)
    - [x] 관리 기록 이벤트가 발생하고 난 다음에 데이터 Fetch가 한번 더 일어나야 한다.
- [x] `지각 | 오늘 일정 | 남은 일정`에 따른 배경색을 분리힌다.

https://github.com/woowacourse-teams/2023-pium/assets/50974359/7b65212c-5153-433b-b945-1f23f8189df3

----

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/a38c7e1d-6a27-4e93-bf33-d400d0a85b77)

대략적인 Reminder 데이터의 섹션(?)을 구분해 봤습니다!

작업 내용이 조금 많이 있습니다. msw 설정과 날짜 계산 로직을 넣어본다고 넣었는데 잘 넣었는지 모르겠네요 ㅎ 

`checkbox`구현을 했는데 쓸모가 없어져서... 혹시 모르니 같이 올려놔 봅니다! 

- API명세대로 데이터를 받긴 하지만, 디자인에 맞춰서 값을 새로 분리해야 했습니다. 분리된 타입은 `ReminderExtendType`입니다. 
- API명세를 해당 타입으로 변환하는 메서드는 `useReminder`에 있는 `convertReminderData`입니다.
- 3개의 훅을 하나로 합치는 훅인 `useReminderHooks`를 선언했는데, 데이터에 변화가 있을 때마다 refetch를 해야했기 때문에 3개의 훅이 같은 파일에서 있을 필요가 있다고 생각해서 새로운 훅을 만들었습니다.
- 코드를 보면 아시겠지만, `Reminder`가 최대 4뎁스까지 가기 때문에, `ContextAPI`를 통해서 callback 함수들을 전역으로 설정했습니다.

이후 궁금하신 사항 있으면 바로바로 말씀해 주세요!

# 💬 리뷰 중점사항
우선은 기능 구현이 잘 되는지 확인 부탁드립니다.
리마인더 로직을 짜면서 테스트의 필요성에 대해 살짝 느끼게 되었는데, 테스팅 라이브러리 도입에 대한 여러분의 생각을 듣고싶습니다!!

ps. 쵸파 테코톡 화이팅, 참새 아프지 마세요 ㅠ

2023-07-27 07:14 UTC, WaiNaat requested changes
핵심기능 멋있게 만들어주셔서 감사해요 클린!!
로컬로 돌렸을 때는 개발서버랑 스토리북 둘 다 잘 돌아갑니다 👍

2023-07-27 07:14 UTC, WaiNaat commented on frontend/src/components/Reminder/CardBox/index.tsx
> +        {!notDate && <DateLabel>{data.date}</DateLabel>}
### C

혹시 `showDate`는 어떠신가요

2023-07-27 07:14 UTC, WaiNaat commented on frontend/src/contexts/reminderContext.tsx
### C

컴포넌트 prop으로 `waterCallback`이랑 `pushOffCallback`을 주거나
컴포넌트가 직접 `useWaterMutate`같은 훅을 호출하는 방법이 아니라 context로 하신 이유가 궁금해요

2023-07-27 07:14 UTC, WaiNaat commented on frontend/src/hooks/queries/reminder/useReminder.ts
> +    const [_, month, date] = cur.nextWaterDate.split('-') as [string, Month, string];
### R

이거 아마 이렇게 하시면 될거에요
```suggestion
    const [, month, date] = cur.nextWaterDate.split('-') as [string, Month, string];
```

2023-07-27 07:14 UTC, WaiNaat commented on frontend/src/hooks/useReminderHooks.ts
> +  enabled?: boolean;
### C

enabled 속성이 필요한 이유가 있나요??

2023-07-27 07:32 UTC, hozzijeong commented on frontend/src/hooks/useReminderHooks.ts
> +  enabled?: boolean;
reminder를 전역으로 사용하기 전에 초기 렌더링 되는 것을 방지하고자 작성했었는데, 전역으로 돌리면서 굳이 사용할 필요가 없어졌습니다. 지우는게 좋을 것 같아요!

2023-07-27 07:33 UTC, hozzijeong commented on frontend/src/utils/date.ts
> +interface SpecificDayProps {
params가 더 맞을것 같네요...ㅎ, 기본값 설정(new Date())를 하기 위해서 설정을한 것이었는데, 굳이 그렇게 할 필요가 없긴 하네요 ㅎ

2023-07-27 07:34 UTC, hozzijeong commented on frontend/src/types/api/reminder.ts
> +export type TodayStatus = 'late' | 'exist' | 'none'; // 오늘 할 일에 대한 상태
확실히 통일성이 없어보이긴 하는군요... 확인했습니다!

2023-07-27 07:34 UTC, hozzijeong commented on frontend/src/constants/index.ts
> +export const BASE_URL = 'http://localhost:8282'; // 'http://api.pium.life';
좋아요 좋아요!

2023-07-27 07:36 UTC, hozzijeong commented on frontend/src/components/Reminder/MonthBox/index.tsx
> +  month: string;
넵넵... Month를 따로 설정한 이유는 API로부터 넘어오는 값이 01,02와 같이 표현되고, 리마인더에 표시될때는 1월 2월 .. 이렇게 표현이 되다 보니까 string으로 넘기게 되었습니다.

해당 컴포넌트에서 넘겨 받고 변경해도 괜찮을 것 같긴 하네요!

2023-07-27 07:36 UTC, hozzijeong commented on frontend/src/hooks/queries/reminder/usePushOff.ts
> +};
확실히 범용성이 좀 더 있어보이네요! 좋은 생각인것 같아요 👍

2023-07-27 07:45 UTC, hozzijeong commented on frontend/src/contexts/reminderContext.tsx
`prop`로 전달하게 된다면, `propsDrilling`이 발생하기 때문에 최대한 지양했습니다. 

독립적인 `hooks`도 생각을 했었는데, 데이터 요청이 `success`된  다음에 `useReminder`에 있는 `refetch`를 호출해야 하기 때문에 공통된 관심사라고 생각했고 3가지 메서드가 한 파일에서 선언했습니다.

이제 선언한 훅들을 물주기, 미루기 등등이 사용되는 컴포넌트에서 호출을 했어야 했는데, `context`로 분리한 다음에 전달하는 방식이 `reminder` 중복 코드를 줄인다고 생각했습니다. 처음에 참새가 말했던 대로 파일별로 훅을 호출하는 과정에서 `({enabled})`를 사용했었습니다

관심사 분리 측면에서 약간의 차이가 있을 수 있지만,,, 그렇기 때문에 훅들을 호출해서 반환하는 새로운 훅을 만들어서 사용했습니다.

2023-07-27 07:50 UTC, hozzijeong commented on frontend/src/components/@common/CheckBox/index.tsx
> +      <Input id={id} />
해당 메서드가 필요 없는 것 일까요?? 어떤 의미로 작성 하신건지 궁금합니다!

2023-07-27 07:50 UTC, hozzijeong commented on frontend/src/utils/date.ts
> + *
해당 메서드가 필요 없는 것 일까요?? 어떤 의미로 작성 하신건지 궁금합니다!

2023-07-27 08:20 UTC, WaiNaat commented on frontend/src/utils/date.ts
> + *
빈줄 하나 있어서 지워달라는 거였습니다ㅋㅋㅋ

2023-07-27 08:35 UTC, WaiNaat commented on frontend/src/contexts/reminderContext.tsx
아하 하나 물주기를 완료해도 전체 리마인더 목록을 refetch 해야해서였군요 이해했습니다

2023-07-28 05:06 UTC, hozzijeong commented on frontend/src/components/Reminder/MonthBox/index.tsx
> +  month: string;
반환 받은 값을 `month:data[]` 형태로 지정되어 있어서 Object.entries를 통해서 배열로 변환을 했습니다. (이터러블로 사용하기 위해서 변환했습니다). 이 과정에서 key값은 무조건 string 형태로 변환이 되더라구요? 이것을 바꾸려면 타입을 따로 선언을 해야 하는데 이 부분이 너무 오래걸릴 것 같긴하네요...

2023-07-28 06:25 UTC, bassyu requested changes
작업량이 정말 엄청나네요 😮
코멘트는 큰 내용은 없고 pushOff 네이밍을 delay로 하면 어떨지 제안해봅니다!
수고하셨어요 클린..

2023-07-28 06:25 UTC, bassyu commented on frontend/src/apis/reminder.ts
> +const pushOff = ({ id, body }: PushOffProps) => {
### R

네이밍을 명시적으로 `delay`라고 하는 건 어떤가요?

2023-07-28 08:08 UTC, hozzijeong commented on frontend/src/apis/reminder.ts
> +const pushOff = ({ id, body }: PushOffProps) => {
아예 네이밍이 바뀔것 같습니다 .. ㅎ

2023-07-31 06:16 UTC, bassyu requested changes
리팩터링 양도 상당하네요!!
코드 양도 많고, 대부분 잘 구현해주신 것 같습니다!
반영할 것만 반영해주세요!

2023-07-31 06:16 UTC, bassyu commented on frontend/src/components/Reminder/Card/Card.style.ts
> +export const PutOff = styled.button`
### R

사용되지 않는 친구인 것 같습니다!

2023-07-31 06:16 UTC, bassyu commented on frontend/src/components/Reminder/Card/index.tsx
> +import {
### R

type import 가 빠졌네요!

2023-07-31 06:16 UTC, bassyu commented on frontend/src/components/Reminder/Card/index.tsx
> +  const changeDateHandler = (changeDate: string) => {
### C

여기도 `Handler` Suffix를 빼보는 건 어떨지 제안해봅니다!
보통 핸들러 함수는 컴포넌트 안에, 로직 함수는 훅으로 빼는 패턴이 많이 쓰인다고 생각하는데요,
그래서 핸들러라는 표현을 안해줘도 이해할 수 있고, 행동에 네이밍 초점을 맞추면 좋지 않을까? 생각했어요.

2023-07-31 06:16 UTC, bassyu commented on frontend/src/pages/Reminder/index.tsx
> +  if (reminderData === undefined) return null;
### A

이렇게 어떤가요?

```suggestion
  if (!reminderData) return null;
```

2023-07-31 06:59 UTC, hozzijeong commented on frontend/src/apis/reminder.ts
> +const waterPlant = ({ id, body }: WaterPlantProps) => {
확실히 Params가 더 맞는것 같네요...!! 수정하겠습니다 ㅎ

2023-07-31 07:02 UTC, hozzijeong commented on frontend/src/components/@common/CheckBox/index.tsx
> +    setChecked((prev) => !prev);
전 함수의 순수성(?)을 생각해서 외부의 값을 참조하지 않고 해당 메서드에서 처리되는게 낫다고 생각을 해서 콜백 형식으로 작성했습니다. 직접 값을 할당하는 방식이 콜백을 사용하는 것과 다르게 특별한 기능적 차이나 의도의 차이가 있을까요??  (의도의 차이가 어떤건지 잘 몰라서 여쭙습니다...ㅎ)

2023-07-31 07:03 UTC, hozzijeong commented on frontend/src/components/@common/CheckBox/index.tsx
> +  const checkHandler = () => {
저는 Handler를 붙이는 게 좀 더 명시적인것 같아요... 메서드의 이름은 최대한 구체적으로 작성하는게 낫다고 생각하는데 쵸파의 생각은 어떤가요?

2023-07-31 07:07 UTC, hozzijeong commented on frontend/src/components/Reminder/Card/index.tsx
> +  const changeDateHandler = (changeDate: string) => {
함수의 "표현을 안해줘도 이해할 수 있고"는 상당히 주관적인 것 같아요🥲 행동에 네이밍 초점을 맞춘다면 그것은 유틸 함수를 작성할때 좀 더 알맞지 않나? 라고 생각했습니다. 핸들러의 역할을 갖는 메서드라면 핸들러라고 명확하게 명시하는게 좀 더 깔끔하다고 생각이 듭니다

2023-07-31 07:37 UTC, bassyu commented on frontend/src/components/Reminder/Card/index.tsx
> +  const changeDateHandler = (changeDate: string) => {
클린 말도 맞습니다!
표현을 안해줘도 이해할 수 있다는 뜻은 '함수 명만 보고도 핸들러구나'까지는 아니고 코드를 조금 살펴보면 알 수 있다는 뜻이었어요!
마치 저희가 타입을 사용할 때 `~Type` Suffix를 붙이지 않는 이유랑 비슷하다고 생각했어요.

2023-07-31 07:48 UTC, bassyu commented on frontend/src/components/@common/CheckBox/index.tsx
> +    setChecked((prev) => !prev);
제가 아는 부분에서 설명 드릴게요!
한번의 리렌더링에서 setState를 여러번 쓰고, 실시간으로 바뀌는 상태를 사용하고 싶은 의도일 때 콜백을 사용한다고 알고 있습니다.
간단하게 아래 두 코드를 보면 이해가 될 것 같습니다!
```
setState(count + 1); // 2
setState(count + 1); // 2
// 최종 2로 리렌더링
```
```
setState((prev) => prev + 1); // 2 
setState((prev) => prev + 1); // 3 
// 최종 3로 리렌더링
```
`!checked` 이런식으로 작성해도 원시값은 참조가 완전 바뀌기 때문에 리렌더링 트리거에 차이는 없을거에요!

2023-07-31 08:46 UTC, hozzijeong commented on frontend/src/components/@common/CheckBox/index.tsx
> +    setChecked((prev) => !prev);
설명 감사합니다! 

개인적인 생각으로는 `Handler`가 조건에 따른 분기처리를 해야하는 경우라면 상황에 맞는 setState를 사용하는게 맞다고 생각이 들지만, 결국 변경된 상태에 따라 동일한 작업을 수행하는 것이라면 코드를 수정할 필요가 있을까? 하는 생각이 들었습니다! 쵸파는 어떻게 생각하시나요??

2023-07-31 10:58 UTC, bassyu commented on frontend/src/components/@common/CheckBox/index.tsx
> +    setChecked((prev) => !prev);
사실 지금 상태에서 결과는 똑같긴 합니다!
다만 '실시간 데이터를 반영하는 것은 아니다'는 메세지를 주는 의미가 있다고 생각했어요.

2023-07-31 11:03 UTC, bassyu approved these changes

2023-08-01 04:39 UTC, WaiNaat requested changes
변경해주신 부분들 확인했어요!
중간에 리마인더 기획이 바뀌어서 할 일이 많았을 것 같은데 고생하셨습니다ㅠㅠ

2023-08-01 04:39 UTC, WaiNaat commented on frontend/src/apis/reminder.ts
> +  Authorization: 'pium@example.com',
### R

요거 `pium@gmail.com` 이래요!!

2023-08-01 04:39 UTC, WaiNaat commented on frontend/src/components/DateInput/index.tsx
> +  changeCallback?: (value: string) => void;
### C

`React.InputHTMLAttributes<HTMLInputElement>`에 들어있는 value나 onChange가 아니라 직접 선언하신 이유가 궁금해요

2023-08-01 05:10 UTC, hozzijeong commented on frontend/src/components/Reminder/CardBox/index.tsx
> +    <ReminderCardBox key={data.petPlantId}>
코드를 리팩터링 하다가 빼먹은 부분이네요... 감사합니다!

2023-08-01 05:11 UTC, hozzijeong commented on frontend/src/components/Reminder/MonthBox/index.tsx
> +    <MonthReminderBox key={month}>
위와 같은 이유입니다... 원래는 Reminder 페이지에서만 작업하다가 (전부 map을 때렸었습니다) 파일로 분리하는 과정에서 지우지 않았습니다...

2023-08-01 05:13 UTC, hozzijeong commented on frontend/src/apis/reminder.ts
> +  Authorization: 'pium@example.com',
오옷 감사합니다

2023-08-01 05:20 UTC, hozzijeong commented on frontend/src/components/DateInput/index.tsx
> +  changeCallback?: (value: string) => void;
value는 타입 체크때문에 그렇습니다. value를 받아서 사용하는 `convertDateKorYear`에서 받는 타입과 HTMLInputElement에서 받는 value의 타입이 달라서 특정했습니다.

onChange는 약간의 레거시 느낌이 있긴 합니다. 당시에 작성했을 때는 changeHandler와 changeHandler가 발생하고 난 다음에 실행될 callback을 분리하는게 관심사 분리 측면에서 낫다는 생각에 분리했었는데, 지금 생각해보니 눈가리고 아옹(?) 느낌이네요

2023-08-01 05:21 UTC, hozzijeong commented on frontend/src/components/@common/CheckBox/CheckBox.style.ts
> +  }
와 생각해보니 굳이 적용할 필요가 없는 코드네요... 당연히 컴포넌트 위에 올리면 hover이고, pointer를 적용해야겠다 라는 생각으로 작성했습니다..

2023-08-01 05:32 UTC, hozzijeong commented on frontend/src/mocks/storage/Reminder.ts
왜 안되나 했더니 중복되는 변수명이 있었네요... 멋있어요 참새

2023-08-01 08:09 UTC, WaiNaat commented on frontend/src/components/DateInput/index.tsx
> +  changeCallback?: (value: string) => void;
value는 이해했습니다!
onChange도 어떤 느낌인지는 알 것 같아요. 만약 요 DateInput 내에서 입력값에 대한 검증이나 전처리가 필요하다면 callback을 받아서 처리 후에 실행하는 방향이 깔끔해 보여요. 근데 지금은 value, setValue 역할을 form reducer가 해 줘서 불필요해 보이기도 합니다.

2023-08-01 08:10 UTC, merged