feat:54-토스트_구현
woowacourse-teams/2023-pium pull request #147
Opened 2023-07-27 07:26 UTC by hozzijeong

# 🔥 연관 이슈

- close #54 

# 🚀 작업 내용

https://github.com/woowacourse-teams/2023-pium/assets/50974359/56a0446a-4d30-4180-a6c4-f0ddd5ae8098

- 쵸파가 작성해준 코드를 이어서 구현해 봤습니다
- stack 형태로 구현해서 쌓이기가 가능합니다.
- stack을 쌓기 위해서 Context API를 사용했습니다.

# 💬 리뷰 중점사항

- 토스트 박스를 삭제하는 버튼을 추가하는 것에 대해서 어떻게 생각하시나요?
- 토스트를 보여줬다가 사라지게 하기는 했는데, 전역 상태인 `toastList`는 비워지지가 않습니다. 이게 상태이기 때문에 `toastList`를 지우면 리렌더링이 발생되더라구요... 그래서 일단은 비우지는 않기로 했는데 특정 트리거가 (ex.화면전환) 발생할 때마다 비워줘야 할 것 같습니다. 다른 방법이 있을까요? (상태 초기화가 필요하긴 합니다...)

2023-07-28 11:21 UTC, WaiNaat requested changes
이쁜 토스트 감사해요 👍 
리뷰 제한시간을 넘겨서 죄송합니다ㅠㅠ 오늘 일과중에 할 시간이 있을 것 같았는데 생각보다 다른 할 일이 많았네요..

1. 삭제 버튼
    굳이? 라는 생각이 듭니다. 시간이 지나면 사라지는 건데 굳이 이용자에게 x표시를 눌러서 닫아야만 할 것 같은 암시를 줄 필요는 없을 것 같아요
3. 최적화
    심한 리렌더링을 감수하더라도 비우는 게 맞다고 생각해요. 페이지 이동 트리거도 괜찮을 것 같은데 이동을 감지해서 비워주는 코드가 페이지 컴포넌트 안에 들어가 있어야 한다면 저는 반대입니다. 너무 많은 보일러플레이트가 생길 것 같아요

2023-07-28 11:21 UTC, WaiNaat commented on frontend/src/hooks/useToast.ts
> +  const id = useId();
### C

![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/69e33836-5208-459f-96fd-0cb2b672686c)

만약 무작위 값이 필요한 거라면 [randomUUID](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)는 어떠신가요

2023-07-29 03:04 UTC, bassyu reviewed
안녕하세요 클린! 빠르게 구현해주신 부분에선 크게 리뷰할 내용이 없네요!
저번에 말씀 드린 것처럼 리스트 대신 그냥 toast-root에 포탈로 바로 붙이는 방법이 상태 관리로서는 최선이라는 생각이 들어요.
그리고 슬슬 `Recoil` 적용에 대해서 이야기 나눠봐도 좋을 것 같아요!

2023-07-31 02:24 UTC, hozzijeong commented
@bassyu @WaiNaat 말씀해 주신 부분들 반영해서 적용했습니다! 한번 확인해주세요

toast 삭제의 경우에 일정 시간 뒤에 삭제하는 것으로 설정했습니다 (렌더링 이슈는 확실히 있을 것 같습니다) 렌더링 최적화에 방법에 대한 여러분들의 생각을 듣고 싶습니다... ㅠㅠ

2023-07-31 05:53 UTC, bassyu approved these changes
변경내용 확인했습니다!
사용성도 좋은 것 같아요!
(출렁이는 것은.. 오히려 기능일수도?)

2023-07-31 05:53 UTC, bassyu commented on frontend/src/hooks/useToast.ts
> +    setToastList((prev) => [...prev, { id, type, message }]);
### A

```suggestion
    setToastList((prev) => [...prev, { id, type, message }].slice(0, MAX_TOAST_SIZE));
```

나중에 최대로 보여줄 토스트 개수를 정하는 것도 좋아보입니다!

2023-07-31 06:55 UTC, hozzijeong commented on frontend/src/hooks/useToast.ts
> +    setToastList((prev) => [...prev, { id, type, message }]);
추후에 맥시멈을 정하는 정책이 생긴다면 괜찮은 아이디어 같네요 ㅎ

2023-07-31 08:55 UTC, WaiNaat requested changes
안녕하세요 클린! 바꾸신 부분들 확인했습니다.
사실 별 내용은 없고.. [SVG에 aria-label 달기](https://github.com/woowacourse-teams/2023-pium/pull/147#discussion_r1277380480)가 아직 해결이 안 되어 있어서 다시 요청 드려요

최적화 관련해서는 고민을 해 봤는데 크게 세 가지 방법이 있는 것 같아요
1. useCallback, useMemo를 적절하게 사용하기
2. Recoil 등 전역 상태 라이브러리
3. useSyncExternalStore

일단 세 방법 다 제 기준 이번 데모데이까지는 힘들어 보여요. 개인적으로는 1번으로 하는 게 멋있을 것 같은데 제가 방금 살짝 뜯어본 거로는 감도 안 잡히더라구요ㅠㅠ

2023-07-31 08:55 UTC, WaiNaat commented on frontend/src/components/@common/Toast/Toast.style.ts
> + 0% {
### R

한 칸이 모자라요 😢

2023-07-31 08:55 UTC, WaiNaat commented on frontend/src/hooks/useToast.ts
> + *
### R

여기도 빈 공간이 생겨버렸습니다..

2023-08-01 04:40 UTC, WaiNaat approved these changes
멋있어요 클린

2023-08-01 04:40 UTC, merged