feature: 120 리마인더 기능 구현
woowacourse-teams/2023-pium pull request #148
Opened 2023-07-27 08:08 UTC by yeonkkk

# 🔥 연관 이슈

- close #120 

# 🚀 작업 내용
- 리마인더 조회, 물주기, 미루기 기능 구현했습니다.

# 💬 리뷰 중점사항
- 테스트 부분 놓치거나 부족한 게 없는지 봐주시면 좋을 것 같습니다.  
- 리마인더에서 물을 주는 기능이 `petPlant`의 waterDate 들을 업데이트함과 동시에 history도 저장을 하는 로직입니다. 
 
- 물주기, 미루기 메서드 네이밍 고민을 오래하긴 했는데, 그렇게 마음에 들진 않네요. 혹시 더 좋은 이름 있으면 추천 받습니다🥹

2023-07-27 12:27 UTC, Choi-JJunho requested changes
고생하셨습니다~
리마인더의 검증로직에 대해서는 모여서 이야기를 나눠봐야할 것 같네요!

몇가지 수정하면 좋을 것 같은 부분에 대해 코멘트 남겨놨습니다~

2023-07-27 12:27 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +        );
### C

assertAll 대신 `SoftAssertions.assertSoftly()`를 사용해보는건 어떤가요?

Soft Assertions을 이용하면 모든 assertThat을 실행하고 해당 실패 내역을 확인할 수 있다는 장점이 있습니다.

다음과 같이 사용할 수 있습니다.
```java
SoftAssertions.assertSoftly(softly -> {
            softly.assertThat(updatedPetPlant)
                    .extracting(PetPlant::getNextWaterDate, PetPlant::getLastWaterDate)
                    .isEqualTo(List.of(newWaterDate.plusDays(petPlant.getWaterCycle()), newWaterDate));
            softly.assertThat(historyRepository.findAll())
                    .extracting(History::getPetPlant, History::getWaterDate)
                    .contains(tuple(updatedPetPlant, newWaterDate));
        }
);
```

2023-07-27 12:27 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +        PetPlant updatedPetPlant = petPlantRepository.findById(petPlant.getId()).get();
### C

Optional 값에 대해 get()으로 값을 꺼내오고 사용하는것이 NPE를 유발할 수 있다고 생각되어 다소 불안정하게 느껴지네요

`.orElseThrow()`로 예외를 던지게하는건 어떤가요?

2023-07-27 12:27 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +    }
### C

통합테스트인만큼 실제 값을 모두 비교해보는건 어떨까요?
좀더 꼼꼼하게 작성하면 다음과 같이 작성할 수도 있을 것 같아요

```suggestion
    @Test
    void 리마인더_전체_조회() {
        DataResponse<List<ReminderResponse>> dataResponse = reminderService.readAll(petPlant.getMember());
        
        List<ReminderResponse> expect = List.of(
                PetPlantMapper.toReminderResponse(petPlant, petPlant.calculateDDay(LocalDate.now()))
        );

        assertThat(dataResponse.getData())
                .hasSize(1)
                .usingRecursiveComparison()
                .isEqualTo(expect);
    }
```

2023-07-27 12:27 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +                        .extracting("petPlant", "waterDate")
### R

extracting을 사용할 때 필드명을 String으로 나타내면 향후 필드명이 변경되었을 때 컴파일 타임에서 감지할 수 없다는 단점이 존재합니다.
만약 extracting을 사용한다면 메서드 참조를 이용하는것이 조금 더 안전해보입니다.

```suggestion
                        .extracting(PetPlant::getNextWaterDate, PetPlant::getLastWaterDate)
```

2023-07-27 12:27 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +                        .extracting("nextWaterDate", "lastWaterDate")
### R

> 만약 extracting을 사용한다면 메서드 참조를 이용하는것이 조금 더 안전해보입니다.

ditto

2023-07-27 12:27 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +                .extracting("nextWaterDate", "lastWaterDate")
### R 

> 만약 extracting을 사용한다면 메서드 참조를 이용하는것이 조금 더 안전해보입니다.

ditto

2023-07-28 00:48 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/ReminderService.java
> +                .orElseThrow(() -> new NoSuchElementException("일치하는 반려 식물이 존재하지 않습니다. id: " + petPlantId));
### C

컨트롤러에서 파라미터로 받는 Member로 해당 반려 식물의 주인인지 확인하는 부분도 필요할 것 같아요 !

2023-07-28 00:57 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/ReminderService.java
> +        return DataResponse.<List<ReminderResponse>>builder().data(reminderResponses).build();
### A

빌더 사용시 한줄에 점 하나로 정리해보는건 어떨까용?!

2023-07-28 06:51 UTC, rawfishthelgh requested changes
조이 고생하셨습니다~!
다만 지금 Run All Test를 수행했을 때, @DataJpaTest에서 Auditing 이슈로 제 환경에서는 실패하고 있는데, 올리시기 전에 한 번 확인 부탁드립니다!
<img width="1335" alt="스크린샷 2023-07-28 오후 3 49 17" src="https://github.com/woowacourse-teams/2023-pium/assets/79038908/40e2d259-0565-46cc-a2a6-8431ee1b0ad1">

2023-07-28 06:51 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +    void 물주기() {
### **C**
물주기 이후에 어떤 결과가 예상되는지 네이밍을 통해 드러낼 수 있을 것 같아요!

2023-07-28 06:51 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +        PetPlant updatedPetPlant = petPlantRepository.findById(petPlant.getId()).get();
### **A**

저는 테스트의 경우 get()을 사용하는 것은 나쁘지 않다고 봅니다! 우리가 setUp() 메소드로 해당 petPlant를 영속화 시키는 "가정"을 진행하고 있고, 이는 어떤 변수로 npe가 유발될 가능성이 적다고 생각해요. 

또 npe가 생기더라도 프로덕션에 영향을 주지 않으니 괜찮지 않을까요??

2023-07-28 15:06 UTC, yeonkkk reviewed
@Kim0914 @rawfishthelgh @Choi-JJunho 

하마드, 주노, 그레이! 
양질의 리뷰 감사드립니다🌱

피드백 내용 반영 완료 했습니다!
이번 리뷰도 잘 부탁드립니다 ~

2023-07-30 09:03 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +    void 물주기() {
지금과 같이 `~하면 ~가 일어난다`와 같은 방식으로 구성하는 방식을 선호합니다!
위와 같은 테스트 네이밍을 구성하면 어떤 의도로 테스트를 작성했는지 파악하기 용이할 것 같아서 드린 피드백이었습니다ㅎㅎ

2023-07-30 09:37 UTC, rawfishthelgh requested changes
조이! 비즈니스 요구사항이 바뀌어 작업이 어려웠을텐데 열심히 리팩토링 하느라 고생하셨어요ㅠㅠ
피드백이 많지는 않은데, 추가되어야 할 검증 로직이 있는 것 같아 코멘트 달아놨어요! 
한 번 확인해주시고 반영 여부 판단해주시면 될 것 같아요!

2023-07-30 09:37 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +    }
### **C**
member의 id 값을 통해 비교하거나, 혹은 member id 값으로 비교하는 equals를 Member에 정의해주는게 어떨까요??

2023-07-30 09:37 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +        }
**C**
"마지막으로 물을 준 날짜(lastWaterDate)"에도 물을 줄 수 없도록 해야할 것 같아요!! 최솟값이 lastWaterDate 이후 라서요ㅜㅜ

lastWaterDate에 물을 줄 수 있게 해도 부정합이 발생하지는 않겠지만, 같은 정보를 유지하는데 update 쿼리가 날아가는 현상이 생길 것 같아요!

2023-07-30 09:37 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +        }
**C**
위 내용과 비슷한 코멘트인데, 미루기 날짜를 "오늘"로 변경하면 안되는 것도 검증에 포함시켜야 할 것 같아요!

2023-07-30 09:41 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +    }
저도 '물을 준다'의 행동의 책임은 반려 식물이 가져갈 수 있지 않을까 생각이 드네요 !

객체의 세계로 보았을 때 자기 자신이 관리하고 있는 `lastWaterDate`, `nextWaterDate`는 반려 식물 자신이 관리하는게 자연스러워 보여요 !

2023-07-30 09:43 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +    }
### C

객체 타입을 비교할 때는 `Objects.equals()`를 통해 비교하는 방법을 권장하더라구요 !

현재 메서드에서는(그럴 일은 없겠ㅈㅣ만) this.member가 null인 경우 예외가 발생할 수 있겠네요 ㅎㅎ

2023-07-31 03:13 UTC, Choi-JJunho requested changes
고생하셨습니다!
이번에는 테스트 관련해서 조금 꼼꼼하게 리뷰남겼습니다.
확인 부탁드립니다~

2023-07-31 03:13 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +        LocalDate newWaterDate = LocalDate.now().plusDays(1);
### C
테스트 명을 조금 더 구체적으로 작성할 수 있을 것 같아요!
`물주기_날짜가_N일_지각인_반려_식물에_대한_미루기`

### A
`@ParameterizedTest`의 name 속성을 이용하면 더 구체적인 테스트명을 다룰 수 있습니다.
```suggestion
    @ParameterizedTest(name = "{0}일 지각인 반려식물에 대해 {1}일 미루기")
    @CsvSource(value = {"1,1", "2,4", "4,2", "5,1"})
    void N일_지각_미루기(int days, int plusDays) {
        PetPlant 산세베리아 = PetPlant.builder()
                .nickname("크론")
                .imageUrl("https://image2.com")
                .light("자연광이 잘 드는 곳")
                .location("거실")
                .wind("바람 솔솔")
                .flowerpot("정보 없음")
                .waterCycle(7)
                .birthDate(LocalDate.of(2022, 7, 1))
                .lastWaterDate(LocalDate.of(2022, 7, 1))
                .nextWaterDate(LocalDate.now().minusDays(days))
                .build();

        LocalDate newWaterDate = LocalDate.now().plusDays(plusDays);
```

<img width="442" alt="image" src="https://github.com/woowacourse-teams/2023-pium/assets/49794401/1f268605-c9e0-40ec-ade3-b2d7a9941b2b">

2023-07-31 03:13 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +    void N일_뒤의_할일_미루기(int days) {
### A
> @ParameterizedTest의 name 속성을 이용하면 더 구체적인 테스트명을 다룰 수 있습니다.

ditto

2023-07-31 03:13 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +        PetPlant updatedPetPlant = petPlantRepository.findById(petPlant.getId()).get();
### A
> 해당 테스트는 잘못된 ID 값을 입력할 경우에 NoSuchElementException 가 발생합니다.
.get() 사용을 해도 괜찮을 것 같군요! 좋습니다 👍

2023-07-31 03:13 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +    void 해당_반려_식물의_사용자와_물주기를_요청한_사용자가_다르면_예외_발생() {
### A
`해당`은 생략해도 될 것 같아요~!

2023-07-31 03:13 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +    void 물주기_미루기() {
### C
`물주기를 N일 미룬다` 와 같이 함수가 파라미터로 받고 사용하는 값에 대한 설명이 포함되어있으면 좋을 것 같아요!
그와 동시에 `@ParameterizedTest`의 사용도 생각해볼 수 있겠네요!

2023-07-31 03:13 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +    void 물주기_미루기_실패시_예외_발생() {
### C
`오늘보다_이전_날짜로_미루기_수행_시_예외_발생`처럼 테스트 명에서 어떤 상황에서 실패하는지에 대한 명시가 되어있으면 좋겠네요!

2023-07-31 03:13 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/ReminderServiceTest.java
> +    void 해당_반려_식물의_사용자와_미루기를_요청한_사용자가_다르면_예외_발생() {
### A
> 해당은 생략해도 될 것 같아요~!

ditto

2023-07-31 07:02 UTC, yeonkkk reviewed
@Choi-JJunho @Kim0914 @rawfishthelgh 
다들  리뷰 감사드려요~
2차 피드백 반영 완료했습니다! 
혹시 수정할 사항이나 같이 논의할 사항 있으면 코멘트 더 부탁드려요🙂

2023-07-31 08:48 UTC, rawfishthelgh requested changes
고생하셨습니다!
equals 로직만 추가되면 merge 하겠습니다

2023-07-31 08:48 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +        return !Objects.equals(this.member, member);
C
지금 Member에 equals가 정의되지 않아서, 동등성 비교가 수행되지 않을 것 같아요ㅜㅜ id 값을 통해 비교해야할 것 같아요!!

2023-07-31 08:51 UTC, Choi-JJunho requested changes
고생하셨습니다~
회의때 이야기한 equals 에 대한 적용만 완료되면 Approve 하겠습니다

2023-07-31 08:51 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +    public boolean isNotSameMember(Member member) {
### A
`isNotSameMember` 대신 `isNotOwner` 와 같은 네이밍은 어떨까요?

2023-08-01 00:43 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/ReminderService.java
> +        checkMemberEquality(petPlant, member);
### C
반려식물의 주인을 확인한다는 의미를 가진 메서드명은 어떨까요?
`checkOwner`정도로 작명할 수 있을 것 같아요 !

2023-08-01 00:46 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/ReminderService.java
> +        if (petPlant.isNotOwner(member)) {
### A

`isNotOwner`에 Of를 더해주는건 어떨까요?!
`isNotOwnerOf`가 되어야' 반려식물의 소유자' 라는 의미가 명확해지는 것 같아요 ㅎㅎ
중요한 부분은 아니라 그냥 넘어가셔도 됩니다 ~

2023-08-01 00:47 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/dto/ReminderResponse.java
> +	private Long petPlantId;
### C

여기 탭이 한칸 더 들어간 것 같은데 기분 탓인가요?! 😆

2023-08-01 00:49 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +    @ParameterizedTest(name = "{0}일 뒤의 물주기를 {1}일 뒤로 미루기")
테스트 넘 잘 짜주셨군요 ㅎㅎ

2023-08-01 01:30 UTC, yeonkkk reviewed
@Kim0914 @Choi-JJunho 

3차 피드백 반영 완료!
아쉽게도 코멘트 100은 못 채웠네요..🥲

2023-08-01 01:30 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/service/ReminderService.java
> +        checkMemberEquality(petPlant, member);
좋은 것 같아요.
반영 완료!

2023-08-01 01:30 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/service/dto/ReminderResponse.java
> +	private Long petPlantId;
확인해보니 탭 한칸이긴 한데, 혹시 모르니 라인 정리 한 번 하겠습니다~

2023-08-01 01:30 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/service/ReminderService.java
> +        if (petPlant.isNotOwner(member)) {
반영 완료~!

2023-08-01 01:30 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +        return !Objects.equals(this.member, member);
회의에서 논의한대로 equals, hash code 작성 완료 했습니다!🙂

2023-08-01 01:33 UTC, Choi-JJunho approved these changes
고생하셨습니다~

2023-08-01 01:35 UTC, merged