feat: 단건 히스토리 조회 페이징 기능 구현
woowacourse-teams/2023-pium pull request #149
Opened 2023-07-27 10:40 UTC by rawfishthelgh

# 🔥 연관 이슈

- close #117 

# 🚀 작업 내용
petPlant의 단건 히스토리 조회와 페이징 기능을 구현했습니다

# 💬 리뷰 중점사항

현재 `Service` 계층의 `isLastPage`라는 메소드에서, 마지막 페이지에 해당하는지 여부를 검사하고 있습니다. 
그런데 이를 `HistoryMapper.toHistoryResponse()`에서 `isLastPage`를 처리해야 할지, 아니면 지금처럼 서비스 계층에 두어야 할지 조금 고민인데 의견 주시면 감사하겠습니다!

2023-07-28 00:42 UTC, Kim0914 requested changes
하마드 ~~ 페이징과 관련한 쉽지 않은 작업을 꼼꼼하게 해주셨네요 👏
궁금한 점과 생각해볼만한 점을 코멘트로 남겼습니다 ㅎㅎ
확인부탁드려요 !!

2023-07-28 00:42 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
> +            @NotNull(message = "반려 식물 ID가 포함되어야 합니다.") @Positive(message = "반려 식물 ID는 1이상의 값이어야 합니다.") @RequestParam("petPlantId") Long petPlantId,
### A 

어노테이션 순서를 통일해보는건 어떨까요?!
컨벤션으로 정해진 건 없지만, 현재 다른 메서드들을 보면 어떤 어노테이션인지(@RequestParam), 어떤 검증이 필요한지(@Positive) 순서로 작성되고 있는 것 같습니다 !

2023-07-28 00:42 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
> +            @NotNull(message = "반려 식물 ID가 포함되어야 합니다.") @Positive(message = "반려 식물 ID는 1이상의 값이어야 합니다.") @RequestParam("petPlantId") Long petPlantId,
### C

URL 파라미터가 누락된 경우 `@NotNull`이 검증되는지 궁금합니다 !!
해당 테스트가 있으면 한눈에 확인할 수 있겠네요 🙃

2023-07-28 00:42 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +}
### R

애플리케이션 코드 마지막 줄에 라인 하나 추가해주세요 !!
없으면 깃허브에서 경고를 보여준답니다 ㅜㅜ

2023-07-28 05:04 UTC, Choi-JJunho requested changes
고생하셨습니다!
develop 브랜치 최신 반영사항 pull 한 뒤에 추가작업 부탁드립니당~

2023-07-28 05:04 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +        );
### C
SoftAssertions.assertSoftly를 사용해보는건 어떤가요?
실패한 코드의 라인 위치를 보여주기 때문에 디버깅에 유용한 기능이라고 생각합니다.

다음과 같이 사용할 수 있습니다.

```java
assertSoftly(softly -> {
        softly.assertThat(histories1.getContent().get(0).getId()).isEqualTo(history1.getId()),
        softly.assertThat(histories2.getContent().get(0).getId()).isEqualTo(history2.getId()),
        softly.assertThat(histories1.getTotalElements()).isEqualTo(2L),
        softly.assertThat(histories2.getTotalElements()).isEqualTo(2L),
        softly.assertThat(histories1.getTotalPages()).isEqualTo(2),
        softly.assertThat(histories2.getTotalPages()).isEqualTo(2)
    }
);
```

2023-07-28 05:04 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +        );
### C
> SoftAssertions.assertSoftly를 사용해보는건 어떤가요?

ditto

2023-07-28 11:03 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +@RequiredArgsConstructor
뇌를 빼놓고 있었군요ㅎㅎ수정하겠습니다!

2023-07-28 11:09 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
> +            @RequestParam Integer page,
사실 처음에는 저도 Pageable 객체 형태로 파라미터에 받는 방식을 사용했었는데요!
컨트롤러를 보았을 때 파라미터로 어떤 값이 넘어오는지 명확하게 표현하고 싶었고, 지금 상황에서 page와 size 이외에 다른 쿼리 파라미터를 사용하지 않고 있으므로 두 정보만 받아오고 있음을 확실히 지정하고 싶었습니다!
하지만 확장성 측면에서 볼 때 조금 아쉬운 측면이 있겠네요...

2023-07-28 11:12 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +    PetPlant petPlant;
private으로 접근을 제어했습니다!
그런데 궁금한 점은 사실 테스트 코드에서 private 접근지정자를 사용할 필요성을 못 느끼고 있는데,
혹시 필요한 이유가 있으면 알려주시면 감사하겠습니다ㅎㅎ

2023-07-29 07:46 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +    void setUp() {
테스트 메소드가 하나만 존재하다 보니 이에 대해서 간과한 것 같네요! 
만약 모든 테스트에서 위 객체들을 사용한다면 @BeforeEach로 할당하는 게 맞겠지만 그레이의 말처럼 이 객체를 사용하지 않을 경우에 위험이 발생할 것 같아요. 수정하겠습니다!

2023-07-29 07:48 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +        historyRepository.save(history1);
하하 제가 support를 사용하는 시점에 이미 영속화 동작이 있다는 것을 잠시 잊었네요ㅎ....
수정했습니다!

2023-07-29 08:08 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/mapper/HistoryMapper.java
> +    public static HistoryResponse toHistoryResponse(Page<History> historyPageByPetPlantId, boolean isLastPage) {
저도 이 부분을 고민하긴 했는데요!
현재 파라미터가 Page 인터페이스를 통해 값을 받아오고 있어서, 해당 네이밍을`historyPageByPetPlantI`로 구성했었습니다.
그레이의 의견을 듣고 나니 "어떠한 반려 식물의 히스토리들"이라는 네이밍이 적합해 보입니다!
`petPlantHistory`로 변수명을 변경했습니다

2023-07-29 08:10 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +    private boolean isLastPage(int nowPage, int totalPages) {
해당 메소드 기능이 존재하고 있는지 몰랐네요! 적용해보는게 좋을 것 같습니다ㅎㅎ

2023-07-29 08:39 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +    class 히스토리_ {
꼼꼼한 추가 감사합니다 :) 해당 테스트를 짜다 보니 page와 size에 대해서도 validation을 수행해야 하겠다고 생각이 들어 추가했어요

2023-07-29 08:50 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +    void setUp() {
반영 완료했습니다 👍

2023-07-29 09:05 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
> +            @NotNull(message = "반려 식물 ID가 포함되어야 합니다.") @Positive(message = "반려 식물 ID는 1이상의 값이어야 합니다.") @RequestParam("petPlantId") Long petPlantId,
반영 완료했습니다 👍

2023-07-29 09:10 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
> +            @NotNull(message = "반려 식물 ID가 포함되어야 합니다.") @Positive(message = "반려 식물 ID는 1이상의 값이어야 합니다.") @RequestParam("petPlantId") Long petPlantId,
테스트를 만들어 보니 `$.message`에 value 값이 들어가지 않는군요! null 값이 들어갈 때 자동으로 예외가 발생해 400이 반환하는 것을 확인하는 테스트를 추가했습니다

2023-07-29 09:12 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +}
오오 첨 알게된 사실이네요ㅎㅎ
주노 블로그 참고해서 설정 완료했습니다!

2023-07-29 09:14 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/mapper/HistoryMapper.java
> +    public static HistoryResponse toHistoryResponse(Page<History> historyPageByPetPlantId, boolean isLastPage) {
`Page` 인터페이스에 `isLast()`라는 메소드가 존재하고 있어, `isLastPage` 변수를 제거하고 해당 메소드를 통해 `hasNext` 필드를 세팅했습니다!

2023-07-29 09:16 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +        int nowPage = historyPageByPetPlantId.getPageable().getPageNumber() + 1;
반영했습니다 👍  좋은 네이밍 추천 고마워용

2023-07-29 09:45 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
> +    public ResponseEntity<HistoryResponse> read(
Member 값이 넘어오는 경우를 고려하지 못했군요! 파라미터 추가 후 확인 검증 로직까지 HistoryService에 추가했습니다

2023-07-29 09:47 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +class HistoryRepositoryTest {
수정했습니다!!

2023-07-29 09:55 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +        );
반영했습니다! 유용한 기능 알려줘서 고마워요ㅎㅎ

2023-07-30 09:36 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/mapper/HistoryMapper.java
> +    public static HistoryResponse toHistoryResponse(Page<History> historyPageByPetPlantId, boolean isLastPage) {
좋아요 !! 굿굿

2023-07-31 02:40 UTC, Choi-JJunho requested changes
고생하셨습니다!
요청드렸던 내용 반영 잘해주셨네요! 👍
마지막으로 테스트에서 몇가지 부분만 보완하면 좋을 것 같아 코멘트 남겼습니다!

2023-07-31 02:40 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +
### R
공백 하나만 제거해주세용

2023-07-31 02:40 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +                .build();
### C
영속화 시키는 메서드를 private 메소드로 분리해보는건 어떤가요?
분리해두면 향후 다른 테스트가 추가되었을 때 사용하기 용이할 것 같네요

2023-07-31 02:40 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +        );
### C
`assertSoftly` 반영아 안된거같아요~

2023-07-31 02:40 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +        ).isInstanceOf(IllegalArgumentException.class).hasMessage("다른 사용자의 반려식물을 조회할 수 없습니다");
### A
가독성을 위해 `.` 하나에 개행 하나로 표현하는건 어떨까요?
```suggestion
        ).isInstanceOf(IllegalArgumentException.class)
        .hasMessage("다른 사용자의 반려식물을 조회할 수 없습니다");
```

2023-07-31 02:40 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +        ).isInstanceOf(NoSuchElementException.class).hasMessage("id에 해당하는 반려식물이 없습니다");
### A 
> 가독성을 위해 `.` 하나에 개행 하나로 표현하는건 어떨까요?
ditto

```suggestion
        ).isInstanceOf(NoSuchElementException.class)
        .hasMessage("id에 해당하는 반려식물이 없습니다");
```

2023-07-31 05:17 UTC, Kim0914 requested changes
리뷰 반영해주신 부분 확인했습니다 !!

추가적으로, 함께 살펴볼 부분 코멘트 남겼는데 마지막으로 확인 부탁드릴게요 💚

2023-07-31 15:29 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +        );
누락했네요ㅠㅠ 반영했습니다!

2023-07-31 15:42 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +        ).isInstanceOf(IllegalArgumentException.class).hasMessage("다른 사용자의 반려식물을 조회할 수 없습니다");
반영했습니다 👍

2023-07-31 15:43 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +        ).isInstanceOf(NoSuchElementException.class).hasMessage("id에 해당하는 반려식물이 없습니다");
반영 완료했습니다 👍

2023-07-31 16:38 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +        if (petPlant.getMember().getId() != member.getId()){
PetPlant에 hadSameMember()라는 메소드를 만들어 처리했습니다! 👍

2023-07-31 17:32 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +
반영했습니다 👍

2023-07-31 18:04 UTC, rawfishthelgh commented
@Choi-JJunho @Kim0914 
피드백 반영 완료했습니다~!
추가로 물주기 날짜 기준으로 내림차순 정렬해 반환하도록 하는 기능도 추가했어요

2023-08-01 01:35 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/Member.java
> +    @Override
### R

라인 구분해주세요 !

2023-08-01 01:42 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +        Page<History> historyPageByPetPlantId = historyRepository.findAllByPetPlantId(petPlantId, PageRequest.of(request.getPage(), request.getSize(), Sort.Direction.DESC,"waterDate"));
### R

`,` 공백 구분 부탁드립니다 ~

2023-08-01 01:42 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/dto/HistoryPageRequest.java
> +    @NotNull
### R

여기도 한 줄 공백 !

2023-08-01 01:43 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +public class HistoryServiceTest extends IntegrationTest {
### C

내림차순으로 값을 가져오는 로직에 대한 검증은 없어도 괜찮을까용?!

2023-08-01 06:22 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/Member.java
> +    @Override
반영 완료! 👍

2023-08-01 06:25 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +        Page<History> historyPageByPetPlantId = historyRepository.findAllByPetPlantId(petPlantId, PageRequest.of(request.getPage(), request.getSize(), Sort.Direction.DESC,"waterDate"));
반영 완료 ! 👍

2023-08-01 06:25 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/dto/HistoryPageRequest.java
> +    @NotNull
반영완료! 👍

2023-08-01 06:36 UTC, Choi-JJunho commented
<img width="827" alt="image" src="https://github.com/woowacourse-teams/2023-pium/assets/49794401/a61b3721-2a05-460e-a219-5cdcbf0ad71e">

`git pull origin develop` 으로 develop 브랜치의 변경사항 적용해주세용~

2023-08-01 06:56 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +public class HistoryServiceTest extends IntegrationTest {
해당 검증코드 추가했습니다! service layer 단에서는 검증할 생각을 못 했는데 고마워요ㅎㅎ

2023-08-01 07:14 UTC, rawfishthelgh commented
@Choi-JJunho @Kim0914 
충돌 해결 및 컨벤션 정렬 완료했습니다~!

2023-08-01 08:34 UTC, Choi-JJunho requested changes
고생하셨습니다~
몇가지 반영하면 좋을 것 같은 내용들이 있어서 추가로 코멘트 남겼습니다

2023-08-01 08:34 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/mapper/HistoryMapper.java
> +        int currentPage = petPlantHistory.getPageable().getPageNumber() + 1;
### A
MagicNumber를 상수로 표현해도 좋을 것 같아요
`ADJUSTMENT_PAGE_VALUE`와 같은 이름은 어떨까요?

2023-08-01 08:34 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +        if (!petPlant.hasSameMember(member)) {
### R
위에서 이야기한 `isNotOwnerOf` 메서드로 대체하면 좋을 것 같아요

2023-08-01 08:34 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +            given(historyService.read(any(), any(), any()))
### C
Mocking 한 테스트에 대해서 `any()` 내부에 어떤 클래스인지 명시해주는건 어떤가요?
함수에 어떤 값이 들어가는지 명시적으로 표현해주는것이 좋아보여요

```suggestion
            given(historyService.read(anyLong(), any(HistoryPageRequest.class), any(Member.class)))
```

2023-08-01 08:34 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +    class 히스토리_ {
### C
`@Nested`의 선언을 조금 더 구체적으로 변경해보는건 어떨까요?
```suggestion
    class 히스토리_조회_시_ {
```

2023-08-01 08:37 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/repository/HistoryRepository.java
> +    Page<History> findAllByPetPlantId(Long petPlantId, Pageable pageable);
현재는 빈 배열을 응답하고 있습니다! 어떤 방식으로 처리할지는 팀원들과 논의를 한 번 더 해봐야겠군요

2023-08-01 08:39 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +    }
대체 완료했습니다 👍

2023-08-01 08:39 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +
반영 완료 👍

2023-08-01 08:41 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/mapper/HistoryMapper.java
> +        int currentPage = petPlantHistory.getPageable().getPageNumber() + 1;
해당 네이밍으로 수정했습니다!
저도 다시 보니까 매직넘버가 없어 무슨 로직이지 싶었네요...ㅋㅋㅋㅋ

2023-08-01 08:42 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +        if (!petPlant.hasSameMember(member)) {
대체 완료 👍

2023-08-01 08:42 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +            given(historyService.read(any(), any(), any()))
### R

`ditto`

2023-08-01 08:43 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +            given(historyService.read(any(), any(), any()))
### R

`ditto`

2023-08-01 08:43 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +            given(historyService.read(any(), any(), any()))
반영 완료했습니다! 이런 부분도 테스트 가독성에 영향을 줄 수 있군요

2023-08-01 13:54 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +    class 히스토리_ {
반영완료 ! 👍

2023-08-02 02:34 UTC, rawfishthelgh commented
@Kim0914 @Choi-JJunho 
페이지 인덱스 0으로 시작하는 것으로 변경 & Pageable 객체로 바인딩하여 수정했습니다!

2023-08-02 03:43 UTC, Choi-JJunho requested changes
고생하셨습니다~
에러메시지와 관련된 부분만 수정되면 Approve해도 될 것 같아요

2023-08-02 03:43 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +public class HistoryServiceTest extends IntegrationTest {
### C

해당 설정 동일하게 붙여주세요~

```suggestion
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
@SuppressWarnings("NonAsciiCharacters")
public class HistoryServiceTest extends IntegrationTest {
```

2023-08-02 04:34 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +                .orElseThrow(() -> new NoSuchElementException("id에 해당하는 반려식물이 없습니다"));
통일했습니다!

2023-08-02 04:34 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +            throw new IllegalArgumentException("다른 사용자의 반려식물을 조회할 수 없습니다");
통일했습니다!

2023-08-02 04:35 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +public class HistoryServiceTest extends IntegrationTest {
적용했습니다!

2023-08-02 04:35 UTC, yeonkkk reviewed
하마드 고생하셨습니다! 
저도 코멘트 조금 남겨 봅니다~

2023-08-02 04:35 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +
### A

공백이 있네요!

2023-08-02 04:39 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
> +
제거했습니다!

2023-08-02 04:40 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +            mockMvc.perform(get("/history?petPlantId=1&page=1&size=4")
### C

URL을 하드코딩해서 작성할 수도 있지만
mockMvc에서 param도 제공합니다 !
해당 기능을 활용해보는건 어떨까요?
```suggestion
            mockMvc.perform(get("/history")
            .param("petPlantId", "1L") ....
```

2023-08-02 04:40 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +            mockMvc.perform(get("/history?petPlantId=1&page=1&size=4")
쿼리 파라미터를 쓰는 테스트 모두 동일하게 적용할 수 있을 것 같아요 !

2023-08-02 04:40 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/HistoryService.java
> +                .orElseThrow(() -> new NoSuchElementException("id에 해당하는 반려식물이 없습니다"));
반영완료!

2023-08-02 04:41 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +
반영완료!

2023-08-02 05:07 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +            mockMvc.perform(get("/history?petPlantId=1&page=1&size=4")
반영완료!

2023-08-02 05:08 UTC, Kim0914 approved these changes
하마드 !
저희 서비스의 기둥인 히스토리 구현하시느라 고생많았습니다 ㅎㅎ
리뷰 주고 받으면서 저도 많이 배웠네요 ~~
다른 분들이 남겨놓은 코멘트로도 충분해서 저는 이만 approve 하겠습니다 😉

2023-08-02 05:13 UTC, Choi-JJunho approved these changes
고생하셨습니다~
더 수정할 내용이 없어보여 Approve 하겠습니다 👍

2023-08-02 05:13 UTC, merged