feat: 내 반려 식물 상세 조회 페이지
woowacourse-teams/2023-pium pull request #150
Opened 2023-07-27 13:31 UTC by WaiNaat

# 🔥 연관 이슈

- close #126

# 🚀 작업 내용

![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/82a76517-613c-4bbd-8c08-1cebaa0f0f2c)

- 간단한 스피너 만들기
    - 기존 Suspense fallback에 스피너 넣기
- 이미지 컴포넌트 통합
    -  'wide' 타입 추가해서 사전/반려 식물에 활용하기
- API 명세 추가에 따른 msw 업데이트
    -  mock data
    -  반려 식물 목록
    - 반려 식물 1개 조회
-  비동기 통신 추가
    - fetch
    - useQuery 
- 내 반려 식물 상세 보기 페이지
    - API 요청의 반환값들 보여주기
    - 식물 사전 정보로 바로 갈 수 있는 버튼 만들기
    - Suspense 적용하기
    - 생일이면 왕관 보여주기 (id를 4로 주면 생일입니다)

# 💬 리뷰 중점사항

디자인을 중점적으로 봐주세요!!!

2023-07-28 06:52 UTC, bassyu approved these changes
빠르고 이쁘게 만들어주셨네요!! 감사합니다 참새~
디자인은 물주기에서 숫자랑 `일마다` 를 살짝 띄우는건 어떤지 제안해봅니다!

2023-07-28 06:52 UTC, bassyu commented on frontend/src/components/@common/Spinner/index.tsx
### A

오 스피너도 추가됐네요! 좋아요

2023-07-28 06:59 UTC, hozzijeong requested changes
피곤하신데도 잘 만들어주셨네요! 고생하셨습니다 참새!

디자인 위주로 봐달라고 하셔서 디자인 위주로 코멘트 남겼습니다.

추후에 수정 버튼, 타임라인 보기등으로 이동(?) 할 수 있는 버튼이 있으면 좋을 것 같아요

2023-07-28 06:59 UTC, hozzijeong commented on frontend/src/pages/PetDetails/index.tsx
> +      <PetDetailsContent petPlantId={Number(id)} />
### R

id가 undefiend인 경우도 한번 고려해봐야 할 것 같아요!

2023-07-28 06:59 UTC, hozzijeong commented on frontend/src/components/PetDetails/PetDetails.style.ts
> +export const EnvironmentTitle = styled.span`
### C

혹시 다음과 같은 디자인은 어떤가요??

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/e04ba3f5-ce6c-4c52-b6f8-074633532fcf)

```ts 
export const IconBox = styled.div` // EnvironmentTitle입니다.
  display: inline-flex;
  align-items: center;
  justify-content: center;

  width: 24px;
  height: 24px;

  font-weight: bold;
  color: ${({ theme }) => theme.color.primary};

  background: ${({ theme }) => theme.color.background};
  border-radius: 50%;
  svg {
    width: 20px;
    height: 20px;
  }
`;
```
(컴포넌트 내부의 gap도 4px, 8px로 줄였습니다)

2023-07-28 06:59 UTC, hozzijeong commented on frontend/src/components/@common/Image/Image.style.ts
> +  min-width: ${({ type, theme }) => (type === 'wide' ? theme.width.pad : '')};
### R

min-width 설정에서 이 부분이 좀 깨지는것 같습니다. 확인 부탁드려요

2023-07-28 06:59 UTC, hozzijeong commented on frontend/src/components/PetDetails/index.tsx
> +            <Text>피움과 함께한 지</Text>
### C

나타나는 날짜를 YYYY-MM-DD 보다 며칠 남음. 며칠 지남 등으로 바꿔보면 어떤가요??

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/508b32f5-f579-47a4-a1f9-80386613a295)

2023-07-28 06:59 UTC, hozzijeong commented on frontend/src/components/PetDetails/index.tsx
> +            <Text>피움과 함께한 지</Text>
"다음 물 줄 날 3일 후" 이렇게 해도 나쁘지 않겠네요...ㅎ

2023-07-28 06:59 UTC, hozzijeong commented on frontend/src/constants/index.ts
> +  process.env.NODE_ENV === 'development' ? 'http://localhost:8282' : 'http://api.pium.life';
### A 

아마 변경 필요할 것 같습니다 🌝

2023-07-28 06:59 UTC, hozzijeong commented on frontend/src/types/api/petPlant.ts
> +  dictionaryPlantId: DictionaryPlant['id'];
타입 재사용 너무 좋네요 ㅎ

2023-07-28 12:08 UTC, WaiNaat commented on frontend/src/pages/PetDetails/index.tsx
> +      <PetDetailsContent petPlantId={Number(id)} />
주소를 그냥 `pium.life/pet/`으로 하면 내 반려 식물 목록이 나온다고 생각해서 따로 처리를 하지 않았었습니다. 혹시 이거 말고도 제가 놓친 부분이 있을까요??

2023-07-28 12:08 UTC, WaiNaat commented on frontend/src/components/PetDetails/PetDetails.style.ts
> +export const EnvironmentTitle = styled.span`
오 이쁜데요? 좋아요

2023-07-29 02:54 UTC, WaiNaat commented on frontend/src/components/@common/Image/Image.style.ts
> +  min-width: ${({ type, theme }) => (type === 'wide' ? theme.width.pad : '')};
확인 결과 min-width가 딱히 필요 없는 것 같아서 지웠어요

2023-07-29 04:05 UTC, WaiNaat commented on frontend/src/components/PetDetails/index.tsx
> +            <Text>피움과 함께한 지</Text>
'3일 후'로 반영했어요!

2023-07-29 04:08 UTC, WaiNaat commented
최종 변경된 시안은 이런 느낌이에요

![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/40369ac4-e3e7-4db3-a303-5688c54a2be5)

왕관은 생일자 옆에 나타나는 아이콘입니다

2023-07-30 11:51 UTC, hozzijeong commented on frontend/src/pages/PetDetails/index.tsx
> +      <PetDetailsContent petPlantId={Number(id)} />
늦은 답장 죄송합니다! 

타입 검사를 했을때 id가 string | undefiend여서 분기처리가 필요하지 않을까? 하는 생각에 답변을 단 것이었습니다. 적절하게 컨트롤 된다면 딱히 문제가 있어보이지는 않네요

2023-07-30 12:03 UTC, hozzijeong approved these changes
늦게 확인해서 죄송합니다!! 변경된 부분 확인했습니다 고생하셨어요 참새!

2023-07-30 12:04 UTC, merged