feat: 반려 식물 목록 페이지 구현
woowacourse-teams/2023-pium pull request #156
Opened 2023-07-30 06:20 UTC by bassyu

# 🔥 연관 이슈

- close #138

# 🚀 작업 내용

반려식물 카드랑 카드 리스트 페이지를 만들었습니다.

<img width="383" alt="스크린샷 2023-07-30 오후 3 18 15" src="https://github.com/woowacourse-teams/2023-pium/assets/54442420/d81eb64d-0eac-4025-9cc9-f4875b0363e6">

# 💬 리뷰 중점사항

원래는 스켈레톤을 적용하려고 했는데, 보통 화면이 꽉 찰 정도로 반려 식물 카드가 많지는 않을 것 같았습니다. 
그래서 suspense로 대체 화면을 보여주는게 나을거라 생각했어요!

디자인 리뷰도 환영입니다!

2023-07-31 02:41 UTC, WaiNaat requested changes
쵸파 안녕하세요 🦌 깔끔하게 카드 만들어주셔서 감사해요. 확실히 사진이 대문짝만하게 있는 게 훨씬 이쁜 것 같아요

디자인 관련해서 제 생각은 여기에 적을게요.
우선 제가 대략적으로 만든 개선안이에요

![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/6361d4a4-e62e-477f-9d3e-e9d1c9f69513)

### 추가하기 버튼
저는 이게 너무 시선을 뺏는다고 느꼈어요. 멀리서 봤을 때 식물 카드가 아니라 이 버튼이 제일 먼저 보이더라구요. 개인적으로는 조금 더 흐리거나 아니면 배경을 흰색으로 하는 게 어떤가 하는 생각이 듭니다.
```css
font-size: 3.6rem;
color: ${(props) => props.theme.color.primary};
background: ${(props) => props.theme.color.background};
border: 1px solid ${(props) => props.theme.color.primary};
```
위쪽 사진엔 이렇게 적용했어요

![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/1f1f7678-4fa5-4790-8d07-de539ff83ac6)
![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/4124a390-59a2-4f2b-b146-e57d016c058e)

아니면 아예 회색으로 가도 좋을 것 같아요

### 카드
다 좋은데 테두리가 없어서 이름 부분을 봤을 때 시야가 카드 한 개가 아니라 그 주변까지 넓어지면서 집중이 흩어지는 느낌이에요.
```css
border: 1px solid ${({ theme }) => theme.color.gray};
```
Wrapper에 이거 하나만 추가했습니다

2023-07-31 02:41 UTC, WaiNaat commented on frontend/src/pages/PetList/index.tsx
> +            <PetCard key={pet.id} pet={pet} onClick={goPetDetail} />
### R

[div에 onClick을 달아서 사용하는 경우 접근성을 위해서 처리해야 하는 작업](https://betterprogramming.pub/how-to-turn-a-div-into-an-accessible-button-in-react-fbf236283d6d)이 생각보다 많더라구요.. 페이지 이동 로직은 `<Link>`를 이용하는 건 어떨까요?

추가적으로 onClick이 이벤트 객체가 아니라 number를 인자로 받는다는 점도 어색해 보입니다

2023-07-31 02:41 UTC, WaiNaat commented on frontend/src/types/api/petPlant.ts
> +}
### R

develop꺼 땡겨오시면서 밑에 NewPetPlantRequest랑 PetPlantDetails가 생겼을 것 같은데 이 친구들에게서 필요한 부분을 따 오는 방식이 더 어울릴 것 같아요

2023-07-31 02:41 UTC, WaiNaat commented on frontend/src/pages/PetList/index.tsx
> +          <RegisterButton onClick={goRegister}>+</RegisterButton>
### R

type="button"
aria-label="반려 식물 등록하기"

추가 부탁드려요 👍

2023-07-31 02:41 UTC, WaiNaat commented on frontend/src/hooks/queries/pet/usePetList.ts
> +    placeholderData: keepPreviousData,
### R?

요 부분도 아마 suspense 터지면 필요가 없을 것 같긴 한데 잘 모르겠네요

2023-07-31 03:41 UTC, hozzijeong requested changes
깔끔하게 잘 만들어 주셨네요! 고생하셨습니다 쵸파!!

저도 디자인 적인 부분은 여기서 얘기하겠습니다 ㅎ
![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/def7ec3f-d67e-43c4-86b7-99e48bca87a9)

참새가 준 의견처럼 추가하기 카드의 색이 좀 밋밋하게 갔으면 좋겠습니다. 저는 `grayLight`를 줬어요.

또한 식물 종이랑 별명이랑 둘 다 같은 색으로 주니까 시선이 분산되더라구요... 그래서 식물 별명에 font-weight를 좀 더 주고, 식물 종 이름은 색을 `gray`로 변경했습니다.

마지막으로 D+xx인데, 하이라이트를 주는 폰트 크기를 D+ 폰트 크기와 동일하게 줬습니다. 거기에 D+ xx로 날짜와 D사이를 좀 띄웠어요!

마지막으로 헤더아 border-bottom을 주는 식으로 카드와 헤더를 구분해 보는 것은 어떤가요?? (이건 개인적인 의견입니다)

PS. 이전 브랜치들을 머지하고 PR을 작성하니 쵸파의 코드만 보고 리뷰하기가 쉽지 않더라구요... PR을 올릴때는 쵸파의 commit만 올려주실 수 있나요? (물론 저도 토스트 PR올릴때 처리 못해서 다시 올렸습니다 하하;;)

2023-07-31 03:41 UTC, hozzijeong commented on frontend/src/components/PetCard/index.tsx
> +        <Image src={imageUrl} type="square" size="100%" />
### R

alt 추가 부탁드려요

2023-07-31 03:41 UTC, hozzijeong commented on frontend/src/hooks/queries/pet/usePetList.ts
> +    select: ({ data }) => data,
### C

딱히 데이터에 변환을 주지 않는데 select를 사용한 이유가 있을까요??

2023-07-31 06:19 UTC, bassyu commented on frontend/src/apis/pet.ts
> +    headers: { 'Content-Type': 'application/json' },
헉 이거 상수화 해서 적용 해야겠네요!

2023-07-31 06:23 UTC, bassyu commented on frontend/src/hooks/queries/pet/usePetList.ts
> +    staleTime: Infinity,
그러네요! PetList는 자주 바뀔 예정이니 지우겠습니다!

2023-07-31 06:24 UTC, bassyu commented on frontend/src/pages/PetList/index.tsx
> +            <PetCard key={pet.id} pet={pet} onClick={goPetDetail} />
좋은 것 같습니다! Link로 대체할게요!

2023-07-31 06:25 UTC, bassyu commented on frontend/src/types/api/petPlant.ts
> +}
오 PetPlantDetails 가 있었군요 
merge하고는 잘 안봤는데 반영할게요!

2023-07-31 06:30 UTC, bassyu commented on frontend/src/hooks/queries/pet/usePetList.ts
> +    placeholderData: keepPreviousData,
정확하게 뭔지 모르겠네요.. 우선 빼겠습니다!

2023-07-31 06:31 UTC, bassyu commented on frontend/src/hooks/queries/pet/usePetList.ts
> +    select: ({ data }) => data,
자세히 보시면 `PetListResponse`를 `Pet[]`로 구조분해 할당하는 과정입니다!

2023-07-31 10:11 UTC, hozzijeong commented on frontend/src/hooks/queries/pet/usePetList.ts
> +    select: ({ data }) => data,
아하 data 프로퍼티를 받는거군요!! 감사합니다👍

2023-08-01 04:44 UTC, hozzijeong requested changes
변경된 내용 확인했습니다! 요청 드린것만 확인 부탁드려요 고생하셨습니다 쵸파!

2023-08-01 04:44 UTC, hozzijeong commented on frontend/src/components/PetCard/index.tsx
> +        <Image src={imageUrl} type="square" size="100%" />
### R

alt 추가 다시한번 부탁드립니다!

2023-08-01 04:44 UTC, hozzijeong commented on frontend/src/components/PetCard/index.tsx
> +      <ContentArea>
### R 

이 부분에서도 접근성 고려해서 어떤 식물에 대한 설명인지, 이름 등등에 대한 정보를 좀 더 상세하게 넣으면 좋을 것 같아요.
지금은 참새 참새 D+1 이런식으로 나오는데, 별명, 식물 종 등등에 대한 이야기가 추가로 붙으면 좋을 것 같습니다.

2023-08-01 04:44 UTC, hozzijeong commented on frontend/src/pages/PetList/index.tsx
> +          <Link to={URL_PATH.petRegisterSearch}>
### R

해당 링크가 어떤 링크인지에 대한 설명이 추가되면 좋을것 같아요. 지금은 Link, + 이렇게밖에 나오지 않습니다

2023-08-01 04:52 UTC, WaiNaat requested changes
바뀐 부분들 확인했어요. 로컬에서도 이쁘게 잘 나옵니다!

2023-08-01 04:52 UTC, WaiNaat commented on frontend/src/components/PetCard/index.tsx
> +        <Image src={imageUrl} type="square" size="100%" />
### R
alt 추가 부탁드려요2

2023-08-01 04:52 UTC, WaiNaat commented on frontend/src/components/PetCard/index.tsx
> +}: PetCardProps) => {
### C

바로 PetPlant를 사용하는 게 아니라 Props라는 이름으로 한번 더 감싼 이유가 있나요?

2023-08-01 04:52 UTC, WaiNaat commented on frontend/src/apis/pet.ts
> +      Authorization: 'pium@example.com',
### R

이거 `pium@gmail.com`이래요!!

2023-08-01 05:00 UTC, bassyu commented on frontend/src/components/PetCard/index.tsx
> +      <ContentArea>
`aria-label` 말씀하시는 것 맞을까요? 추가하도록 하겠습니다!

2023-08-01 05:01 UTC, bassyu commented on frontend/src/pages/PetList/index.tsx
> +          <Link to={URL_PATH.petRegisterSearch}>
아래처럼 해볼게요!
```suggestion
          <Link to={URL_PATH.petRegisterSearch} aria-label="식물 추가로 이동">
```

2023-08-01 05:05 UTC, bassyu commented on frontend/src/components/PetCard/index.tsx
> +}: PetCardProps) => {
원래 onClick이 있었는데 사라지면서 아예 같아졌네요! 딱히 이유가 없으니 합쳐도 좋을 것 같습니다~

2023-08-01 05:44 UTC, hozzijeong reviewed
마지막 부분만 한번 확인 부탁드립니다!

2023-08-01 05:44 UTC, hozzijeong commented on frontend/src/pages/PetList/index.tsx
> +              aria-label="식물 상세로 이동"
### R

이 부분이 "식물 상세로 이동" 이라고 하면 어떤 식물로 이동인지가 잡히지 않더라구요... 그래서 

```typescript
aria-label={`${petPlantCard.nickname}의` 상세로 이동`}
```

과 같이 명확하게 특정 지을 수 있으면 더욱 좋을 것 같습니다!

추가적으로 a태그 안에서 `aria-label`을 읽으니까 안에 있는 섹션별로 읽어지는게 아니라 안에 있는 label들이 전부 읽어지네요... 접근성 너무 어렵습니다 ㅠ

2023-08-01 07:04 UTC, bassyu commented on frontend/src/pages/PetList/index.tsx
> +              aria-label="식물 상세로 이동"
오.. 일단 nickname까지 label에 넣는 걸로 하겠습니다!

2023-08-01 07:24 UTC, hozzijeong approved these changes
확인했습니다! 고생하셨어요 쵸파! Approve할게용

2023-08-01 10:22 UTC, WaiNaat requested changes
반영해 주신 부분들 확인했어요! 충돌만 해결되면 approve하겠습니다

2023-08-01 11:18 UTC, WaiNaat approved these changes
머지 확인했어요
고생하셨습니다 쵸파 🦌

2023-08-01 11:19 UTC, merged