feat: 반려 식물 조회 사용자 검증 기능 추가
woowacourse-teams/2023-pium pull request #172
Opened 2023-08-01 08:32 UTC by Kim0914

# 🔥 연관 이슈

- close #169 

# 🚀 작업 내용
- 반려 식물 조회, 수정 시 사용자 검증 기능을 추가했습니다.
- 추가적으로 코드 컨벤션에 맞도록 리팩토링을 진행했습니다.
- 테스트 코드 mocking시 any()에 타입을 명시하도록 했습니다.
- 누락된 테스트 코드를 작성했습니다. (반려 식물 정상 수정 컨트롤러 테스트, 반려 식물 주인 확인 도메인 테스트)

# 💬 리뷰 중점사항
사용자 인증이 필요한 부분(`@Auth`) 누락된 부분이 없는지 확인 부탁드려요 !

2023-08-01 08:38 UTC, Choi-JJunho approved these changes
고생하셨습니다~

2023-08-01 08:38 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        otherMember = memberSupport.builder().build();
### A 
otherMember 같은 경우는 모든 테스트 상황에서 사용되는 일반적인 객체가 아니라고 생각해요!
반려 식물의 주인이 아닌 경우에만 otherMember를 따로 선언해줘서 사용하는건 어떨까요?

2023-08-01 09:59 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        otherMember = memberSupport.builder().build();
반영했어요 !

2023-08-01 11:11 UTC, yeonkkk requested changes
고생하셨습니다 그레이! 
코멘트 조금 남겼으니 확인 부탁드려요!

2023-08-01 11:11 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +                            .header("Authorization", "pium@gmail.com")
### C

사전 식물의 경우 로그인하지 않아도 검색 및 조회가 가능한데 테스트에 Authorization header를 넣어준 이유가 있을까요?!
api 명세와 달라서 혼란이 있을 수 있을 것 같아요!

2023-08-01 11:11 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
> +    }
### C
통일성 측면에서 다른 테스트들과 동일하게 wrongId로 빼서 작성할 수 있겠어요!

```suggestion
        void 잘못된_ID로_조회하면_400을_반환() throws Exception {
        Long wrongId = -1L;
        
            mockMvc.perform(get("/pet-plants/{id}", wrongId)
                            .header("Authorization", "pium@gmail.com")
                            .contentType(MediaType.APPLICATION_JSON)
                            .characterEncoding(StandardCharsets.UTF_8))
                    .andExpect(status().isBadRequest())
                    .andExpect(jsonPath("$.message").value(containsString("반려 식물 ID는 1이상의 값이어야 합니다.")))
                    .andDo(print());
        }
    }
```

2023-08-01 11:11 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
> +                            .header("Authorization", "pium@gmail.com")
### C
다른 테스트들과 동일하게 형식을 가져가도 좋을 것 같아요!

```suggestion
            mockMvc.perform(patch("/pet-plants/{id}", 1L)
                            .header("Authorization", "pium@gmail.com")
```

2023-08-01 14:36 UTC, rawfishthelgh requested changes
고생하셨습니다 그레이ㅎㅎ
의견 교환이 필요한 부분 코멘트 남겼습니다! 확인해주세요

2023-08-01 14:36 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
> +            @RequestParam @NotBlank(message = "검색어는 비어있을 수 없습니다.") String name) {
제가 놓친 부분인데 고맙습니당ㅎㅎ

2023-08-01 14:36 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +            throw new IllegalArgumentException("요청 사용자와 반려 식물의 사용자가 일치하지 않습니다. memberId: " + member.getId());
C
member의 id는 입력값이 아닌데 응답할 필요가 있을까요??
이에 대한 의견이 궁금합니다!

2023-08-02 01:59 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +                            .header("Authorization", "pium@gmail.com")
조이가 말씀해주신 부분을 고려해야겠네요 !

사전 식물의 경우 로그인을 하지 않아도 되기 때문에 header는 삭제해야할 것 같습니다 ㅎㅎ
현재 UI 테스트를 상속하고 있는 부분도 함께 제거하겠습니다 !

2023-08-02 04:05 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +            throw new IllegalArgumentException("요청 사용자와 반려 식물의 사용자가 일치하지 않습니다. memberId: " + member.getId());
이 부분은 고민을 했었는데 위와 같이 코드를 짠 이유는 다음과 같습니다.

1. 서비스 계층까지 요청을 내려온 상황은 인증을 정상적으로 통과한 후, **이미 회원은 정상적으로 조회된 상태**이다.
2. 입력으로 받은 사용자와 반려 식물의 주인이 다른 상황에서 **사용자를 식별하는 수단은 회원의 PK인 ID**이다.

현재 저희 서비스는 인증 로직이 없기 때문에 전역 이메일로 인증 과정을 처리하지만, 로그인이 추가되면 세션 방식이든 토큰 방식이든 회원 ID를 담아서 클라이언트에게 전달하고, 클라이언트가 해당 값을 서버로 요청을 보내기 때문에 회원 PK인 memberId가 사용될 것 이라고 예상하고 있습니다 😀

2023-08-02 04:34 UTC, yeonkkk approved these changes
반영 확인했습니다!
고생하셨습니다 그레이👍

2023-08-02 04:36 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +            throw new IllegalArgumentException("요청 사용자와 반려 식물의 사용자가 일치하지 않습니다. memberId: " + member.getId());
이 부분은 로깅관련해서 구체화할 때 한번 더 이야기 해보면 좋을 것 같아요

2023-08-02 04:37 UTC, rawfishthelgh approved these changes
고생하셨습니다~!

2023-08-02 04:38 UTC, merged