feature: 내 반려 식물 정보 수정 페이지
woowacourse-teams/2023-pium pull request #174
Opened 2023-08-01 12:56 UTC by WaiNaat

# 🔥 연관 이슈

- close #167

# 🚀 작업 내용

- api 요청 관련 fetcher, useMutation, msw
- 반려 식물 정보 수정 페이지
- 간단한 cypress 테스트
- 기타 리팩터링
    - 기능이 똑같은 함수 통합 (getDaysBetween, getDaysBetweenDate)
    - form reducer를 훅으로 분리하여 두 개의 페이지가 같이 쓸 수 있도록 변경
    - 모든 `dDay`를 `dday`로 수정 (#165)
    - 별명 입력 최대 30글자로 제한

### 디자인
![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/554ede79-555b-4a56-9408-6bbaebce3028)

1. 반려 식물 상세 정보 페이지에서 넘어오고, 다시 반려 식물 상세 정보 페이지로 돌아가는 만큼 수정 페이지와의 차이를 최소화하고자 했어요. 마치 공책을 열어서 본인이 쓴 내용을 바로 수정하는 느낌?을 주고자 했습니다. 반려 식물 등록 페이지는 역순으로 쌓이는 스택형이라는 특수성 때문에 정보 수정에 사용하기에는 적절하지 않다고 생각했어요
2. 날짜 입력은 기존의 컴포넌트를 재사용했어요
3. 글자 입력이나 select 같은 경우에는 접근성을 생각해서 기본 html 태그 내에서 최대한 정상적으로 보이게끔 만들었어요
4. 성공 또는 실패 시 토스트를 보여줘요. 성공 시 다시 반려 식물 상세 정보 페이지로 이동합니다.

# 💬 리뷰 중점사항

작업 내용별로 커밋 메시지를 나눴습니다. `dday` 때문에 한번에 보시기 힘들면 커밋별로 보는 걸 추천드려요
디자인 관련 피드백도 환영입니다!

2023-08-02 00:43 UTC, WaiNaat commented
현재 navbar가 페이지 내용들을 먹는 현상이 나타나서 확인중입니다

2023-08-02 08:24 UTC, bassyu requested changes
깔끔하네요~~
데이터가 원래 있던 위치에서 바로 인풋으로 바뀌니까 엄청 직관적이고 이쁜 것 같습니다!

폼 입력에서 조금 패턴이 보이는 것 같은데 아직은 뾰족한 수가 떠오르지 않네요.

2023-08-02 08:24 UTC, bassyu commented on frontend/src/components/PetPlantEditForm/index.tsx
> +              {OPTIONS.location.map((locationOption) => (
### C

이거는 나중에 셀렉트 리팩터링 해보겠습니다!

2023-08-02 08:42 UTC, hozzijeong reviewed
고생하셨습니다 참새! 깔끔하게 잘 만들어 주셨네요!!

코멘트 한 부분들 확인 부탁드립니다~!

2023-08-02 08:42 UTC, hozzijeong commented on frontend/src/components/PetPlantEditForm/index.tsx
> +      alert('별명과 물 주기 주기는 공백이 아니어야 해요.');
### C

Toast로 띄워줘도 좋을 것 같습니다!

2023-08-02 08:42 UTC, hozzijeong commented on frontend/src/components/PetPlantEditForm/index.tsx
> +    console.log(value);
### C

console 삭제 부탁드려요!

2023-08-02 08:42 UTC, hozzijeong commented on frontend/src/components/PetDetails/index.tsx
> +        <EditButton type="button" onClick={goToEditPage}>
### C

Link를 사용하지 않고 navigation을 사용하신 이유가 있을까요??

2023-08-02 10:11 UTC, WaiNaat commented on frontend/src/components/PetDetails/index.tsx
> +        <EditButton type="button" onClick={goToEditPage}>
앗 페이지 이동이라 Link가 맞을 것 같은데 생각 없이 버튼을 넣어버렸네요..

2023-08-02 10:21 UTC, WaiNaat commented on frontend/src/components/PetPlantEditForm/index.tsx
> +      alert('별명과 물 주기 주기는 공백이 아니어야 해요.');
토스트에 렌더링 이슈가 있고, 일반적인 상황에서는 제출 버튼 자체가 비활성화되어 있어서 저 문구를 보는 경우는 굉장히 특수한 경우라 alert로 냅뒀습니다. 특수한 경우만을 위해서 훅을 부르는 건 피하고 싶었어요

2023-08-03 06:52 UTC, hozzijeong approved these changes
변경 사항들 확인했습니다 고생하셨어요 참새!

2023-08-03 06:52 UTC, hozzijeong commented on frontend/src/pages/Loading/Loading.style.ts
> +  height: calc(100vh - 68px);
좋아요~

2023-08-03 07:14 UTC, bassyu approved these changes
확인했습니다!

2023-08-03 07:15 UTC, merged