refactor: 핵심 기능 스크린 리더를 활용한 웹 접근성 수정
woowacourse-teams/2023-pium pull request #182
Opened 2023-08-02 07:17 UTC by hozzijeong

# 🔥 연관 이슈

- close #161 

# 🚀 작업 내용
- [x] 스토리북 addon 설치
- [ ] storybook + cypress를 통한 스크린 리더 테스트
- [x] CardBox 테스트
- [x] 달력 테스트
- [x] Toast 테스트
- [x] 미뤄진 날짜 확인 테스트
- [x] 달력 컴포넌트 생성

---

급하게 달력 컴포넌트와 모달 컴포넌트를 만들었습니다. 달력 컴포넌트의 경우에는 이후에 캘린더에도 사용할 것 같아서 날짜를 나타낼 컴포넌트를 `DaySmallBox`라고 언급했습니다. 

모달 컴포넌트 역시 날짜 입력을 받을 때 나타나게 하기 위해 추가했습니다. 

# 💬 리뷰 중점사항

- `dialog`태그를 사용하면 자동으로 focusing이 되는것으로 알고 있는데 이게 잘 안되네요... 어찌어찌 바꿔야지만 적용이 되는데 이 부분을 어떻게 해야 할지 감이 잘 잡히지 않습니다...
- 급하게 만들다 보니 너무 제 입맛대로 바꾼 코드들이 있습니다... 한번 확인해주시고 따끔하게 한마디씩 부탁드려요!
- dialog가 띄워진 상태에서 toast의 `alert`를 읽지 못하는 것 같습니다... 이 부분도 한번 같이 생각해 봤으면 좋겠어요!!
- 반려식물 정보를 읽는 `list`가 너무 솨라락 하고 읽히는것 같은데... 어떤 느낌인지 한번 봐주시면 감사하겠습니다.
```tsx
...
    <ContentBox role="list" tabIndex={0}>
        <NickName role="listitem" aria-label="반려 식물 닉네임">
          {nickName}
        </NickName>
        <DictionaryPlantName role="listitem" aria-label="반려 식물 사전 이름">
          {dictionaryPlantName}
        </DictionaryPlantName>
        <Alert status={status} role="listitem" aria-label="물을 줘야하는 날">
          {alertMessage}
        </Alert>
      </ContentBox>
...
```
- 스크린 리더를 통해 개편해 볼 수 있는 상황을 함께 이야기 해주시면 좋을것 같습니다!

---
총 걸린 시간: 10시간 (대략,,, 어제부터 시작)

스크린 리더 리팩터링 및 학습: 3시간
달력 컴포넌트: 5시간
모달: 30분
나머지 코드 리팩터링: 1시간 30분

2023-08-02 13:36 UTC, WaiNaat requested changes
클린 엄청난 걸 만드셨더라구요ㄷㄷ 멋있어요

### 달력 디자인

- 2023년 7월처럼 6주에 걸친 애가 갑자기 뚱뚱해져요
- 달 바꾸는 버튼이 조금 더 컸으면 좋겠어요 (시력이슈)

### 접근성(윈도우 내레이터)

- '하마드 나무 이미지 이미지' -> 이미지 alt에서 '이미지' 글귀 빼도 될 것 같아요
- Card <ContentBox role="listItem"> '반려 식물 닉네임 1 슬래시 3 수준 1 참새 나무'
- '리마인더 칠월 이십이 그레이 나무 이미지': 22'일'이라는 내용을 표현할 수 있다면 좋을 것 같습니다.
- 시각적으로는 같은 날이라 날짜가 비어 있더라도 읽어 준다면 좋을 것 같아요
- 달력에 '일월화수목금토' 를 읽는데 그렇게 유효한 정보는 아니라는 생각이 들어요. aria-hidden도 괜찮을 듯 합니다
- 달력 제목 '경고 2023년 8월 달력 캘린더' 라고 읽는데 왜 경고가 붙는지는 모르겠습니다
- 토스트는 몇개 시도해봤는데 잘 안 되네요ㅠㅠ

### dialog 관련

autofocus를 하려면 지금처럼 isOpen && 으로 조절하는 방식이 아니라 다이얼로그를 ref같은걸로 찍고 자체 제공하는 showModal, close를 써야 하는 것 같아요

> When using HTMLDialogElement.showModal() to open a \<dialog\>, focus is set on the first nested focusable element.

모달을 아래처럼 수정하니까 autofocus가 작동합니다.
아래 코드 문제점: 배경 클릭으로 안 닫힘, 디자인 깨짐, 첫 focus가 닫기 버튼

```ts
  const body = useRef(document.body);
  const modalRef = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    const clearWindowEvents = () => {
      body.current.querySelector('#root')?.setAttribute('aria-hidden', 'false');
      body.current.style.overflowY = 'auto';
      window.removeEventListener('keydown', keyDownHandler);
    };

    if (isOpen) {
      modalRef.current?.showModal();

      body.current.querySelector('#root')?.setAttribute('aria-hidden', 'true');
      body.current.style.overflowY = 'hidden';
      window.addEventListener('keydown', keyDownHandler);

      return () => {
        clearWindowEvents();
        modalRef.current?.close();
      };
    }

    return clearWindowEvents;
  }, [isOpen]);
```

### 읽는 속도? 관련

속도는 스크린 리더에서 따로 조절이 가능해서 저희 쪽에서 따로 처리할 필요는 없다고 생각해요. 제가 들었을 때도 약간 빠르긴 했는데 평소에도 듣는 속도라고 생각하면 그렇게까지 빠르진 않은 것 같아요

2023-08-03 02:39 UTC, hozzijeong commented on frontend/src/components/@common/Toast/Toast.style.ts
> +  z-index: 3;
z-index 컨벤션을 맞추는게 나아보여요. modal을 사용하다 보면 어쩔수 없이 z-index를 사용하게 되어서 순서를 바꾼다고 해도 효과가 없을 것 같습니다

2023-08-03 02:40 UTC, hozzijeong commented on frontend/src/components/@common/Calendar/DaySmallBox/index.tsx
> +          isToday={isToday ?? null}
요일도 DaySmallBox로 설정을 해놔서, 이부분은 날짜가 아닌 경우이기 떄문에 null을 설정했습니다

2023-08-03 03:47 UTC, hozzijeong commented on frontend/src/components/DateInput/index.tsx
> +  changeCallback?: (value: string) => boolean;
validator가 좋은 것 같아요! min,max이외에도 다른 검증 사항이 있을 것 같아서 validator를 받는 형식으로 진행하겠습니다.

2023-08-03 03:59 UTC, bassyu requested changes
감동입니다 클린..
접근성 쉽지 않았을 텐데 수고하셨습니다!!

2023-08-03 03:59 UTC, bassyu commented on frontend/src/components/@common/Calendar/Calendar.style.ts
> +  width: 100%;
### C

다른 달로 이동할 때 높이가 달라져서 버튼 위치가 달라지는데
캘린더 높이를 고정하는 건 어떤가요?

2023-08-03 04:31 UTC, hozzijeong commented on frontend/src/components/@common/Calendar/Calendar.style.ts
> +  width: 100%;
좋은 생각인것 같아요!

2023-08-03 07:51 UTC, bassyu approved these changes
확인했습니다!

2023-08-03 10:12 UTC, WaiNaat requested changes
변경사항 확인했어요! 윈도우 내레이터도 상식적인 수준으로 읽어주는 것 같습니다

충돌만 해결되면 머지할게요 (개인적인 의견으로는 변경사항이 많아서 웹으로 처리하는 게 아니라 로컬에서 하는 게 좋아 보이긴 해요)

2023-08-03 11:42 UTC, WaiNaat approved these changes
접근성 멋지게 구현해주셔서 감사해요 클린

2023-08-03 11:42 UTC, merged