feat: 반려 식물 타임라인 페이지 구현
woowacourse-teams/2023-pium pull request #183
Opened 2023-08-02 07:32 UTC by bassyu

# 🔥 연관 이슈

- close #164

# 🚀 작업 내용

무한스크롤을 적용한 반려 식물 타임라인 페이지를 구현했습니다.
![타임라인스크린샷](https://github.com/woowacourse-teams/2023-pium/assets/54442420/b6dfc7b1-5bb7-4b80-8376-25b4deb7a9c9)

# 💬 리뷰 중점사항

우선 돌아가긴 하는데 리팩터링이 필요하긴 합니다..

### 무한스크롤 

#### 무한스크롤 페이지에서 쓸만한 함수와 센서 컴포넌트를 추가했는데 어떤지 확인해주세요!

### useInfiniteQuery

페이지별로 response가 나누어져 있었어요
그래서 데이터를 받으면
반환값 -> data -> pages -> page
까지 가야 response.body에 접근할 수 있더라구요

아래처럼 사용했는데, 필수로 줘야하는 옵션이 4개였습니다.

```ts
useInfiniteQuery<HistoryResponse, Error, string[], [string, PetPlantDetails['id']], number>({
  queryKey: [HISTORY, petPlantId],
  queryFn: async ({ pageParam }) => {
    const response = await HistoryAPI.getPetPlant(petPlantId, pageParam);
    const data = await response.json();
    return data;
  },
  defaultPageParam: 0,
  getNextPageParam: ({ hasNext }, _allPages, lastPageParam) => {
    return hasNext ? lastPageParam + 1 : undefined;
  },
  suspense: true,
  select: (data) =>
    data.pages.reduce<string[]>(
      (accWaterDateList, page) => accWaterDateList.concat(page.waterDateList),
      []
    ),
});
```

- queryKey
- queryFn
- defaultPageParam: 
pageParam이 페이징할 때 쓰이는 인덱스인데, 이 초기값을 정해줍니다. 
저희는 0으로 시작하기로 해서 0으로 했습니다.
- getNextPageParam: 
결과로 받은 데이터를 정재해서 다음 pageParam을 반환합니다. 
마지막 페이지면 null 또는 undefined를 반환하도록 되어있는데... null이 안되어서 우선 undefined로 해놨습니다.

나머지 쓸만한 옵션들은 공부하고 이후에 추가해봐야겠어요.

2023-08-02 09:27 UTC, hozzijeong requested changes
와... 이쁘게 잘 만들어주셨네요! 고생하셨습니다 쵸파 ㅠ

코멘트 한번 확인해주세요! 추가적으로, 화면에 나갔다가 다시 들어오면 데이터가 마지막 페이지에 있는 것들로 받고 끝나는데, [refetch](https://tanstack.com/query/v5/docs/react/reference/useQuery) 관련해서 옵션을 추가하면 더욱 좋을 것 같아요!!

2023-08-02 09:27 UTC, hozzijeong commented on frontend/src/components/@common/Sensor/index.tsx
### C

뭔가 이 컴포넌트(?)는 `ref`랑 `height`를 반환하는 hooks로 만들 수 있을것 같은데 쵸파 생각은 어던가요???

2023-08-02 09:27 UTC, hozzijeong commented on frontend/src/pages/PetPlantTimeline/date2map.ts
> +type Month = string;
### C

괜찮으시다면 제가 선언해 놓은 Month 타입이 있습니다! 재사용하면 좋을것 같아요!

2023-08-02 09:27 UTC, hozzijeong commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +  const { id: petPlantId } = useParams();
### R

id 값이 `undefiend`인 경우도 같이 처리해주면 좋을 것  같아요!

2023-08-02 09:27 UTC, hozzijeong commented on frontend/src/pages/PetPlantTimeline/PetPlantTimeline.style.ts
> +`;
### R

NavBar에 가려서 보이지 않는데, 마진을 조금 주면 좋을 것 같아요!

2023-08-02 09:27 UTC, hozzijeong commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +          <PlantImage src={Sprout} />
### R 

alt추가 부탁드려요 ㅎㅎ

2023-08-02 09:46 UTC, bassyu commented
아 참고로 refetch는 msw가 그렇게 구현된거라 실제로는 잘 돌아갈거에요!

2023-08-02 11:20 UTC, WaiNaat commented on frontend/src/pages/PetPlantTimeline/PetPlantTimeline.style.ts
> +`;
요 부분은 제 PR에 해결하는 부분이 있긴 합니다

2023-08-03 02:32 UTC, WaiNaat requested changes
무한스크롤 기가 막히네요 멋있습니다 쵸파

2023-08-03 02:32 UTC, WaiNaat commented on frontend/src/apis/history.ts
> +const HistoryAPI = {
### C

이름이 진짜 history api같긴 하네요ㅋㅋㅋ

2023-08-03 02:32 UTC, WaiNaat commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +    .reverse();
### R
이 부분도 useWaterDateList의 select에서 처리하는 게 깔끔하지 않을까요?

2023-08-03 04:01 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/date2map.ts
ㅋㅋㅋㅋ 좋습니다!

2023-08-03 04:10 UTC, bassyu commented on frontend/src/mocks/handlers.ts
> +let pageParam = 0;
아 그러면 되겠네요!

2023-08-03 04:11 UTC, bassyu commented on frontend/src/components/@common/Sensor/index.tsx
> +  fetcher: () => void;
변수로 넘기는 함수면 전부다 callback이라는 것을 알 수 있다고 생각했습니다!
아니면 `onSense` 도 좋은 것 같아요.

2023-08-03 04:14 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +    .reverse();
이 부분은 조금 고민을 했는데요, 쿼리는 우선 데이터를 반환해주고 그 데이터를 어떻게 랜더링 할지는 컴포넌트의 관심사라고 생각했습니다. 
그래서 딱 페이지를 데이터로 피는 작업만 select로 하고, 
나머지 전처리는 유틸이나 컴포넌트의 관심사로 작성했습니다.

2023-08-03 04:16 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/date2map.ts
> +type Month = string;
좋습니다!

2023-08-03 04:19 UTC, bassyu commented on frontend/src/components/@common/Sensor/index.tsx
오 훅으로 만들어도 좋을 것 같아요!
fetcher를 주면 센서 동작을 할 수 있는 ref를 반환하고, 
그걸 어디에 붙일지는 사용처의 관심사로 둬도 좋겠네요.

2023-08-03 04:33 UTC, WaiNaat commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +    .reverse();
지금도 useInfiniteQuery의 selector에서 데이터를 response 그대로가 아니라 변형해서 돌려주는데,
쿼리가 순수한 데이터만 반환한다고 보기는 힘들다고 생각해요
'딱 페이지를 데이터로 펴는 작업' 역시 저희의 UI만을 위해서 특수하게 데이터를 가공하는 행위인데 추가적인 변형 함수와의 차별점을 모르겠습니다.

2023-08-03 04:34 UTC, WaiNaat commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +    .reverse();
그와 별개로 selector 자체를 유틸함수로 만드는 건 나쁘지 않다고 생각해요

2023-08-03 04:35 UTC, WaiNaat commented on frontend/src/components/@common/Sensor/index.tsx
> +  fetcher: () => void;
onSense 좋은데요?
callback을 요청드렸던 이유는 넘기는 함수가 반드시 'fetcher' 역할을 할 필요는 없어서였습니다

2023-08-03 04:51 UTC, bassyu commented on frontend/src/components/@common/Sensor/index.tsx
> +  }, []);
옵저버 자체가 지역 변수인지라 없어도 될 것 같은데 맞을까요?
컴포넌트가 unmount 되면 옵저버 자체가 사라질 것 같습니다!

2023-08-03 05:27 UTC, bassyu commented on frontend/src/components/@common/Sensor/index.tsx
> +  }, []);
아 그런데 컴포넌트가 리렌더링 될 때는 계속 생겨나겠네요.. cleanup 하겠습니다~

2023-08-03 06:31 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +    .reverse();
음 확실히 페이지를 데이터로 펴는 작업 역시 필요한 데이터만 선택한다기 보다는 변환한다에 가깝겠네요
아예 유틸로 빼는 것이 맞는 것 같습니다!

2023-08-03 06:52 UTC, hozzijeong commented on frontend/src/components/@common/Sensor/index.tsx
좋습니다 ㅎㅎ

2023-08-03 09:00 UTC, hozzijeong approved these changes
확인 했습니다!! 이쁘게 잘 나오네요 ㅎ

2를 사용한 변수명은 한번 생각 부탁드립니다..ㅎ

2023-08-03 09:08 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/converter.ts
> +  const map2list = <T>(map: Record<string, T>) =>
아 이건 빼먹고 바꿨네요

2023-08-03 11:01 UTC, WaiNaat requested changes
반영해주신 부분들 확인했어요! 로컬에서도 잘 돌아갑니다
코멘트랑 충돌(다행히 별건 없네요) 확인 부탁드려요

2023-08-03 12:49 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/converter.ts
참새의 의견도 맞습니다! 
우선 큰 차이는 없다고 생각해요~

리액트 쿼리는 비동기 데이터와 비동기 요청을 상태와 함수로 추상화하고 편하게 사용하기 위해서 사용한다고 생각해요.
그리고 훅으로 추상화하는 이유는 어떤 비동기요청을 어떤 쿼리훅으로 받아올지를 추상화 하는 것이 핵심이라고 생각해요.
그렇기 때문에 데이터를 어떻게 '가공'할지는 쿼리의 관심사와 분리해도 된다고 생각합니다.

그런데 지금은 그 '가공'이 자료구조가 다르면서 정렬까지 진행하다보니 
쿼리 훅 안에 비동기 통신을 어떻게 추상화하는지 보다는 결과를 어떻게 가공할지 코드가 더 길어졌네요. 
그래서 꼭 select에 들어가지 않더라도 파일 분리를 우선시했어요.

그런데 파일을 분리하고보니 hooks/query 옆에 두기엔 훅이 아니라 일반 함수고, 
utils에 넣기에는 하나의 컴포넌트에서만 사용하는 특수한 함수라 애매했습니다!

2023-08-03 12:50 UTC, bassyu commented on frontend/src/hooks/useIntersectionRef.ts
> +    if (elementRef.current) observerRef.current.observe(elementRef.current);
오 직접 비교까지 👍👍

2023-08-03 13:06 UTC, WaiNaat commented on frontend/src/pages/PetPlantTimeline/converter.ts
`({ data }) => data` 셀렉터를 분리하는 것에 대해서는 어떻게 생각하시나요?

2023-08-03 13:09 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/converter.ts
이걸 모든 쿼리에서 통일할지는 또 애매한 것 같네요..
아니면 지금 파일 분리가 되어있는 상태에서 쿼리에서 import해서 select에 넣는 건 어떤가요?

2023-08-03 13:13 UTC, WaiNaat commented on frontend/src/pages/PetPlantTimeline/converter.ts
통일하지 않는다면 일관성이 너무 없어보여요. 데이터 수집과 가공을 분리하는 기준이 자료구조나 정렬이라면 외부에서 알아내기 힘들다고 생각합니다.. 뭘 하든 하나로 통일하는 개 맞다고 생각해요

제가 첫 질문을 좀 애매하게 적었었네요.. 리액트 쿼리 쪽에서 import해서 쓰지 않고 컴포넌트에서 import한 이유를 여쭤본 거였어요

2023-08-03 13:15 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/converter.ts
아하 그렇군요! 일관성을 위해서 import하는 것으로 바꿀게요!

2023-08-03 13:35 UTC, WaiNaat approved these changes
변경해주신 부분들 확인했어요! 밤늦게까지 제 이상한 요청에 대해 고민해주셔서 감사합니다 쵸파

제가 집이라 로컬에서 잘 되는지는 확인을 못하겠네요ㅠㅠ 고생하셨습니다!

2023-08-03 13:35 UTC, merged