feat: 반려 식물 삭제 기능 구현
woowacourse-teams/2023-pium pull request #231
Opened 2023-08-08 13:26 UTC by Kim0914

# 🔥 연관 이슈

- close #220 

# 🚀 작업 내용

- [x] 반려 식물 삭제 기능 구현
- [x] 삭제되는 반려 식물에 연관된 히스토리 삭제

# 💬 리뷰 중점사항

반려 식물 삭제 기능을 구현했습니다 !

- 수정과 마찬가지로 반려 식물의 주인을 확인하는 로직을 추가했습니다.
- 현재 구현하는 `반려 식물 삭제`는 무덤과는 관계없이 완전히 서비스에서 삭제하므로, `관련 히스토리까지 삭제`하도록 구현했습니다.
- 삭제 기능의 인수 테스트를 명확히 하기 애매했던 것 같아요 🥹 그래서 `등록 -> 삭제 -> 조회 시 없음`의 과정을 인수 테스트로 작성했습니다. 관련해서 의견 남겨주시면 좋을 것 같아요 :)

2023-08-09 10:33 UTC, Choi-JJunho requested changes
전체적으로 구현을 깔끔하게 잘 해주셔서 크게 변경할만한 부분은 없었네요!
다만 반려 식물의 주인을 확인하는 로직에 대해 PetPlant가 가지는 로직으로 통일하면 좋을 것 같다는 생각이 드네요!
해당 내용에 대해 반영 부탁드려용~

2023-08-09 10:33 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        checkOwner(petPlant, member);
### C

현재 PetPlant 도메인 내부에 isNotOwnerOf() 메서드가 존재합니다.
해당 메서드를 사용하는 방법으로 방식을 통일하는건 어떤가요?

2023-08-09 10:33 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
> +
### R

마지막줄 공백 하나는 지워도 될거같네요? ^^

2023-08-09 21:53 UTC, yeonkkk requested changes
안녕하세요 그레이! 조이입니다~
코드를 잘 작성해주셔서 리뷰 사항은 없네요.
코멘트 조금 남겼으니 확인 부탁드려요!
고생하셨습니다🙂

2023-08-09 21:53 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        PetPlant petPlant = petPlantSupport.builder().member(member).build();
### C
빌더 사용 시 한 줄에 점 하나로 정리해봐도 좋을 것 같아요!

2023-08-09 21:53 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        historySupport.builder().petPlant(petPlant).build();
### C

빌더 사용 시 한 줄에 점 하나로 정리해봐도 좋을 것 같아요!

2023-08-10 03:01 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        checkOwner(petPlant, member);
```java
private void checkOwner(PetPlant petPlant, Member member) {
        if (petPlant.isNotOwnerOf(member)) {
            throw new IllegalArgumentException("요청 사용자와 반려 식물의 사용자가 일치하지 않습니다. memberId: " + member.getId());
        }
    }
```

checkOwner 메서드에서 해당 도메인 로직을 호출하고 있습니다..!

제가 코멘트를 잘못 이해했나요..? 🥹

한번 더 확인 부탁드립니다 ~

2023-08-10 03:02 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
> +        void 정상_삭제_후_204를_반환하고_조회할_수_없다() {
좋아요 !

2023-08-10 03:03 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
> +                    .andDo(print());
오.. 감사합니다 ㅎㅎ

2023-08-10 03:03 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/repository/MemberRepositoryTest.java
>          Member save = memberRepository.save(member);
반영했어요!

2023-08-10 03:03 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        checkOwner(petPlant, member);
앗 아래부분을 못봤네요.. 😓
제 불찰입니다 이상 없습니다!

2023-08-10 03:06 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        PetPlant petPlant = petPlantSupport.builder().member(member).build();
프로덕션 코드에서는 빌더 사용 시 한 줄에 점 하나로 구분했었는데, 저희 테스트 코드에서는 빌더를 한 줄에 다 작성하더라구요 !

한번 슥 훑어봤는데, 테스트에서 빌더를 한 줄에 다 작성하고 있는데 몇몇 테스트는 통일되지 않는 부분이 있네요 ㅎㅎ

이 부분은 컨벤션으로 명확히 되면 일괄적으로 수정할게요 !

2023-08-10 03:06 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        historySupport.builder().petPlant(petPlant).build();
위 코멘트와 동일합니다 ~

2023-08-10 03:06 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        historySupport.builder().petPlant(petPlant).build();
저는 변수로 추출하지 않는 단순 생성행위에 대해서는 한줄로 작성해도 괜찮아보여요!

2023-08-10 03:06 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        PetPlant petPlant = petPlantSupport.builder().member(member).build();
> 저는 변수로 추출하지 않는 단순 생성행위에 대해서는 한줄로 작성해도 괜찮아보여요!

ditto

2023-08-10 03:10 UTC, Choi-JJunho approved these changes
깔끔하게 작성해주셔서 머지해도 될 것 같아요~
고생하셨습니다~👍

2023-08-10 03:21 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        PetPlant petPlant = petPlantSupport.builder().member(member).build();
오 그렇군요 두분 의견 감사합니다! 
저도 해당 테스트에서는 딱히 구분하지 않아도 된다고 생각하긴 했는데, 통일성 측면에서 정리하면 좋을 것 같아 말씀드렸어요!
지금까지 작성한 테스트들과 앞으로의 작성할 테스트를 고려하면 저는 한 줄에 점 하나로 구분해도 좋을 것 같습니다 ㅎㅎ
(필드가 많은 객체가 테스트에서 필요한 경우를 생각해볼 수 있겠네요)
하지만 그레이 말대로 컨벤션 영역이라 팀원들 의견에 따르겠습니다~ 🙂

2023-08-10 03:32 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +        PetPlant petPlant = petPlantSupport.builder().member(member).build();
조이가 말한 것 처럼 `필드가 많은 객체가 테스트에서 필요한 경우`는 줄바꿈을 하도록 해야겠네요 !

`필드가 많은 객체가 테스트에서 필요한 경우` -> 다들 알잘딱으로 아실거라고 믿습니다 ㅎㅎ 💚

2023-08-10 04:22 UTC, yeonkkk approved these changes
고생하셨습니다 그레이!
이만 머지하겠습니다~🌱

2023-08-10 04:23 UTC, merged