test: 문서화 추가
woowacourse-teams/2023-pium pull request #237
Opened 2023-08-09 14:52 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #122 

# 🚀 작업 내용

- [x] RestDocs 설정 적용
- 각 API 별 문서화 적용
  - [X] 반려 식물
  - [X] 사전 식물
  - [x] 리마인더
  - [x] 히스토리

## 추가 작업 내용

- 테스트에서 현재 시간을 필요로하지 않는 테스트에 대해 LocalDate.now()를 최대한 이용하지 않도록 수정했습니다.
- Controller 테스트의 정상 동작하는 테스트를 기준으로 문서를 생성헀습니다.
  - 이 과정에서 정상 요청에 대한 테스트명을 `정상_요청시_...`로 통일하는 과정이 있었습니다.

## 참고사항

RestDocs 설정을 적용했습니다.
`src > docs > asciidocs` 경로에 존재하는 `.adoc` 파일이 문서화의 기반이 되는 파일입니다.
<img width="240px" alt="image" src="https://github.com/woowacourse-teams/2023-pium/assets/49794401/2d45d05b-6c16-4291-979f-dd21f868390f">

실행방법 및 적용내용 확인 방법은 다음과 같습니다.
- gradle build 수행
- Application 구동
- localhost:8080/docs/index.html 경로 확인

<img width="1200px" alt="image" src="https://github.com/woowacourse-teams/2023-pium/assets/49794401/5687a98e-a09e-45de-9ce7-1c415e3bb9f6">

# 💬 리뷰 중점사항

누락된 API가 있는지 확인 부탁드립니다.
추가로 테스트가 복잡해지지는 않았는지도 같이 확인 부탁드립니다.

2023-08-10 06:40 UTC, Kim0914 requested changes
안녕하세요 ㅎㅎ 리뷰어 그레이입니다 !

docs 설정 추가해주신다고 고생많으셨어요 😀
개인적으로 추가했으면 하는 내용을 코멘트로 달았어요 !

추가적으로 pathParameters를 추가하게 된다면 
`MockMvcRequestBuilders`의 `get, post, delete...`대신 
`RestDocumentationRequestBuilders`의 `get, post, delete..`를 사용해야 합니다 😂

컨트롤러 테스트와 docs 테스트가 한번에 작성될 때의 단점이라고 할 수 있겠네요 ㅜㅜ

스프링 공식문서에서 `RestDocumentationRequestBuilders`가 `MockMvcRequestBuilders`를 확장한 클래스라고 하기 때문에 사용하는데는 큰 문제가 없을 것 같아요 😎

2023-08-10 06:40 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +                            preprocessRequest(prettyPrint()),
### C

RequestParam이 있는 API인 경우 param에 대한 정보를 제공하는건 어떨까요?
```java
this.mockMvc.perform(get("/dictionary-plants?name=스투")) 
		.andExpect(status().isOk()).andDo(document("dictionaryPlant", queryParameters(
				parameterWithName("name").description("사전 식물 검색 파라미터")
		)));
```
대충 작성한 예시 코드입니다 😉

위와 같이 사용할 수 있는데요, parameterWithName("name")에 들어가는 "name"과 실제 API 쿼리 파라미터 key값 "name" 이 다른 경우 테스트가 실패해서 신뢰성도 가져갈 수 있습니다 !

queryParameters는 snippet을 직접 반환하기 때문에 현재 document의 3번째 파라미터부터 추가할 수 있겠네용

또한 queryParameter에 대한 snippet이 생성되기 때문에 asciidoc의 adoc에 추가할 수 있습니다.

![image](https://github.com/woowacourse-teams/2023-pium/assets/68818952/ac627d62-fe16-4fe0-bf3b-b2013e127484)
현재는 관련 정보가 없는 것 같아요 !

Rest Docs가 테스트 코드를 기반으로한 신뢰성 있는 docs인 만큼 추가해주면 좋을 것 같네요 😀

+)
![image](https://github.com/woowacourse-teams/2023-pium/assets/68818952/8d5601aa-a8f4-4ce5-b617-b4852d1113c7)

추가하면 위와 같이 표시할 수 있습니다 !

2023-08-10 06:40 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +                            preprocessResponse(prettyPrint()))
### C
페이지와 관련된 파라미터들도 docs에 추가할 수 있을 것 같아요 !

2023-08-10 06:40 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +                    )
### C
```suggestion
                    .andDo(document("dictionaryPlant/findById/",
                            preprocessRequest(prettyPrint()),
                            preprocessResponse(prettyPrint()),
                            pathParameters(
                                    parameterWithName("dictionaryPlantId").description("사전 식물 ID")
                            ))
                    )
```

![image](https://github.com/woowacourse-teams/2023-pium/assets/68818952/458b8e31-e771-42e4-80d7-595835d66106)
PathParameter에 대한 정보가 필요하지 않을까요? 🤓
현재 나와있는 정보로도 유추할 수는 있지만, 좀 더 명확해지면 좋을 것 같아요 !

![image](https://github.com/woowacourse-teams/2023-pium/assets/68818952/1a703f3c-83f7-4c4e-8ff2-ee6e1d08773b)

추가하면 다음과 같이 확인할 수 있습니다 !

2023-08-10 06:40 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
> +                            preprocessResponse(prettyPrint()))
### C

여기도 requestFields에 대한 docs 내용이 추가될 수 있겠네요 !

토큰 값을 필수로 담아야하는 API는 requestHeader에 대한 docs도 추가될 수 있겠네요 !

2023-08-10 06:40 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/PetPlantControllerTest.java
> +                            preprocessResponse(prettyPrint()))
### C

여기도 !

2023-08-10 06:55 UTC, Kim0914 commented
+++ 추가

생각해보니.. docs 작성에 시간이 꽤 들 수도 있을 것 같은데 ㅎㅎ
지금 docs 형태도 부족하지는 않아서, 우선 진행하고 4차 스프린트 기능 구현을 완료한 다음에 보충해도 될 것 같아요 😁

2023-08-10 07:13 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +                            preprocessRequest(prettyPrint()),
파라미터 설명 좋네요! 반영하겠습니다.

2023-08-10 09:59 UTC, rawfishthelgh requested changes
주노! 빠르게 문서화 진행해주셔서 고맙습니다ㅎㅎ
의견 교환이 필요한 지점이 두 곳 있어서 코멘트 남겼습니다.
읽어보시고 의견 재교환 or 반영해주면 좋을 것 같아요!

2023-08-10 09:59 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +        void ID값을_0이하의_값으로_조회하면_400을_반환() throws Exception {
### **A**
궁금한 점인데, 정상적이지 않은 요청에 대한 API명세(오류 명세)도 restdocs를 통해 드러낼 수 있나요?

만약 가능하다면 잘못된 요청에 대한 명세 또한 api이므로 드러나야 한다고 생각합니다!

2023-08-10 09:59 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +        void 이름이_비어있으면_400을_반환() throws Exception {
> 궁금한 점인데, 정상적이지 않은 요청에 대한 API명세(오류 명세)도 restdocs를 통해 드러낼 수 있나요?

ditto

2023-08-10 09:59 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +        void 정상_요청시_200을_반환한다() throws Exception {
### **C**
조금 고민되는 지점인데, 저희가 현재 HistoryController 에서는 
`@PageableDefault` 어노테이션을 활용해 
`@PageableDefault(size = 20, sort = "date", direction = DESC)`
과 같은 방식으로 기본 사이즈와 정렬방식을 명시하고 있습니다.
여기서 요청을 보낼 때 size, page, direction 정보를 클라이언트에서 자유롭게 질의할 수 있죠.

하지만 현재 api 명세에는
<img width="503" alt="스크린샷 2023-08-10 오후 6 50 52" src="https://github.com/woowacourse-teams/2023-pium/assets/79038908/94a23f4b-a5ab-4f8c-876f-e8db7e56f30f">
위와 같은 방식으로 page, size 정보만 드러나고, sort 방식에 대한 정보는 드러나지 않고 있는데요.
1. size와 sort는 디폴트가 지정되어 있으므로 page만 api 명세에 드러나도록 테스트를 작성한다.
2. 디폴트가 지정된 파라미터라도 api명세에 모두 드러나도록 테스트를 작성한다.
3. 현재처럼 page, size 정보만 제공한다

셋 중에 어떤 방식으로 진행하면 좋을지 주노의 의견 궁금합니다!! 저는 개인적으로 디폴트가 들어간 쿼리 파라미터라도 명세에 제공하는게 더 정확하고 유연하지 않을까 싶네요.

2023-08-10 10:14 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +        void 이름이_비어있으면_400을_반환() throws Exception {
> 오류 명세에 대해서도 문서화가 진행되면 꼼꼼한 문서가 될 것 같지만 모든 검증 조건에 대한 케이스가 문서화로 나타나면 복잡해질 것 같아요!
해당 부분은 에러메시지로 충분히 전달한다고 생각하여 문서화를 진행하지 않아도 된다고 생각합니다.

ditto

2023-08-10 10:38 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/controller/HistoryControllerTest.java
> +        void 정상_요청시_200을_반환한다() throws Exception {
2번이 적절한것 같네요~
Pageable의 옵션을 명세에 같이 적는 방향으로 적용해보곘습니다

2023-08-10 16:51 UTC, rawfishthelgh approved these changes
반영 내용 확인 완료했습니다! 
Approve 하겠습니다

2023-08-11 03:52 UTC, Kim0914 approved these changes
안녕하세요, 리뷰어 그레이입니다.

확인했어용 ㅎㅎ
고생했습니다 !

2023-08-11 03:53 UTC, merged