feat: 반려 식물 수정 시 히스토리 추가
woowacourse-teams/2023-pium pull request #257
Opened 2023-08-12 06:18 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #251 

# 🚀 작업 내용

- [x] 반려 식물 수정 시 히스토리 생성 (location, flowerpot, light, wind, waterCycle)
- 반려 식물 마지막으로 물 준 날 수정 시 히스토리 수정
  - [x] 가장 최근의  마지막으로 물 준 날 히스토리의 currentDate를 업데이트 한 값으로 수정한다.

# 💬 리뷰 중점사항

다음 작업 내용과 이어지는 작업입니다.
- #256 

이벤트의 관심사가 적절하게 분리되었는지 확인 부탁드립니다.

2023-08-12 11:37 UTC, rawfishthelgh requested changes
주노! 어려운 도메인 로직이었는데 잘 개발해줘서 고맙습니다ㅎㅎ
두 가지 정도 궁금한 부분 있어서 코멘트 남겼어요! 이 부분만 해소되면 approve 하면 될 것 같습니다 👍

2023-08-12 11:37 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +
### **C**
공백이 두줄 있네요!

2023-08-13 06:44 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +    private static final PageRequest TOP_ORDER_BY_DATE_DESC = PageRequest.of(0, 1, Sort.Direction.DESC, "date");
재사용 가능성을 염두에 두고 전역화했는데 불필요한 Heap 메모리 사용이 될 수도 있을 것 같네요!
지역변수로 관리하는 방향으로 반영하겠습니다

2023-08-13 06:46 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +        if (historyAboutLastWaterDate.getSize() == JUST_ONE) {
Repository상으로 `TOP_ORDER_BY_DATE_DESC`로 하나의 값만 가져옵니다.

하지만 이 때 반환되는 값은 History 엔티티 단건에 대한 정보가 아닌 Page<>로 감싸진 객체가 반환됩니다.

이에 Page 객체 내부에 원소가 단 하나라는 보장이 없을 수도 있기 때문에 `historyAboutLastWaterDate.getSize() == JUST_ONE` 검증을 추가했습니다.

하마드가 말씀하신 것 처럼 한개가 아닌 경우에 대해서 Exception 처리를 수행하는 것이 더 올바를 방향이라는 생각이 드네요!

올바르지 않은 결과값에 대해 예외처리를 하는 방향으로 반영하겠습니다.

2023-08-13 08:04 UTC, rawfishthelgh approved these changes
주노 리뷰 반영 감사합니다~ㅎㅎ
approve 할게요

2023-08-13 15:58 UTC, Kim0914 requested changes
주노 ~~ 주말인데도 열일하시는군요 ㅎㅎ

너무 고생많았습니다 !
개인적으로 궁금한 내용들과, 생각해 볼만한 내용들 코멘트로 남겼어요 💚

2023-08-13 15:58 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/History.java
> +        }
### A

지난번에 하마드가 `Objects.isNull()`에 대한 코멘트를 달아줬었는데요..!!

이 부분 확인하고 컨벤션을 맞춰보면 좋겠네요 ㅎㅎ

- https://github.com/woowacourse-teams/2023-pium/pull/139#discussion_r1275656106

2023-08-13 15:58 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEvent.java
>      private final String current;
### A

`@NotBlank`가 아닌 `@NotNull`인 이유가 의도한 것인지 궁금합니다 !

2023-08-13 15:58 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/event/history/PetPlantHistory.java
> +
여기 if 문들은 어쩔 수 없어보이네요 🤣🤣

나~아~중에 더 고민해봅시다 ㅎㅎ

2023-08-13 15:58 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +        final PageRequest TOP_ORDER_BY_DATE_DESC = PageRequest.of(0, 1, Sort.Direction.DESC, "date");
### R

`final` 키워드를 명시해줄 이유가 없으면 삭제해도 좋을 것 같아요 !

2023-08-13 15:58 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +            throw new IllegalArgumentException("최근 물주기 정보는 하나의 값만 존재해야합니다. size: " + historyAboutLastWaterDate.getSize());
### C

클라이언트에게 받은 요청이 아닌, 서버에서 만든 질의(페이징)으로 조회한 후 결과가 잘못 나왔을 때 `IllegalArgumentException` 예외 보다는 서버 내부에서 발생한 예외 등으로 사용하는 것이 더 적절하지 않을까요?!

서버에서도 디비로 부터 예상치 못한 응답을 받았기 때문입니다 ! (디비 내부에서 문제가 생겼을 확률이 높음)

2023-08-13 15:58 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +    private static void validateContentSize(Page<History> historyAboutLastWaterDate) {
### R

`static`으로 사용하신 이유가 있나요 ?!

2023-08-13 15:58 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +    public void updateLastWaterDateHistory(LastWaterDateEvent lastWaterDateEvent) {
개인적으로 궁금한 부분입니다 !

이벤트 리스너에서 파라미터 타입에 해당하는 메서드를 만들어 놓으면, publisher의 publishEvent가 알아서 호출하는 이벤트를 찾아주는건가요?! 🤓

리스너의 코드를 보면 `savePetPlantHistory`, `updateLastWaterDateHistory`가 따로 호출되는 부분은 안보이는 것 같고... 파라미터 타입으로만 구분되나? 싶어서요 ㅎㅎ

2023-08-13 15:58 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/domain/HistoryTest.java
> +        SoftAssertions.assertSoftly(softly -> {
### C

static import 해줄 수 있겠네요 ㅎㅎ

2023-08-13 16:11 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/domain/History.java
> +        }
내부값 접근 시 NPE를 고려했으나 위에서 접근하는 값에 대해서 null check를 해주고있으니 == 을 사용해도 되겠군요! 반영하겠습니다~

2023-08-13 16:13 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEvent.java
>      private final String current;
EventListener의 로직을 구성하던 중에 nullCheck 로직이 Event 객체 내부에서 일어나면 좋겠다는 생각에 NotNull을 붙였는데 생각해보니 NotBlank가 더 구체적인 검증이 될 수 있겠네요!

NotBlank를 사용하는 방향으로 리팩터링 진행하겠습니다~

2023-08-13 16:16 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +            throw new IllegalArgumentException("최근 물주기 정보는 하나의 값만 존재해야합니다. size: " + historyAboutLastWaterDate.getSize());
확실히 데이터 저장 상태에 이상이 있는 경우가 대표적이겠네요!
현재 핸들링 대상으로 잡지 않은 `IllegalStateException`으로 수정하겠습니다.

2023-08-13 16:18 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +        final PageRequest TOP_ORDER_BY_DATE_DESC = PageRequest.of(0, 1, Sort.Direction.DESC, "date");
지역적으로 상수를 선언한 내용으로 재할당을 막아야한다고 생각하기 때문에 final을 붙였습니다

2023-08-13 16:19 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +    private static void validateContentSize(Page<History> historyAboutLastWaterDate) {
인텔리제이 설정이... 😅 수정하겠습니다~

2023-08-13 16:20 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/history/HistoryEventListener.java
> +    public void updateLastWaterDateHistory(LastWaterDateEvent lastWaterDateEvent) {
넵~ 파라미터 타입으로 구분됩니다!
Event publish 시점에서 Spring Context 상에 이벤트를 발생시키고 해당하는 이벤트를 파라미터로 가진 Listener가 이벤트를 받아오는 흐름으로 이벤트가 구성됩니다

2023-08-14 03:35 UTC, Kim0914 approved these changes
리뷰 남기고 잠들었는데 그 짧은 사이에 반영해주셨군요?!

멋있습니다 🫢

리뷰 반영된거 확인했어요 !
고생많았습니다 :)

2023-08-14 03:35 UTC, merged