feat: 타임라인 페이지 고도화
woowacourse-teams/2023-pium pull request #258
Opened 2023-08-12 09:21 UTC by bassyu

# 🔥 연관 이슈

- close #228

# 🚀 작업 내용

스크린샷은 모의 데이터라 뷰 위주로 봐주세요..

![타임라인 고도화](https://github.com/woowacourse-teams/2023-pium/assets/54442420/a6b95dcf-ba47-4bec-b9b9-74090989dfaf)

- 아래의 정보를 추가적으로 보여줍니다.
  - 년도
  - 몇일만에 물을 줬는지
  - 물주기를 어떻게 변경했는지
  - 환경을 어떻게 변경했는지

- 필터링 기능을 추가했습니다.
- 스켈레톤을 추가했어요. 

# 💬 리뷰 중점사항

같은 페이지어도 필터를 바꾸면 서스펜스 페이지를 보여주니 깜빡이는 느낌이 있었어요. 그래서 스켈레톤을 추가해봤습니다!

2023-08-12 11:59 UTC, hozzijeong requested changes
세상에... 훨씬 나아졌습니다. 고생하셨어요 쵸파!! 

다만, 필터링이 제대로 되지 않는 버그가 있는것 같아서 한번 수정 부탁드려요! 추가로 슬랙에서 말한것 처럼 전체 보기 필터도 있으면 더 좋을것 같습니다!

코멘트 확인 부탁드려요!! 고생하셨습니다!

2023-08-12 11:59 UTC, hozzijeong commented on frontend/src/components/@common/CheckButton/index.tsx
### C

아예 컴포넌트를 새로 만드셨군요 ㅋㅋㅋㅋㅋ 멋있습니다. 스토리북도 추가하면 더 좋을것 같아요!

2023-08-12 11:59 UTC, hozzijeong commented on frontend/src/hooks/useSwitch.ts
### C

훅 이름이 `Switch`니까 처음에 보다가 `switch`문인가? 라는 생각이 먼저 들었습니다. 훅 이름은 `useShow`나  `useToggle`은 어떤가요?

2023-08-12 11:59 UTC, hozzijeong commented on frontend/src/components/petPlant/Timeline/index.tsx
> +      {(isLoading || isFetchingNextPage) && (
### R

해당 기능은 `Suspense`로 사용 못하나요?? 사용이 가능하다면 `Suspense`로 사용하는게 어떤가요

2023-08-12 11:59 UTC, hozzijeong commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +  const onClickWaterCycle = () => {
### R

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/7af5a892-3c10-4da3-b437-1a5316f4ca77)
쵸우파... 필터가 제대로 먹지 않습니다... 사실상 물주기 설정이 체크된다면 필터에 waterCycle만 있어야 하는데 그렇게 되지 않고 있어요... 다른 필터도 모두 마찬가지입니다. 아마 toggle의 상태가 바로 업데이트 되지 않아서 조건문이 제대로 작동하지 않는것 같은데 한번 확인해주세요!

2023-08-12 11:59 UTC, hozzijeong commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +
### C

`[flowerpot, light, location]`을 `setting`이라는 변수로 따로 선언하는건 어떤가요? 다른데서도 사용을 많이 하고 있는것 같아서 재사용 성이 좋을것 같습니다

2023-08-12 11:59 UTC, hozzijeong commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +  if (!petPlantId) return null;
### C

나중에 `petPlantId`가 없는 경우에 에러 바운더리에 잡힐 수 있게 에러를 던지는것은 어떤가요?

2023-08-12 11:59 UTC, hozzijeong commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +const ButtonLabel = styled.span`
### R

`style`파일로 분리해주세요!

2023-08-12 11:59 UTC, hozzijeong commented on frontend/src/components/petPlant/TimelineItemList/index.tsx
> +  const TYPE_MESSAGE_MAP = {
### C 

해당 변수는 컴포넌트 외부로 빼는게 어떤가요?!?!

2023-08-12 11:59 UTC, hozzijeong commented on frontend/src/components/petPlant/Timeline/converter.ts
> +  const convertMapToList = <T>(map: Record<string, T>) =>
### R

변환 함수가 함수 속에 있는 이유가 있을까요? 특별한 이유가 없다면 분리하는게 좋을것 같습니다.

2023-08-12 13:38 UTC, WaiNaat requested changes
제가 머릿속에서 그렸던 것보다 훨씬 더 이뻐요 👍 고생하셨습니다 쵸파

디자인 관련해서 개인적인 의견은 맨 처음에 물 주기 등록했을 때 숫자 하나만 덩그러니 있는 게 못생겨서 '3일' 이런 식이면 더 좋겠다는 생각이 듭니다
슬랙에는 전체 필터도 있으면 좋겠다고 말씀을 드렸었는데 또 디자인을 보니까 없어도 좋아보여요

확실히 타임라인에는 서스펜스보다는 스켈레톤이 더 어울리는 것 같아요

가장 큰 문제는 intersection observer가 아닐까 합니다 😭

2023-08-12 13:38 UTC, WaiNaat commented on frontend/src/hooks/queries/history/useYearList.ts
>      },
### R
히스토리를 실시간으로 바꾸진 않으니 `refetchOnWindowFocus = false`를 해도 좋을 것 같아요

### C
필터 변경 시 깜빡임 같은 경우에는 `placeholderData: keepPreviousData` 설정을 하면 아예 없앨 순 있어요 물론 이 친구도 장단점이 있긴 합니다

2023-08-12 13:38 UTC, WaiNaat commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +          <Water fill={isCheckedWater ? 'white' : theme.color.water} />
### R

svg는 단순 꾸미기용이니 `aria-hidden`으로 부탁드려용

2023-08-12 13:38 UTC, WaiNaat commented on frontend/src/apis/history.ts
> +  let url = `${HISTORY}?petPlantId=${petPlantId}&page=${page}&size=${size}`;
### C

`let`을 안 쓰는 운동을 어떻게 생각하시는지 궁금해요
저는 솔직히 피할 수 있으면 피하지만 백준풀면서 let을 많이써서 let 사용에 대한 큰 거부감은 없거든요

2023-08-12 13:38 UTC, WaiNaat commented on frontend/src/components/@common/CheckButton/CheckButton.style.ts
> +export const CheckboxLabel = styled.label`
### C

개인적으로는 `cursor: pointer`가 있으면 좋겠어요

2023-08-12 13:38 UTC, WaiNaat commented on frontend/src/components/petPlant/Timeline/converter.ts
> +export type YearList = [string, MonthList][];
### C

year month day 타입을 쓰면 보기엔 더 좋을 것 같은데 로컬에서 이렇게 바꿔보니까 아래쪽에서 대참사가 일어나네요ㅠㅠ
```suggestion
type DayMap = Record<Day, TimelineItem[]>;
type MonthMap = Record<Month, DayMap>;
type YearMap = Record<Year, MonthMap>;

type DayList = Array<[Day, TimelineItem[]]>;
type MonthList = Array<[Month, DayList]>;
export type YearList = Array<[Year, MonthList]>;
```

2023-08-12 14:15 UTC, bassyu commented on frontend/src/components/@common/CheckButton/index.tsx
좋아요! 추가하겠습니다~

2023-08-12 14:18 UTC, bassyu commented on frontend/src/hooks/useSwitch.ts
이게 원래 useBoolean 인데 useModal이 되었다가 무거워져서 다시 useSwitch로 추출되었습니다!
show 뿐만 아니라 체크박스 상태로도 쓰이기도 하고 토글 뿐만 아니라 on, off도 있어서 이렇게 네이밍했어요!

2023-08-12 14:21 UTC, bassyu commented on frontend/src/components/petPlant/Timeline/index.tsx
> +      {(isLoading || isFetchingNextPage) && (
음 제가 잘 이해를 못했는데 suspense로 현재 동작처럼 할 수 있나요?

2023-08-12 14:23 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +  const onClickWaterCycle = () => {
코드부터가 상당히 무결하지 않긴 합니다...
이 부분은 동시에 동작하도록 다시 리팩터링 하겠습니다!

2023-08-12 14:24 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +  if (!petPlantId) return null;
오 좋은 방법이네요!!

2023-08-12 14:27 UTC, bassyu commented on frontend/src/hooks/queries/history/useYearList.ts
>      },
- 아 어쩐지 윈도우 다녀오면 다시 불러오던데 그 이유였군요!! 좋아요 👍
- 이 옵션도 상당히 매력적이네요! 어떤 장단점이 있을까요?? 적용해보면서 공부해도록 하겠습니다~

2023-08-12 14:29 UTC, bassyu commented on frontend/src/components/petPlant/Timeline/converter.ts
> +export type YearList = [string, MonthList][];
한번 적용해서 해결해 보겠습니다! 설레네요

2023-08-12 14:32 UTC, bassyu commented on frontend/src/hooks/useSwitch.ts
> +  }, [isOn]);
생각해보니 콜백함수가 이런 역할도 있네요!
좋은 방법인 것 같습니다!

2023-08-12 14:39 UTC, bassyu commented on frontend/src/components/petPlant/TimelineItemList/index.tsx
> +        switch (type) {
가독성이 더 좋다고 생각했어요~ 가독성이 상당히 주관적인 것이긴 하죠..
switch는 type을 딱 대표로 새우고, 이 type에 의존해서 반환하리라는 것을 알리는 느낌이었습니다.

2023-08-12 14:42 UTC, bassyu commented on frontend/src/components/petPlant/Timeline/index.tsx
> +  const intersectionRef = useIntersectionRef<HTMLDivElement>(fetchNextPage);
센서가 안보였다가 보여야 트리거가 되는데, 화면이 길면 안보이게 될 수가 없더라구요
화면 높이에 맞춰서 센서를 내려보겠습니다!

2023-08-12 14:43 UTC, bassyu commented on frontend/src/components/petPlant/Timeline/Timeline.style.ts
> +  z-index: ${(props) => props.theme.zIndex.sticky + 3};
처음에 연 월 일이 다 겹쳐졌을 때 만들었다가 미처 지우지 못했네요! 이 친구만 + 1 해두겠습니다~

2023-08-12 14:46 UTC, hozzijeong commented on frontend/src/components/petPlant/Timeline/converter.ts
> +export type YearList = [string, MonthList][];
아마 Object에서 받는 key값이 string을 반환하기 때문에 터지는 것으로 생각돼요! 예전에 어떤 블로그에서 해결하는 방법을 봤었는데 개별 Modlue을 따로 만들어서 object의 key에도 Month,Year,Day등의 타입을 받을 수 있도록 설정하더라구요..? (찾아봤는데 안찾아지네요....) 그래서 너무 무리다 싶으면 저는 고도화 할 때 해도 될 것 같습니다..ㅎ

2023-08-12 14:52 UTC, bassyu commented on frontend/src/apis/history.ts
> +  let url = `${HISTORY}?petPlantId=${petPlantId}&page=${page}&size=${size}`;
사실 저도 큰 거부감은 없습니다!
최대한 안쓰는 것이 좋긴 하겠지만 적절하게 사용할만한 곳에서는 쓸 수 있다고 생각해요.

2023-08-12 15:17 UTC, hozzijeong commented on frontend/src/components/petPlant/Timeline/index.tsx
> +      {(isLoading || isFetchingNextPage) && (
https://github.com/woowacourse-teams/2023-pium/assets/50974359/ab1e4ee7-13de-41bb-ac3b-b406aa85b9c2

되는것 같아요! Suspense로 감쌌습니다! 추가적으로 스켈레톤 이미지도 컴포넌트로 따로 분리하면 좋을것 같아요! (안에 있는 `DayArea`역시 불필요한 fragment로 감싸져 있는것 같습니다!)

2023-08-13 02:23 UTC, hozzijeong commented on frontend/src/hooks/useSwitch.ts
체크박스의 상태라면 뭔가 toggle이 더 낫거나 좀더 디테일한 이름이면 좋을것 같아요! (showSwitch or toggleSwitch 같은...?)

2023-08-13 04:15 UTC, WaiNaat commented on frontend/src/hooks/queries/history/useYearList.ts
>      },
제가 생각하는 장점은 안 깜빡이는 거고, 단점은 인터넷이 느린 환경에서는 필터는 체크가 되어있는데 화면은 오랜 시간 동안 바뀌지 않아서 사용자가 엥?? 할 수 있다는 거에요

2023-08-13 04:15 UTC, WaiNaat commented on frontend/src/components/petPlant/Timeline/converter.ts
> +export type YearList = [string, MonthList][];
아하 생각보다 복잡하네요ㅠㅠ

2023-08-13 05:09 UTC, bassyu commented on frontend/src/hooks/useSwitch.ts
toggle도 좋네요! useToggle로 바꿔보겠습니다~

2023-08-13 06:22 UTC, bassyu commented on frontend/src/components/petPlant/Timeline/converter.ts
> +  const convertMapToList = <T>(map: Record<string, T>) =>
convertMapToList 는 convertYearMapToYearList 에서만 쓰이는 함수라는 것을 표현하고 싶었습니다!
분리해도 무방할 것 같네요~

2023-08-13 06:43 UTC, bassyu commented on frontend/src/hooks/queries/history/useYearList.ts
>      },
아 그정도 차이가 있었군요!! 개인적으로 바뀌는 시간동안 바뀌는 중이라는 것을 표현해도 좋을 것 같아요~

2023-08-13 07:43 UTC, bassyu commented on frontend/src/hooks/useSwitch.ts
> +  }, [isOn]);
대신에 한번의 렌더링 과정에서 이 함수가 여러번 호출된다면 여러번 바뀔 수도 있겠네요! 이 점은 유의해야겠습니다.

2023-08-13 08:21 UTC, bassyu commented on frontend/src/types/history.ts
> +  data: HistoryItem[];
적용해봤는데 나름 괜찮네요!

2023-08-13 08:37 UTC, bassyu commented on frontend/src/components/petPlant/Timeline/index.tsx
> +      {(isLoading || isFetchingNextPage) && (
아 제가 가운데 식물은 남아 있었으면 해서 이렇게 만들었습니다...

2023-08-13 11:26 UTC, WaiNaat requested changes
바뀐 부분들 확인했어요 👍 
intersection observer도 이젠 잘 작동합니다. 악질적으로 브라우저 확대를 25%로 해도 위아애로 스크롤 좀 비벼주니까 다음 걸 잘 가져오네요ㅎㅎ

2023-08-13 11:26 UTC, WaiNaat commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +  }, [isCheckedWater, isCheckedWaterCycle, isCheckedSetting]);
### R

[불필요한 이펙트](https://react.dev/learn/you-might-not-need-an-effect#updating-state-based-on-props-or-state)에요!!

이펙트에서 setFilter를 하기 때문에 필터를 클릭하면
**isChecked가 바뀌어서 렌더링 -> 이펙트 발생 -> filter가 바뀌어서 렌더링**
으로 인해 불필요한 렌더링이 생기고 있어요

이전과 같은 세 개의 이벤트 핸들러가 있는 모습이 더 낫다고 생각합니다.
아니면 `const { toggledItems, toggleItem } = useToggleMap(items)` 같은 훅으로 분리해서 써도 깔끔해질 것 같아요

2023-08-13 11:26 UTC, WaiNaat commented on frontend/src/types/history.ts
> +  'lastWaterDate' | 'waterCycle' | 'flowerpot' | 'light' | 'location'
### R

여기에 `wind`가 빠진거같아요!!

2023-08-13 12:11 UTC, bassyu commented on frontend/src/types/history.ts
> +  'lastWaterDate' | 'waterCycle' | 'flowerpot' | 'light' | 'location'
헉..!! 정말 큰일날 뻔했네요 🙇

2023-08-14 02:28 UTC, hozzijeong requested changes
변경 사항 확인했습니다! 

바뀌었음에도 필터링이 제대로 먹지 않는것 같아서 원인을 찾아봤는데, handler에서 filter를 받고 따로 처리하지 않는것 같더라구요! 한번 handler에서 filter에 따른 데이터 필터링 구현 해주시면 좋을 것 같아요!

2023-08-14 02:30 UTC, bassyu commented on frontend/src/pages/PetPlantTimeline/index.tsx
> +  }, [isCheckedWater, isCheckedWaterCycle, isCheckedSetting]);
2번 렌더링 하긴 합니다..! 다시 확인해보니 이전 코드도 필터링이 잘 먹기는 해서 롤백하겠습니다!
아마 필터링은 되는데 모의 데이터가 안 바뀌어서 헷갈린 것 같아요.

2023-08-14 08:46 UTC, hozzijeong approved these changes
확인했습니다 쵸파~ 고생하셨어요!! 멋져요 👍

2023-08-14 09:48 UTC, WaiNaat approved these changes
멋있어요

2023-08-14 09:48 UTC, merged