refacrtor: 반려 식물 수정 페이지 리팩터링, Select 접근성 개선
woowacourse-teams/2023-pium pull request #260
Opened 2023-08-12 11:45 UTC by WaiNaat

# 🔥 연관 이슈

- close #255 

# 🚀 작업 내용

### 반려 식물 수정 페이지 관련

- #214 의 논의대로 `secondLastWaterDate` 를 받아 마지막 물 준 날 변경에 대한 검증을 추가했어요
- 만약 이 값이 `null`이면 `lastWaterDate`부터 365일 이전의 날짜 중에서만 선택할 수 있게 정했어요
- '정보 수정하기' 버튼의 크기를 늘렸어요 (모바일에서 보면 진짜 작게 보이더라구요)
- 실시간으로 다음 물 줄 날과 함께한 날을 변경합니다.
- '취소하기' 버튼을 이용해 양식 입력을 취소할 수 있어요
- 기존 정보와 비교했을 때 달라진 점이 없다면 양식 제출이 비활성화됩니다

### 달력

- 기존: 무조건 "오늘"에만 붉은 강조 표시가 되어 있어서 선택한 날과 오늘이 다를 경우 쉽게 인지하기 힘들었어요
- 변경: 오늘은 테두리로, 선택한 날은 붉은 배경에 흰 글씨로 바꿨어요.
![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/ee7b00c0-749c-433a-aa5e-c4224cab1649)

### Select

- 일단 키보드로 사용할 수 있게끔 고쳤습니다
    - esc로 닫기
    - 탭 키로 접근 가능
    - 엔터, 스페이스 바로 입력 가능

### 버그 수정

`getDaysBetween`이 "두 날짜 사이의 간격"이 아니라 "디데이"를 계산하고 있어서 그 부분을 고쳤어요
- 입력한 두 날짜: 2023년 8월 12일, 2023년 8월 12일
- 기존: `1` 반환
- 변경: `0` 반환

# 💬 리뷰 중점사항

1. 취소 시에도 토스트를 보여주는 게 좋을까요?
2. 달력에서 혹시 '오늘'을 표현할 수 있는 더 좋은 방안 있으면 알려주세요!!

2023-08-12 15:09 UTC, hozzijeong requested changes
고생하셨습니다 참새 멋져요!

mock데이터가 값이 너무 고정되어 있어서 처음에 의아했네요 ㅋㅋㅋㅋ 그래도 값은 잘 바뀌는거 확인했습니다!

2023-08-12 15:09 UTC, hozzijeong commented on frontend/src/components/@common/Select/index.tsx
> +                onKeyDown={({ key }: React.KeyboardEvent<HTMLLIElement>) => {
### C

메서드를 분리하는게 어떤가요?

2023-08-13 04:20 UTC, WaiNaat commented on frontend/src/utils/date.ts
> +  first.setHours(0);
찾아보니까 `first.setHours(0, 0, 0, 0);`으로 한번에 초기화가 돼서 그렇게 바꾸면 분리할 필요는 없다는 생각이 들어요 이래서 공식문서를 읽어야 하나 봅니다..

2023-08-13 04:53 UTC, WaiNaat commented on frontend/src/components/@common/Select/index.tsx
> +                onKeyDown={({ key }: React.KeyboardEvent<HTMLLIElement>) => {
함수가 map에서 나오는 option에 귀속되어야 해서 완전히 밖으로 빼지는 못하고 map 안에서 만들어서 쓰도록 고쳤습니다

2023-08-13 09:12 UTC, bassyu approved these changes
사용성에서 퀄리티가 확 올라간게 느껴지네요!! 좋습니다.. 👍👍

> 1. 취소 시에도 토스트를 보여주는 게 좋을까요?

지금도 괜찮은 것 같아요!

> 2. 달력에서 혹시 '오늘'을 표현할 수 있는 더 좋은 방안 있으면 알려주세요!!

지금 딱히 떠오르는 게 없네요! 충분한 것 같아요~

2023-08-13 15:29 UTC, hozzijeong approved these changes
변경사항 확인했습니다! 고생하셨어요 참새

2023-08-13 15:29 UTC, hozzijeong commented on frontend/src/utils/date.ts
멋져요

2023-08-13 15:29 UTC, hozzijeong commented on frontend/src/components/@common/Select/index.tsx
> +              const selectOnEnterOrSpace = ({ key }: React.KeyboardEvent<HTMLLIElement>) => {
좋아요 좋아요

2023-08-13 15:29 UTC, merged