feat: 로그인 기능을 구현한다.
woowacourse-teams/2023-pium pull request #272
Opened 2023-08-14 07:27 UTC by hozzijeong

# 🔥 연관 이슈

- close #224 

# 🚀 작업 내용
- [x] 카카오 로그인 기능 구현
- [x] 쿠키 검증을 통해 호출되는 API 설정
- [ ] 로그 아웃 기능 구현
- [ ] 회원 탈퇴 기능 구현
- [ ] 자기 검증 기능 구현

# 💬 리뷰 중점사항

https://github.com/woowacourse-teams/2023-pium/assets/50974359/98ba8c62-46f7-4a20-8050-01b869d9a6f7

카카오 로그인과 API 요청시에 쿠키가 없는 경우 401을 반환하도록 했습니다. 로그아웃, 회원 탈퇴, 자기 검증(`member/me`)와 관련된 API는 아직 명세가 뚜렷하게 나오지 않아서 API를 생성만 해놓고 아직 msw로 붙이거나 하지는 않았습니다.

너무 늦어질것 같아서 일단은 현재까지 구현한 사항들은 먼저 올리고 추가로 명세가 확실해 진다면 나머지를 구현하겠습니다!

2023-08-14 11:36 UTC, bassyu requested changes
수고하셨어요 클린!!
OAuth 관련해서 자세한 내용을 몰라 리뷰 못드려서 아쉽네요..

2023-08-14 11:36 UTC, bassyu commented on frontend/src/apis/auth.ts
> +const Auth = {
### R

저번에 URL 네이밍이랑 겹쳤어서 API 붙이는 게 좋을 것 같습니다!
```suggestion
const AuthAPI = {
```

2023-08-14 11:36 UTC, bassyu commented on frontend/src/hooks/useAuth.ts
### C

여기 파일에서 4개의 쿼리가 모여있는 것 같은데, queries/auth 폴더에 4개로 분할해서 사용하는 건 어떤가요? 
useRecoidState랑 navigate가 겹치긴 하는데 컨벤션 맞추는 것도 좋을 것 같아요~

2023-08-14 11:36 UTC, bassyu commented on frontend/src/pages/Error/UnAuthorize.tsx
### R

unauthorized 는 한 단어라서 Unauthorize.tsx 로 네이밍 하는 건 어떤가요?

2023-08-14 11:36 UTC, bassyu commented on frontend/src/pages/Login/index.tsx
> +  const goToMainHandler = () => navigate(URL_PATH.main);
### C

반환값이 없다는 것을 명시적으로 알리는 것도 좋아보입니다!
```suggestion
  const goToMainHandler = () => {
    navigate(URL_PATH.main);
  }
```

2023-08-14 11:36 UTC, bassyu commented on frontend/src/pages/RootTemplate/index.tsx
> +      const unValidPath = loginUrl.find((url) => pathname.includes(url));
### R

이 친구도 한 단어로 봐도 될 것 같아요~
```suggestion
      const unvalidPath = loginUrl.find((url) => pathname.includes(url));
```

2023-08-14 11:36 UTC, bassyu commented on frontend/src/hooks/useAuth.ts
> +  const userLogout = useMutation({
### R
혹시 원래 의도가 맞을까요?
```suggestion
  const userLogout = () => useMutation({
```

2023-08-14 12:06 UTC, hozzijeong commented on frontend/src/apis/auth.ts
> +};
이게 authorizationcode를 얻는 url로 보내는거여서 auth에 있는게 맞다고 생각을 했습니다... 

다른 파일로 옮긴다면 어디가 괜찮을것 같으신가요?

2023-08-14 12:09 UTC, hozzijeong commented on frontend/src/apis/auth.ts
> +const Auth = {
좋은것 같습니다 ㅎ

2023-08-14 12:09 UTC, hozzijeong commented on frontend/src/hooks/useAuth.ts
괜찮은 생각 같아요! 바로 바꿔보겠습니다!

2023-08-14 12:10 UTC, hozzijeong commented on frontend/src/hooks/useAuth.ts
> +  const userLogout = useMutation({
원래 의도가 맞긴한데, 화살표 함수형으로 선언하면 ()로 실행 시켜야 하기 때문에 굳이 필요가 없다고 생각해서 바꿨습니다..ㅎ

2023-08-15 04:23 UTC, WaiNaat requested changes
안녕하세요 클린! 신성한 연휴에도 어려운 작업을 해 주셔서 감사해요
로그인 관련 코드는 아직 잘 몰라서 일단 코드 한번 훑어만 봤습니다
로컬에서 브랜치 받아서 한번 해보고 궁금한 게 있으면 더 남길게요!

2023-08-15 04:23 UTC, WaiNaat commented on frontend/src/components/@common/Icons/KakaoLoginLarge.tsx
> +          xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAW4AAABaCAYAAAHvOYwWAAAAAXNSR0IArs4c6QAAGX5JREFUeAHtXQl4FMW2/meyEhJCEgIhLAKCCoKIG+IFWVQ2URS5+JQICKg8QVzQJ+/hwnO/KqIIF2VTUbx6vaAoAiKy
😮

2023-08-15 04:23 UTC, WaiNaat commented on frontend/src/constants/index.ts
> +  international: 500,
### C

`internalServerError`는 어떠신가요

2023-08-15 04:23 UTC, WaiNaat commented on frontend/src/hooks/queries/reminder/useReminder.ts
> +    suspense: true,
### C

![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/a53b5baa-1060-40ad-a287-fb816374d73c)

suspense가 true면 error일때 던진다는데 이거랑 throwOnError랑은 약간 다른 설정인가요??

2023-08-15 04:23 UTC, WaiNaat commented on frontend/src/hooks/useAuth.ts
> +    retry: false,
### C

기회를 한 번만 주는 이유가 있나요??

2023-08-15 04:23 UTC, WaiNaat commented on frontend/src/pages/Login/index.tsx
> +        </div>
### R

태그의 의미를 생각하면 GotoMain을 Link로 하고 KakaoLoginLarge를 button으로 감싸는게 나은 것 같은데 어떻게 생각하시나요??

2023-08-15 04:23 UTC, WaiNaat commented on frontend/src/pages/RootTemplate/index.tsx
> +      const unValidPath = loginUrl.find((url) => pathname.includes(url));
### R

저는 `invalidPath` 추천합니다 👍

2023-08-15 06:03 UTC, hozzijeong commented on frontend/src/hooks/queries/reminder/useReminder.ts
> +    suspense: true,
원래 getSession이 Mutate였다가 useQuery로 설정하면서 제외하지 않은 옵션 같네요...ㅎ 

찾아보니, `throwOnError`를 true로 하게된다면 무조건 적으로 Errorboundary에 해당 오류를 던지겠다는 의미를 명시하는 것 같습니다. 기본은 undefiend이고, 그럴 경우에는 query의 설정에 따라 처리가 되고 있습니다. 

해당 query의 경우에는 세션을 얻는 쿼리로써 에러가 발생한다면 무조건적으로 에러를 표시하긴 해야 하긴 합니다. 하지만 suspense와 throwOnError를 동시에 사용할 필요는 없는것 같아요!

2023-08-15 06:05 UTC, hozzijeong commented on frontend/src/hooks/useAuth.ts
> +    retry: false,
사용자의 sessionId가 잘못된 값을 반환했다면, 다시 로그인해서 새로운 값을 받으면된다고 생각했습니다. 문제의 해결 방법이 단순한데 굳이 여러번 요청을 할 필요가 있나? 하는 생각이 들어서 한번이면 충분하다고 생각했습니다.

2023-08-15 06:25 UTC, hozzijeong commented on frontend/src/apis/auth.ts
> +};
카카오 로그인 버튼을 Link로 변경하면서 바로 접근하기 위해 `AUTHORIZATION_URL`을 그대로 반환했습니다!

2023-08-15 06:30 UTC, WaiNaat requested changes
코드 읽고 추가 리뷰 남겨요~

비로그인 때 리마인더 -> 로그인페이지 -> 메인화면 반복하면 어느순간부터 터지는 문제가 있습니다 (왜인진 진짜 모르겠어요😥)
![로그인 안하고 404](https://github.com/woowacourse-teams/2023-pium/assets/77872742/97907913-6123-4a92-9dee-7d286f2b97a7)

2023-08-15 06:30 UTC, WaiNaat commented on frontend/src/router.tsx
> +          </ErrorBoundary>
### R

이 보일러플레이트 없애는법을 알아왔습니다

router.tsx 페이지 컴포넌트를 감싸는 모든 Errorboundary랑 Suspense를 없애고 App.tsx에 있는 Errorboundary도 모두 없앱니다

그담에 RootTemplate에 가서 리턴값을 아래처럼 고치면 전역 에러바운더리 두 개랑 전역 suspense 하나를 설정할 수 있어요!!
```jsx
<Wrapper>
  <PageArea>
    <ErrorBoundary fallback={<NotFound />}>
      <ErrorBoundary fallback={<UnAuthorize />} statusCode={401}>
        <Suspense fallback={<Loading />}>
           <Outlet />
        </Suspense>
      </ErrorBoundary>
    </ErrorBoundary>
  </PageArea>
</Wrapper>
```

2023-08-15 06:30 UTC, WaiNaat commented on frontend/src/hooks/useAuth.ts
> +        return null;
아 void면 에러가 나오네요😅

2023-08-15 06:34 UTC, hozzijeong commented on frontend/src/components/@common/Icons/KakaoLoginLarge.tsx
> +          xlinkHref="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAW4AAABaCAYAAAHvOYwWAAAAAXNSR0IArs4c6QAAGX5JREFUeAHtXQl4FMW2/meyEhJCEgIhLAKCCoKIG+IFWVQ2URS5+JQICKg8QVzQJ+/hwnO/KqIIF2VTUbx6vaAoAiKy
카카오에서 제공하는 것을 그대로 받아오다 보니... 이렇게 됐습니다..ㅎ

2023-08-15 06:35 UTC, hozzijeong commented on frontend/src/pages/RootTemplate/index.tsx
> +      const unValidPath = loginUrl.find((url) => pathname.includes(url));
invalidPath로 변경하곘습니다!

2023-08-15 06:46 UTC, hozzijeong commented on frontend/src/router.tsx
> +          </ErrorBoundary>
오우 마이 가핫! 감사합니다 참새!

2023-08-15 06:47 UTC, hozzijeong commented on frontend/src/store/atoms/userInfo.ts
> +const sessionId = sessionStorage.getItem('sessionId');
쿠키로 가져오면 msw에서 해당 쿠키가 유효한 값인지 아닌지 판별하기가 어렵습니다. 따라서 브라우저가 닫히면 사라지는 sessionStorage를 사용했고, 만약에 브라우저를 종료했다가 다시 키는 경우라면 다시 로그인 해야 된다는 가정을 갖고 적용했습니다.

2023-08-15 06:48 UTC, hozzijeong commented on frontend/src/hooks/useAuth.ts
> +        const sessionId = cookieValue.slice(0, 10);
처음에 에러가 나길래, 용량이 너무 커서인가? 하고 생각을 해서 10개로 한정지었었는데, 제가 `stringify` 하지 않아서 생겼던 문제더라구요...ㅎ 하지만 별 문제가 없어서 그대로 뒀었습니다

2023-08-15 06:49 UTC, hozzijeong commented
추가로, 참새가 말한 에러가 왜 나는지를 좀 찾아보고 있는데, msw에서 401에러를 뱉는게 아니라 500에러를 뱉고있더라구요? 그래서 지금 해결 방법을 모색중에 있습니다

2023-08-15 07:49 UTC, WaiNaat commented on frontend/src/store/atoms/userInfo.ts
> +const sessionId = sessionStorage.getItem('sessionId');
msw만을 위한 설정이라면 없애는 게 좋다고 생각해요
msw에서 oauth 자체를 모킹해서 로컬에서는 카카오 로그인 없이 msw가 `ctx.cookie`로 특정 값을 설정해서 그걸로 유효성을 판별하는 게 더 나을 것 같아요

2023-08-15 08:16 UTC, hozzijeong commented on frontend/src/store/atoms/userInfo.ts
> +const sessionId = sessionStorage.getItem('sessionId');
위에서 sessionStorage를 사용한 것은 msw만을 위한 설정이긴 하지만, 브라우저 스토리지를 사용한 것은 msw만을 위한 설정은 아닙니다. 로그인을 성공했어도 새로고침 하게된다면 로그인이 풀리는 현상이 발생하는데 이를 해결하기 위해서는 localStorage나 sessionStorage가 필요하다고 생각했습니다.

카카오 OAuth 모킹과 관련해서는 카카오 계정을 입력 받고, 이를 통해 로그인 까지는 이루어져야 한다고 생각합니다. 카카오 계정을 통해서 인증 코드를 받는 것 까지가 프론트의 역할이기 때문에 해당 부분까지는 구현을 했습니다. 

카카오 계정을 통해서 받은 인증 코드를 가지고 AccessToken을 받는 카카오 API를 한번 더 호출하고, 그 토큰을 가지고 카카오 정보에 접근하는 방식인데, `msw`에서는 `AccessToken`을 받는 것까지는 구현하지 않고 넘겨받은 코드를 SessionStorage에 저장하는 방식으로 구현했습니다.

2023-08-15 09:04 UTC, hozzijeong reviewed
로그인 유지를 위해서 브라우저 스토리지를 사용하는 것에 대해 어떻게 생각하는지 궁금합니다. (LocalStorage vs SessionStorage) 굳이 브라우저 스토리지가 아니라 로그인 상태를 유지할 수 있는 방법에 대해서 생각나는게 있으면 말씀 부탁드립니다. 

저는 쿠키에 만료 값을 줄 수 있기 떄문에 LocalStorage가 괜찮지 않을까 생각을 했습니다. 새로고침을 할 때 리코일에서 LocalStorage에 있는 값으로 로그인 여부를 판단해도 좋다고 생각했습니다. 하지만 로컬스토리지에 있는 값이 유효한 세션인지는 검증이 필요하긴 합니다...

2023-08-15 09:29 UTC, WaiNaat commented
우선 지금 로그인을 해야 접근할 수 있는 부분들에 대한 cypress 테스트가 안 됩니다.. conflict 때문에 github actions가 안 돌아가는 것 같아요

저는 msw에서 로그인을 모킹하는 게 맞다고 생각합니다.  카카오 로그인 역시 api 통신의 일종인데 그것만은 모킹을 하지 않아야 하는 특별한 이유를 모르겠어요. 만약 로컬에서도 카카오 로그인을 확인해야 한다면 npm run dev를 하면 된다고 생각합니다

스토리지를 쓴 이유는 제가 아예 잘못 이해하고 있었네요. 세션 쿠키는 브라우저를 닫으면 없어진다는 걸 몰랐어요
그려면 로컬스토리지를 쓰는 수밖에 없을 것 같습니다
개인적으로는 로컬스토리지 사용을 피하고 싶기는 한데 별다른 해결책이 없는 것 같아요ㅠㅠ 프론트엔드의 한계같습니다

2023-08-15 10:34 UTC, WaiNaat requested changes

2023-08-15 10:34 UTC, WaiNaat commented on frontend/src/hooks/useUnauthorize.ts
이거저거 해봤는데 thrnwOnError에 side effect가 들어있는 게 문제인 것 같아요 원인을 통 알수가 없네요

2023-08-15 11:30 UTC, hozzijeong commented on frontend/src/pages/Error/UnAuthorize.tsx
한번 커밋을 했었는데도 적용이 안되었군요...;; 

push를 해보는 걸로 시도해보겠습니다.

2023-08-15 12:40 UTC, hozzijeong reviewed
- [x] cypress에서도 로그인 된 것처럼 처리
- [x] 6연속 토스트 막기 
   - 아마 렌더링 도중에 바로 다른 렌더링이 발생해서 생겨난 것으로 추측. `useEffect`로 감싸니 없어졌습니다.

2023-08-15 12:40 UTC, hozzijeong commented on frontend/src/hooks/useQueryWrapper.ts
참새의 생각대로 `throwOnError`에서는 `side-effect`를 실행시키면 안되는 것 같습니다.

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/db3db09d-e0f1-4013-b226-1f22134aefca)

공식문서에 true인 경우에 `render phase`라는 명확한 워딩이 있는데, render phase일 때는 순수함수만 반환해야 한다는 걸로 알고있습니다. 그래서 실행시키면 안되는 것 같아요.

따라서 렌더링이 끝난 다음에 나오는 결과값에 따라 처리를 해야 된다고 생각을 했습니다. 그래서 결과로 나온 `error`의 값을 받아서, 401이라면 toast메세지와 redirect를 시키는 훅을 하나 만들어 봤습니다. 결과는 아래와 같이 `dev`모드 이기 때문에 두 번 렌더링 되는 형식으로 나타나게 됩니다.

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/4a6e8114-8384-4bb2-b041-c8bebd5d3285)

다만 이 방식이 맞는것인가 싶어서 현재까지는 `useQuery`에 대한 처리만 해놓은 상태입니다. 만약에 괜찮다고 하시면 useMutation이랑 infinityScroll에도 적용시킬 예정입니다.

2023-08-15 13:38 UTC, WaiNaat commented on frontend/src/hooks/useQueryWrapper.ts
좋은데요? 폰이라 코드를 제대로 보기 힘들긴한데 대략 봤을땐 괜찮아 보여요

다만 이름을 wrapper가 아니라 해당 함수가 하는 일을 표현해주면 좋을거같아요

2023-08-16 00:57 UTC, WaiNaat requested changes
바꾸신 부분들 확인했어요!
지금도 토스트가 세 개씩 나오는데 하나는 addToast 최적화가 안되어서고 하나는 StrictMode 때문이라 큰 문제는 없어보입니다

2023-08-16 00:57 UTC, WaiNaat commented on frontend/src/hooks/useQueryWrapper.ts
> +      if (query.error.statusCode === STATUS_CODE.unauthorize) {
### R

여기는 &&으로 묶어도 될 것 같습니다

2023-08-16 00:57 UTC, WaiNaat commented on frontend/src/hooks/useQueryWrapper.ts
> +        navigate(URL_PATH.login);
### C

navigate 하고 replace true는 어떠신가요

2023-08-16 00:57 UTC, WaiNaat commented on frontend/src/hooks/useUnauthorize.ts
> +        return false;
### C

함수 자체를 이렇게 줄일 수 있을 것 같아요

```suggestion
  const throwOnErrorCallback = useCallback((error: Error | StatusError) => (
    !(error instanceof StatusError) || error.statusCode !== STATUS_CODE.unauthorize
);
```

2023-08-16 01:51 UTC, WaiNaat commented
혹시 StatusError를 utils로 옮기는거 어떠신가요??

2023-08-16 04:08 UTC, hozzijeong reviewed
#280 관련 테스크 처리했습니다. 

`members/me`의를 호출하는 경우는 `useQuery`를 호출했을 때 우선적으로 검증을 하고, api를 호출했습니다. mutation의 경우에는 에러가 발생했을 때 errorboundary로 이동하도록 했습니다.

2023-08-16 07:03 UTC, bassyu requested changes
확인했습니다!! 마이페이지 스타일만 수정되면 될 것 같아요! 👍 👍

2023-08-16 07:05 UTC, bassyu approved these changes

2023-08-16 09:09 UTC, merged