feat: 반려식물 단건 히스토리 조회에서 필터링 추가
woowacourse-teams/2023-pium pull request #273
Opened 2023-08-14 10:00 UTC by rawfishthelgh

# 🔥 연관 이슈

- close #219 

# 🚀 작업 내용

querydsl을 활용하여 반려식물 단건 조회시
`filter=`에 해당하는 쿼리 파라미터에 따라 반려식물을 다르게 가져오도록 구성했습니다.

# 💬 리뷰 중점사항
`HistoryCustomRepository`와 `HistoryCustomRepositoryImpl` 부분에서 논리적 오류가 없는지,
`HistoryService`의 read 메소드 부분과 함께 봐주시면 되겠습니다!

2023-08-15 01:48 UTC, Choi-JJunho requested changes
전체적으로 잘 적용해주셨네요!
컨벤션과 같은 자잘한 내용만 확인 부탁드려요~

2023-08-15 01:48 UTC, Choi-JJunho commented on backend/pium/build.gradle
> +tasks.withType(JavaCompile) {
### C

사소한 내용이지만.. 한줄 띄워주면 좋을 것 같아요~!

2023-08-15 01:48 UTC, Choi-JJunho commented on backend/pium/build.gradle
> +    from("${asciidoctor.outputDir}") {
### C

CMD Shift L 로 라인정렬 한번 부탁드려요~

2023-08-15 01:48 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +
### R

불필요한 공백이있네요!

2023-08-15 01:48 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +
### R

불필요한 공백이 있네요!

2023-08-15 09:22 UTC, yeonkkk requested changes
안녕하세요 하마드!
코드를 깔끔하게 잘 작성해주셔서 컨벤션 관련 코멘트와 개인적인 질문이 전부인 것 같네요 ㅎㅎ
남긴 코멘트 확인해주시고, 필요하다고 느껴지시면 적용해주시면 감사하겠습니다!

고생하셨습니다🙂

2023-08-15 09:22 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
> +            });
### A
꼭 적용할 필요는 없지만 이렇게도 작성해볼 수 있습니다🙂

```suggestion
assertThat(currentResponses)
                        .contains("lastWaterDate", "wind", "flowerpot")
                        .doesNotContain("waterCycle", "light", "location");
```

2023-08-15 09:22 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/controller/HistoryController.java
> +            @RequestParam(value = "filter", required = false) List<String> filters,
오 .. `@RequestParm` 사용하면 List로 받아주는군요 .. 하나 알아갑니다!

2023-08-15 11:13 UTC, rawfishthelgh commented on backend/pium/build.gradle
> +tasks.withType(JavaCompile) {
반영 환료!

2023-08-15 11:13 UTC, rawfishthelgh commented on backend/pium/build.gradle
> +    from("${asciidoctor.outputDir}") {
반영 완료!

2023-08-15 11:14 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/config/QueryDslConfig.java
> +
반영 완료!

2023-08-15 11:27 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/acceptance/HistoryApiTest.java
> +            });
훨씬 낫군요 반영완료!

2023-08-15 11:28 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +
반영완료!

2023-08-15 11:28 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +
반영완료!

2023-08-15 11:30 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +
반영완료!

2023-08-15 11:30 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/repository/HistoryRepositoryTest.java
> +
반영완료!

2023-08-15 11:39 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
>                  () -> historyService.read(petPlant.getId(), PageRequest.of(0, 2, Sort.Direction.DESC, "waterDate"),
맞습니다! sorting 처리를 하는 로직이 이전에sms Pageable 객체만을 넘기고 해당 처리는 jpa가 직접 페이징을 하도록 했다면,
지금은 `HistoryCustomRepositoryImpl`에서
```java
@Override
    public Page<History> findAllByPetPlantIdAndHistoryTypes(Long petPlantId, List<HistoryType> historyTypes, Pageable pageable) {

        List<History> histories = jpaQueryFactory.selectFrom(history)
                .where(history.petPlant.id.eq(petPlantId), inHistoryType(historyTypes))
                .orderBy(new OrderSpecifier<>(Order.DESC, history.createdAt), new OrderSpecifier<>(Order.DESC, history.date))
                .offset(pageable.getOffset())
                .limit(pageable.getPageSize())
                .fetch();

        return new PageImpl<History>(histories, pageable, getCount(petPlantId, historyTypes));
    }
```
위와 같은 형태로 직접 저희가 정렬 동작을 명시하고 있기에 어떤 값을 넣어도 상관이 없게 됩니다!

2023-08-15 11:42 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
>                  () -> historyService.read(petPlant.getId(), PageRequest.of(0, 2, Sort.Direction.DESC, "waterDate"),
오오 감사합니다 ㅎ
그럼 `PageRequest.of(0, 2, Sort.Direction.DESC, "waterDate")`와 같이 sort 관련 정보를 넣는 건 명시적인 이유 때문인건가요?

2023-08-15 11:56 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +        PetPlantResponse petPlantResponse = petPlantService.create(PetPlantCreateRequest.builder()
반영완료!

2023-08-15 11:56 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
> +                            .toList()).doesNotContain("waterCycle", "light", "location");
반영 완료!

2023-08-15 12:07 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/service/HistoryServiceTest.java
>                  () -> historyService.read(petPlant.getId(), PageRequest.of(0, 2, Sort.Direction.DESC, "waterDate"),
사실 명시적으로도 필요하지 않을 것 같네요....ㅋㅋㅋㅋ삭제하는게 나을 것 같아요!

2023-08-16 01:37 UTC, yeonkkk approved these changes
반영 사항 확인했습니다.
고생하셨습니다 하마드 ~ 이만 approve 하겠습니다!🌱

2023-08-16 01:58 UTC, Choi-JJunho approved these changes
고생하셨습니다~
더 수정할 내용은 없는 것 같아 Approve 하겠습니다

2023-08-16 01:58 UTC, merged