feat: 215 로그인, 로그아웃 기능 구현
woowacourse-teams/2023-pium pull request #274
Opened 2023-08-14 13:19 UTC by yeonkkk

# 🔥 연관 이슈

- close #215 

# 🚀 작업 내용
내용 추가 예정!

# 💬 리뷰 중점사항
내용 추가 예정!

2023-08-15 04:39 UTC, Choi-JJunho requested changes
조이 안녕하세요~! 리뷰어 주노입니다!

많이 어려웠을텐데도 잘 구현해주셨네요!
방대한 양의 테스트까지 꼼꼼하게 리팩터링해주셔서 감사합니다 👍
시간이 조금 남아 눈에 띄는 몇몇부분에 대해 먼저 리뷰를 남겨봅니다!

나머지 내용은 오늘 저녁이후나 내일 이야기해보도록하죠!

2023-08-15 04:39 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
> +        if (Objects.isNull(session)) {
### C

내부적으로 (session == null) 과 동일하게 동작하는 코드네요!
이전에 하마드의 리뷰 내용 중 동일한 내용이 있었는데요 해당 부분은 컨벤션을 맞춰보면 좋을 것 같아요

- https://github.com/woowacourse-teams/2023-pium/pull/139#discussion_r1275656106

2023-08-15 04:39 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
>                  .orElseThrow(() -> new NoSuchElementException("회원을 찾을 수 없습니다."));
### C

해당 경우 인증을 필요로하나 실패한 경우로 보이는데요!
`AuthenticationException` 혹은 다른 예외를 발생하는 편이 좋지 않을까 싶네요!

2023-08-15 04:39 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/AuthController.java
> +        session.setMaxInactiveInterval(21600);
### C
해당 시간에 대한 값을 상수로 구분하면 좋을 것 같아요!
```suggestion
        session.setMaxInactiveInterval(EXPIRED_TIME_SIX_HOUR);
```

2023-08-15 04:39 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
> +
### A

인증 관련 CustomException을 추가해주셨네요!
`HttpStatus.UNAUTHORIZED` 를 표현해야하기 때문이라면 찬성입니다! 👍

2023-08-15 04:39 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/AcceptanceTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
### A

WebEnvironment.DEFINED_PORT를 도입하게된 배경이 있을까요?

2023-08-15 04:39 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/controller/AuthControllerTest.java
> +                    .andDo(print());
### R

다음 코드로 RestDocs를 적용할 수 있습니다.

코드 반영 후 적용과정은 [팀 블로그 - RestDocs로 API 문서화하기](https://pium-official.github.io/restdocs-start/)의 `asciidoc 문서 생성하기` 부분을 참고하여 asciidoc도 추가해야할 것 같아요~

```suggestion
            mockMvc.perform(get("/login")
                            .param("code", "authorization code")
                            .contentType(MediaType.APPLICATION_JSON_VALUE))
                    .andDo(document("auth/login/",
                            preprocessRequest(prettyPrint()),
                            preprocessResponse(prettyPrint()),
                            queryParameters(
                                    parameterWithName("code").description("카카오 인증 코드")
                            ))
                    )
                    .andExpect(status().isOk())
                    .andDo(print());
```

2023-08-15 04:39 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/controller/AuthControllerTest.java
> +                    .andDo(print());
### R
> 다음 코드로 RestDocs를 적용할 수 있습니다.
코드 반영 후 적용과정은 [팀 블로그 - RestDocs로 API 문서화하기](https://pium-official.github.io/restdocs-start/)의 asciidoc 문서 생성하기 부분을 참고하여 asciidoc도 추가해야할 것 같아요~

ditto

```suggestion
            mockMvc.perform(post("/logout")
                            .session(session)
                            .contentType(MediaType.APPLICATION_JSON_VALUE))
                    .andDo(document("auth/logout/",
                            preprocessRequest(prettyPrint()),
                            preprocessResponse(prettyPrint()))
                    )
                    .andExpect(status().isOk())
                    .andDo(print());
```

2023-08-15 08:36 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
>                  .orElseThrow(() -> new NoSuchElementException("회원을 찾을 수 없습니다."));
제 생각은 `NoSuchElementException`을 그대로 가져가도 괜찮을 것 같기도 하네요.
 Repository 조회 과정에서 결과가 없는 경우는 NoSuchElementException로 통일하면 결과 유추가 더 쉽지 않을까??

2023-08-15 09:37 UTC, rawfishthelgh requested changes
조이! 가장 어려운 이슈였는데 개발하느라 고생하셨습니다.
제가 Auth 관련 지식이 많지 않아 좋은 리뷰를 했는지는 모르겠습니다만ㅜ
확인 후 주관에 따라 반영해주시면 감사하겠습니다!

2023-08-15 09:37 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
> +
저는 주노 리뷰에 궁금한 점이 있는데요! 
`HttpStatus.UNAUTHORIZED`는 `AuthenticationException`에 대한 처리를 하고 있는데 CustomException과 어떤 관련이 있나요??

2023-08-15 09:37 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
> +    public ResponseEntity<GlobalExceptionResponse> handleOAuthServerException(OAuthException e) {
### **A**

`KakaoServerException`에 대한 ExceptionHandler의 파라미터 인자를 상위 `OAuthException`으로 받은 이유는, 향후 다른 회사(구글 등)의 인증방식이 추가될 때 코드 변경을 막기 위한 확장성 차원인가요?
(그냥 질문입니다)

2023-08-15 09:37 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/Member.java
> +    private Long kakaoId;
### **A**
이것도 질문입니다! 향후 다른 회사의 Oauth 활용이 추가된다면,
해당 필드는 변경되나요? 아니면 그 회사의 ID를 보유한 필드가 추가되나요?
ex.`private Long googleId`

2023-08-15 09:37 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/exception/OAuthException.java
> +public class OAuthException extends RuntimeException {
예외 계층 굿 👍

2023-08-15 09:37 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/AuthService.java
> +                .build());
저도 주노의 의견에 동의합니다! 
Optional을 present로 검증하고 get을 사용하는 것은 안티 패턴이라고 하네요
[참고](https://www.latera.kr/blog/2019-07-02-effective-optional/)

2023-08-15 11:37 UTC, yeonkkk reviewed
@Choi-JJunho @rawfishthelgh 
주노, 하마드 ~ 리뷰 감사드려요!

1차 반영 완료 했습니다.

추가 리뷰도 잘 부탁드립니다 ~🙂

2023-08-15 11:37 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
>                  .orElseThrow(() -> new NoSuchElementException("회원을 찾을 수 없습니다."));
#277 

디스커션 생성했습니다.. 같이 이야기해보아요 !!

2023-08-15 11:37 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/service/dto/OAuthSupporter.java
> +    private String REDIRECT_URI;
properties 설정에 따라 값이 변경될수는 있지만, 초기화 후 런타임 시점에 변경되지는 않기 때문에 상수의 역할을 한다고 생각해서 위와 같이 작성했습니다.
그런데 주노 의견을 듣고 보니 변경의 여지가 있는 것 같네요. 
수정하겠습니다~

2023-08-15 12:27 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
>                  .orElseThrow(() -> new NoSuchElementException("회원을 찾을 수 없습니다."));
디스커션에 의견 남겼습니다!

2023-08-15 12:28 UTC, rawfishthelgh approved these changes
반영 사항 확인했습니다. approve 할게요!

2023-08-15 14:52 UTC, Kim0914 requested changes
조이... 로그인의 전설이군요 ㅎㅎ
넘 고생많았습니다 👏👏

테스트 쪽은 궁금한 점이 있어서 내일 조이에게 조언을 구한 후에 추가적으로 코멘트 달겠습니다 !!

2023-08-15 14:52 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
>  public class MemberArgumentResolver implements HandlerMethodArgumentResolver {
### C

패키지 라인에 커멘트가 남겨지지 않아서 여기 남길게요..!
ArgumentResolver는 Presentation 계층과 밀접한 것 같은데 config 패키지에 놓으신 이유가 궁금합니다 !

2023-08-15 14:52 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/config/MemberArgumentResolver.java
> +        Long kakaoId = (Long) session.getAttribute(SESSION_KEY);
### A

개인적인 생각입니다 ㅎㅎ (반영 안하셔도 좋아요 !)

`session.getAttribute(SESSION_KEY);`를 했을 때 반드시 Long 타입이 반환되는 것을 100% 보장하나요?!

그렇지 않으면 따로 메서드로 분리해 try catch를 잡아주면 좀 더 안정성 있지 않을까 생각합니다 😀

2023-08-15 14:52 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/AuthController.java
> +    public static final int EXPIRED_TIME_SIX_HOUR = 21600;
### C

`EXPIRED_TIME_SIX_HOUR` 접근자를 public으로 설정하신 이유가 있으신가요?!

2023-08-15 14:52 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/AuthController.java
> +                                         @Auth Member member) {
### A

라인 하나에 다 작성하는게 더 보기 좋을 것 같아요 !

2023-08-15 14:52 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/exception/OAuthException.java
> +    }
### A

정말 개인적인 궁금증입니다 ㅎㅎ

내부에 정적 팩토리 메서드로 작성해주신 이유가 궁금합니다 ~~

2023-08-15 14:52 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/AuthController.java
> +    public ResponseEntity<KakaoMemberResponse> login(
### C

메서드 반환 타입은 `KakaoMemberResponse`인데 실제 반환 값은 아무 값도 담기지 않는 것 같습니다 !

2023-08-15 14:52 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/dto/OAuthProvider.java
> +            return restTemplate.postForEntity(memberInfoRequestUri, request, KakaoMemberResponse.class)
### A

반환 타입을 `Long`으로 하고 restTemplate의 파라미터를 Long.class로 할 수 있을 것 같은데, 객체로 래핑해주신 이유가 궁금합니당

2023-08-15 14:52 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/UITest.java
> +                .willReturn(Optional.of(member));
굿 ! 잘 바꿔주셨군요 👍

2023-08-15 14:52 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/ReminderControllerTest.java
> +            mockMvc.perform(RestDocumentationRequestBuilders.post("/reminders/{id}", 1L)
### R

static import 해주세요 ㅎㅎ

2023-08-16 01:35 UTC, yeonkkk reviewed
@Kim0914 
그레이~ 피드백 반영 및 질문에 의견 남겼어요! 확인 부탁드립니다 ㅎㅎ

2023-08-16 01:39 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
> +
표현이 조금 부족했나보네요 😅
현재 저희가 정의한 GlobalExceptionHandler 상에서 `HttpStatus.UNAUTHORIZED`를 다루고 있는 경우가 없습니다.
자바에서 제공하는 표준 예외에서 인증과 관련한 예외를 제공하지 않고 있기 때문에 CustomException을 정의하는것이 적절해보인다는 이야기였습니다.

2023-08-16 01:49 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/AcceptanceTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
오! 그런 배경이 있었군요! 감사합니다 👍

2023-08-16 04:25 UTC, yeonkkk commented
@Choi-JJunho @Kim0914 
로그인 상태 확인 기능까지 추가 완료입니다!
리뷰 부탁드립니다 ㅎㅎ

2023-08-16 04:36 UTC, Kim0914 approved these changes
리뷰 반영사항 확인했습니다 !

고생했어용 ~

2023-08-16 07:20 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/domain/Member.java
> +    private Long kakaoId;
### R

엔티티의 필드가 변경됨에 따라 DB 변경사항을 고려해야하네요~!

Discussion을 하나 열었습니다 해당 내용에 대해 의견 나눠보면 좋을 것 같네요

- https://github.com/woowacourse-teams/2023-pium/discussions/287

2023-08-16 12:14 UTC, merged