feat: 에러바운더리 초기화 기능
woowacourse-teams/2023-pium pull request #284
Opened 2023-08-16 06:20 UTC by WaiNaat

# 🔥 연관 이슈

- close #278 

# 🚀 작업 내용

- #272 의 에러바운더리와 StatusError를 받아와서 확장했습니다.
- 에러바운더리 자체의 사용법은 전혀 변하지 않았어요
- Context를 사용해서 에러바운더리 하위 컴포넌트에게 에러바운더리의 setState를 전달해주는 방식입니다.
- 초기화를 원하는 곳에서 `useResetErrorBoundary` 훅을 사용해서 초기화 함수를 받아올 수 있습니다.

```tsx
// 사용 예시

const Redirect = ({ path }: { path: To }) => {
  const navigate = useNavigate();
  const resetErrorBoundary = useResetErrorBoundary();

  useEffect(() => {
    resetErrorBoundary();
    navigate(path, { replace: true });
  }, [navigate, resetErrorBoundary, path]);

  return <Loading />;
};

const Root = () => (
  <ErrorBoundary fallback={<Error />}>
    <ErrorBoundary fallback={<Redirect path="/" />} statusCode={401}>
      <Suspense fallback={<Loading />}>
        <Outlet />
      </Suspense>
    </ErrorBoundary>
  </ErrorBoundary>
);
```

# 💬 리뷰 중점사항

렌더링 최적화.. 됐겠죠??
예제 설정 귀찮으시면 저한테 오세용

2023-08-16 10:57 UTC, hozzijeong requested changes
resetErrorBoundary 메서드를 클래스에 선언하고, 해당 값을 넘기는게 어떤가요? (`react-error-boundary` 참고)

2023-08-16 10:57 UTC, hozzijeong commented on frontend/src/components/@common/ErrorBoundary/index.tsx
> +    const setStateFunction = this.setState.bind(this);
### C

setState라는 메서드를 작성하고, bind를 constructor에서 하는 것은 어떤가요? 렌더링 할때마다 bind를 할것 같습니다.

2023-08-16 11:19 UTC, WaiNaat commented on frontend/src/components/@common/ErrorBoundary/index.tsx
> +    const setStateFunction = this.setState.bind(this);
좋아요 좋아요
resetErrorBoundary 메서드를 constructor에서 묶고 그걸 context에 넘겨주는 방향으로 진행할게요

2023-08-16 11:34 UTC, bassyu approved these changes
멋있어요!

2023-08-17 08:18 UTC, hozzijeong requested changes
코멘트만 확인해주세요!

2023-08-17 08:18 UTC, hozzijeong commented on frontend/src/pages/PetRegister/Form/index.tsx
> +const STACK_ELEMENT_HEIGHT = '96px';
### R

사용하지 않는 변수입니다! 삭제 해주세요

2023-08-17 08:18 UTC, hozzijeong commented on frontend/src/pages/MyPage/index.tsx
> +  const { isLoading } = useCheckSessionId();
### C 

Suspense를 사용하지 않고 isLoading을 사용한 이유가 있나요?

2023-08-17 08:30 UTC, WaiNaat commented on frontend/src/pages/MyPage/index.tsx
> +  const { isLoading } = useCheckSessionId();
그러게요.. 리팩터링 과정에서 throw가 가능해지면서 불필요해진 코드네요

2023-08-17 08:51 UTC, hozzijeong approved these changes
멋있어요 👍

2023-08-17 08:56 UTC, bassyu approved these changes
확인했습니다~!

2023-08-17 08:56 UTC, merged