feat: 반려 식물 등록 사전정보 모달 추가
woowacourse-teams/2023-pium pull request #285
Opened 2023-08-16 06:27 UTC by bassyu

# 🔥 연관 이슈

- close #267
- close #282 

# 🚀 작업 내용

- 반려 식물을 등록
  - 사전 식물 정보 모달
  - 뒤로가기 헤더 추가
- 히스토리 URL 수정
- 파일 분리

# 💬 리뷰 중점사항

페이지에 있는 파일을 많이 분리했습니다! 확인해주세요~

2023-08-16 10:27 UTC, hozzijeong reviewed
파일 분리하고 나니 훨씬 좋네요~ 등록 정보도 확인 했습니다~ 코멘트 한번 확인해주세요~!

2023-08-16 10:53 UTC, bassyu commented on frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
> +    if (value > today) return;
스택이 내려오기도 하고, 입력값이 바로 바뀌어서 이대로도 괜찮다고 생각해요!

2023-08-16 11:16 UTC, WaiNaat requested changes
깔끔하게 잘 만들어주셔서 감사해요 쵸파

디자인적인 피드백으로는 우선 모달 내부 padding이 있었으면 좋겠습니다 (만약 너무 대공사라면 다음기회에 해도 괜찮아요)
![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/238c5d3d-08af-471e-81b5-d782c1b66f50)

그다음에 어떤 식물을 키우시나요 검색 페이지에도 뒤로가기 헤더가 있어야 해요
저번 데모데이 피드백이 저 페이지에서도 뒤로가기 같은 게 있었으면 좋겠다였거든요 👍

2023-08-16 11:16 UTC, WaiNaat commented on frontend/src/pages/PetRegister/Form/index.tsx
> +          <Image size="160px" src={image} />
### R

여기에 alt 부탁드려용

2023-08-16 11:16 UTC, WaiNaat commented on frontend/src/pages/PetRegister/Form/index.tsx
> +          <LineArrowLeft color="" />
### R

여기에도 aria-label이 있으면 좋을거같아요
\+ 색상을 빈 문자열로 주신 이유가 있나요??

2023-08-16 11:16 UTC, WaiNaat commented on frontend/src/pages/PetRegister/Form/index.tsx
> +        <DictionaryPlantName>{name}</DictionaryPlantName>
### C

이 친구가 버튼인 이유가 있나요??
아니면 얘도 같이 사전 정보 띄워주는 버튼 역할을 해도 괜찮아 보여요

2023-08-16 11:27 UTC, bassyu commented on frontend/src/pages/PetRegister/Form/index.tsx
> +        <DictionaryPlantName>{name}</DictionaryPlantName>
이것도 놓친 부분이네요! 감사합니다!

2023-08-16 11:32 UTC, bassyu commented
원래는 등록 검색 페이지에 navbar가 없었어서 받은 피드백이었는데 이제 생겼습니다! 
그래서 등록 폼에서 다시 다른 곳으로 가려면 뒤로 두번 가게 될까봐 등록 검색 페이지에는 뒤로가기를 추가하지 않았어요.

2023-08-16 11:58 UTC, WaiNaat commented on frontend/src/hooks/usePetPlantForm.ts
> +      return { ...petPlantForm, [action.key]: action.value.trim().slice(0, maxLength) };
### C

별명에 띄어쓰기를 아예 허용하지 않아야 한다고 생각하시나요??

저는 띄어쓰기는 허용하되 양식 제출 직전(mutate에 넣기 직전)에만 trim을 해서 앞뒤 공백을 처리하는 게 좋다고 생각해요
식물 이름 자체에 띄어쓰기가 있는 경우가 있고 이름 길이 제한이 30자로 넉넉해서 별명 띄어쓰기를 막을 필요까지는 없다고 봅니다

2023-08-16 12:06 UTC, hozzijeong requested changes
뒤늦게 리뷰가 생겨서... 코멘트 확인 부탁드려요!

2023-08-16 12:06 UTC, hozzijeong commented on frontend/src/components/dictionaryPlant/DictionaryPlantContent/DictionaryPlantContent.style.ts
> +export const Wrapper = styled.section`
### R

Wrapper가 section이고, 하위 엘리먼트도 section인게 조금 이상한것 같습니다...! (제가 짠 코드긴 하지만..ㅎ)
파일 분리를 하면서 Wrapper를 section으로 추가한 것 같은데 여기 wrapper는 main이 맞는것 같아요

2023-08-16 13:02 UTC, hozzijeong requested changes

2023-08-16 13:02 UTC, hozzijeong commented on frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
### R

전반적으로 폰트 크기가 맞지 않는다는 피드백이 있었습니다

`font: 500 1.8rem/2.2rem "GmarketSans"`로 통일해 주실 수 있나요??

2023-08-17 01:20 UTC, bassyu commented on frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
>      const { birthDate: formBirthDate, lastWaterDate: formLastWaterDate } = form;
그러게요..? 코드가 바뀌는 과정에서 뭔가 누락됐나봐요

2023-08-17 01:22 UTC, bassyu commented on frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
>      const { birthDate: formBirthDate, lastWaterDate: formLastWaterDate } = form;
그러게요! 원래 네이밍을 써도 될 것 같네요~

2023-08-17 01:33 UTC, bassyu commented on frontend/src/components/dictionaryPlant/DictionaryPlantContent/DictionaryPlantContent.style.ts
> +export const Wrapper = styled.section`
추출하면서 중복이 조금 있었네요! 해결하겠습니다~

2023-08-17 02:07 UTC, hozzijeong reviewed
멋져요👍

2023-08-17 02:07 UTC, hozzijeong approved these changes

2023-08-17 02:43 UTC, WaiNaat commented on frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
> +              value={form.nickname}
### C

구조 분해 할당을 아예 사용하지 않으신 이유가 있나요?
저는 매번 `form.`을 찍는 비용 + 이름이 길 때 가독성 + 불변성 실수 가능성 때문에 구조분해할당을 선호하는데 피하신 이유가 궁금합니다

2023-08-17 03:27 UTC, bassyu commented on frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
> +              value={form.nickname}
우선  예전코드를 그대로 추출한거라 딱히 피한 건 아닙니다! 이것도 큰 차이는 없다고 생각했어요.
그럼에도 답변 드려보자면...
매번 form을 찍는 것도 비용이지만, 구조분해 할당해서 const 로 선언을 하고 라인이 길어지는 것도 비용이라고 생각했어요.
이름이 길 때 가독성은 오히려 더 좋아진다고 생각했어요. 예를들면 select에 form.wind / OPTIONS.wind 둘 다 있는데 둘 다 구조분해 할당하면 formWind, optionWind로 구조분해 할당 해야하겠죠? 그대신 . 앞에 붙은 객체가 네이밍을 대신 설명해준다고 생각했어요.

2023-08-17 04:11 UTC, WaiNaat commented on frontend/src/components/petPlant/PetPlantRegisterForm/index.tsx
> +              value={form.nickname}
오 저랑은 완전 반대시네요 알갰습니다

2023-08-17 05:42 UTC, WaiNaat approved these changes
멋있어요

2023-08-17 05:42 UTC, merged