reactor: Theme 타입 적용 및 리팩터링
woowacourse-teams/2023-pium pull request #314
Opened 2023-08-30 11:17 UTC by bassyu

# 🔥 연관 이슈

- close #313

# 🚀 작업 내용

"display": "standalone"
해당 설정이 앱애서 바로가기를 만들 때 웹처럼 보이지 않고 앱처럼 보이게합니다.

styled-components theme 추론 되도록 했습니다!
린트 no-empty-interface가 여기서만 이상해서 비활성화 했습니다.

2023-08-31 06:45 UTC, WaiNaat requested changes
신성한 방학에도 업무를 해주셔서 감사해요

2023-08-31 06:45 UTC, WaiNaat commented on frontend/src/pages/PetPlantRegister/Form/index.tsx
> -  useCheckSessionId();
### R

`http://localhost:8282/register/1`로 로그인하지 않은 사람이 접근했을 때에도 리다이렉션을 해주는 역할이라 다시 살려주세요ㅠㅠ

2023-08-31 06:49 UTC, bassyu commented on frontend/src/pages/PetPlantRegister/Form/index.tsx
> -  useCheckSessionId();
오 꼼꼼하게 봐주셔서 감사합니다!

2023-08-31 07:10 UTC, hozzijeong reviewed
고생하셨습니다! 코멘트 한거 한번만 확인 해주세요

2023-08-31 07:10 UTC, hozzijeong commented on frontend/src/components/search/SearchResults/index.tsx
> +import useDictSearch from 'hooks/queries/dictionaryPlant/useDictionaryPlantSearch';
### C

파일 명은 변경하고, import 명은 변경하지 않은 이유가 있을까요??

2023-08-31 07:10 UTC, hozzijeong commented on frontend/src/hooks/queries/petPlant/useDeletePetPlant.ts
> +import PetAPI from 'apis/petPlant';
### C

여기도 파일명만 변경된 이유가 있다면 말씀해주세요!

2023-08-31 08:55 UTC, bassyu commented on frontend/src/components/search/SearchResults/index.tsx
> +import useDictSearch from 'hooks/queries/dictionaryPlant/useDictionaryPlantSearch';
놓친 부분입니다! 수정하겠습니다~

2023-08-31 08:55 UTC, bassyu commented on frontend/src/hooks/queries/petPlant/useDeletePetPlant.ts
> +import PetAPI from 'apis/petPlant';
여기도 놓쳤네요 👍👍

2023-09-01 00:39 UTC, WaiNaat approved these changes
멋있어요

2023-09-01 02:44 UTC, hozzijeong reviewed
일단은 8개정도 찾았는데 혹시 더 있을수도 있으니 한번 확인 부탁드려요

2023-09-01 02:44 UTC, hozzijeong commented on frontend/src/components/search/SearchBox/index.tsx
> +import useDictSearch from 'hooks/queries/dictionaryPlant/useDictionaryPlantSearch';
### C

네이밍1

2023-09-01 02:44 UTC, hozzijeong commented on frontend/src/hooks/queries/dictionaryPlant/useDictionaryPlantDetail.ts
> +import DictAPI, { DICTIONARY_PLANT_URL } from 'apis/dictionaryPlant';
### C

네이밍2

2023-09-01 02:44 UTC, hozzijeong commented on frontend/src/hooks/queries/petPlant/useEditPetPlant.ts
> +import PetAPI from 'apis/petPlant';
### C

네이밍3

2023-09-01 02:44 UTC, hozzijeong commented on frontend/src/hooks/queries/petPlant/usePetPlantCardList.ts
> +import PetAPI, { PET_PLANT_URL } from 'apis/petPlant';
### C

네이밍4

2023-09-01 02:44 UTC, hozzijeong commented on frontend/src/hooks/queries/petPlant/usePetPlantDetails.ts
> +import PetAPI from 'apis/petPlant';
### C

네이밍5

2023-09-01 02:44 UTC, hozzijeong commented on frontend/src/hooks/queries/petPlant/useRegisterPetPlant.ts
> +import PetAPI from 'apis/petPlant';
### C

네이밍6

2023-09-01 02:44 UTC, hozzijeong commented on frontend/src/pages/DictionaryPlantDetail/index.tsx
> +import useDictDetail from 'hooks/queries/dictionaryPlant/useDictionaryPlantDetail';
### C

네이밍7

2023-09-01 02:44 UTC, hozzijeong commented on frontend/src/pages/PetPlantRegister/Form/index.tsx
> +import useDictDetail from 'hooks/queries/dictionaryPlant/useDictionaryPlantDetail';
### C

네이밍8

2023-09-01 05:44 UTC, hozzijeong approved these changes
멋져요 👍

2023-09-01 05:44 UTC, merged