feat: 어드민 페이지 구현
woowacourse-teams/2023-pium pull request #333
Opened 2023-09-05 08:11 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #318 

# 🚀 작업 내용

- [x] 사전 식물 조회
- [x] 사전 식물 삭제
- [x] 사전 식물 수정
- [x] 사전 식물 등록 요청 페이지 구성

# 💬 리뷰 중점사항

thymeleaf를 사용하여 view를 구성했습니다.

view 부분보다는 이번 기능을 추가하면서 작성한 
`사전 식물 삭제`, `사전 식물 수정`, `Admin 권한의 인증 인가과정`에 대해 리뷰해주시면 좋을 것 같습니다.

2023-09-06 04:06 UTC, Kim0914 requested changes
어드민 페이지 멋지게 잘 만들어주셨군요?!
너무 고생많았습니다 ~

몇 가지 코멘트 남겼습니다 ㅎㅎ
확인부탁드려요 😄

2023-09-06 04:06 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
> +    public ResponseEntity<Void> write(@AdminAuth Admin admin, @RequestBody DictionaryPlantCreateRequest request) {
### C

사전 식물 생성 컨트롤러 테스트가 없는 것 같아요 !

2023-09-06 04:06 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
> +    public ResponseEntity<Void> delete(@AdminAuth Admin admin, @PathVariable Long id) {
### C

사전 식물 삭제 컨트롤러 테스트도 없는 것 같아요 !

2023-09-06 04:06 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
> +        Assertions.assertThatThrownBy(() ->
### C

static import !

2023-09-06 04:06 UTC, Kim0914 commented on backend/pium/src/main/resources/application.properties
> +spring.sql.init.mode=always
### A

always로 바꿔주신 이유가 있을까요?!

2023-09-06 04:16 UTC, Choi-JJunho commented on backend/pium/src/docs/contract.yaml
> +openapi: 3.0.3
헉.. 실습해보고 그대로 커밋에 들어가버렸네요 😅
제거하겠습니다!

2023-09-06 04:21 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/AdminPageController.java
> +public class AdminPageController {
넵! 현재 DictionaryPlant에 대한 CRUD를 수행하기 떄문에 해당 컨트롤러에 대한 테스트는 수행하지 않았습니다.

다만 생각해보니 RestDocs에 추가하는게 맞다는 생각이 드네요.. 테스트 추가하겠습니다!

2023-09-06 04:30 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
> +        return ResponseEntity.created(URI.create("")).build();
admin의 flow만 생각해서 write수행 시 production의 사전 식물 상세정보로 리다이렉트되는게 어색하다고 생각했었는데 다시 생각해보니 프론트의 구현 방식에 따라 결정되는 부분이네요!
그레이 의견대로 API의 명확한 동작수행을 위해 Location을 지정해주는 방향으로 수정하겠습니다~

2023-09-06 04:32 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
> +    public ResponseEntity<Void> write(@AdminAuth Admin admin, @RequestBody DictionaryPlantCreateRequest request) {
의식의 흐름을 제어하지 못했군요...😅
수정하겠습니다!

+) 테스트 보완하겠습니다~!

2023-09-06 04:34 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/DictionaryPlantController.java
> +    public ResponseEntity<Void> delete(@AdminAuth Admin admin, @PathVariable Long id) {
테스트 보완하겠습니다~!

2023-09-06 04:36 UTC, Choi-JJunho commented on backend/pium/src/main/resources/application.properties
> +spring.sql.init.mode=always
아 세상에.. 테스트해본다고 그대로 커밋해버렸군요
다시 수정하겠습니다

2023-09-06 05:06 UTC, yeonkkk reviewed
역시 피움 유일 풀 사이클 개발자 최준호..
어드민 페이지가 기깔나네요..🥹👍

코드를 너무 깔끔하게 짜주셔서 리뷰하기 수월했어요 ~~
코멘트 조금 남겼으니 확인 부탁드려요 ㅎㅎ 

고생하셨습니다!

2023-09-09 04:11 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/AdminPageController.java
> +    @GetMapping("/admin/dict")
프론트엔드 페이지 구조를 따라가보려고 dict로 구성했습니다~!
<img width="832" alt="image" src="https://github.com/woowacourse-teams/2023-pium/assets/49794401/fda65245-4000-41a5-9095-4a5aa6fe29d4">

2023-09-09 04:12 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/AdminPageController.java
> +    public String dictionaryPlantUpdateForm(@PathVariable Long id,@AdminAuth Admin admin, Model model) {
어라... 고양이가 키보드 밟고 지나갔나보네요 😅

2023-09-09 12:14 UTC, Choi-JJunho commented on backend/pium/src/main/resources/application.properties
> +spring.mvc.hiddenmethod.filter.enabled=true
넵! 맞습니다

thymeleaf를 사용하면서 javascript를 작성하지 않는 선에서 html 폼을 구성하는 방향으로 진행했습니다.

이 과정에서 사전 식물 update 요청을 수행하기 위해 PATCH 메소드를 사용하게 되었는데 기본적으로 HTML form 태그는 GET, POST 요청만을 지원하고있습니다.

자세한 이유는 다음 포스트를 참고해주세요
https://mangkyu.tistory.com/218

이 경우 PATCH, DELETE와 같은 메소드를 사용하기 위해서 다음과 같이 form 태그 내부에 hidden 속성의 input 태그를 생성하여 HTTP Method를 변경할 수 있습니다.

하지만 스프링 단에서 form 태그가 POST, GET 만가능하도록 제약을 걸고있기 때문에 위와같은 옵션을 줌으로써 form태그 사용 시 POST, GET 이외의 메소드도 사용 가능하도록 설정했습니다.

2023-09-09 12:39 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/AdminPageController.java
> +    public String dictionaryPlantList(@PageableDefault Pageable pageable, @AdminAuth Admin admin, Model model) {
반영하겠습니다~

2023-09-09 13:12 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/domain/Admin.java
> +    }
초기에 작성해뒀다가 제거하면서 까먹은 것 같네요...!!
제거하겠습니다~!

2023-09-09 13:13 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/exception/NeedAdminException.java
> +    }
AuthorizationException을 재사용 가능하도록 계층적으로 구성해보곘습니다~!

2023-09-11 05:20 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
> +    }
### A
예외가 계층을 가지니 메서드 명을 이렇게 가져가도 좋을 것 같네용🙂

```suggestion
    @ExceptionHandler(AuthorizationException.class)
    public ResponseEntity<GlobalExceptionResponse> handleAuthorizationException(AuthorizationException e) {
        String message = e.getMessage();
        GlobalExceptionResponse exceptionResponse = createExceptionResponse(message);
        log.warn(message);
        return new ResponseEntity<>(exceptionResponse, HttpStatus.FORBIDDEN);
    }
```

2023-09-11 05:29 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/controller/AdminArgumentResolver.java
> +    }
### A 
`@AdminAuth` 애너테이션 제거하신 이유가 뭔지 궁금해요!

2023-09-11 11:03 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/AdminArgumentResolver.java
> +    }
Member 인증과의 통일성을 위해 제거했습니다~!

2023-09-12 06:37 UTC, Kim0914 approved these changes
고생많았습니다 ㅎㅎ

코멘트 2개 남겼는데 반영해도 되고 안해도 되니 확인해보고 merge 해주십쇼 !

2023-09-12 07:11 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/AdminPageController.java
> +    public String adminPage(Admin admin, Model model) {
확실히 `@AdminAuth`를 추가하는게 통일성있어보이네요~
추가하겠습니다.

2023-09-12 07:11 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/AdminService.java
> +    public void login(AdminLoginRequest request, HttpSession session) {
좋아요~!
추가하겠습니다

2023-09-12 07:19 UTC, merged