feat: 모두의 정원 게시글 아이템 구현
woowacourse-teams/2023-pium pull request #340
Opened 2023-09-06 08:23 UTC by bassyu

# 🔥 연관 이슈

- close #337

# 🚀 작업 내용

게시글 아이템 컴포넌트를 만들었습니다.

<img width="915" alt="스크린샷 2023-09-06 오후 5 19 52" src="https://github.com/woowacourse-teams/2023-pium/assets/54442420/3c825ce0-bc4a-43d6-9ead-9e452baa0799">

# 💬 리뷰 중점사항

`사전 식물 상세`의 특별 관리 정보처럼 추가 줄바꿈을 했는데,
참새가 만든 이 로직을 컴포넌트로 추출할지 유틸로 추출할지 고민이에요~

2023-09-06 12:02 UTC, WaiNaat requested changes
이쁘게 만들어주셔서 감사해요!!

> 물주기를 새로운 줄에 넣으려다가 너무 길어져서 태그로 넣었어요.

저는 물주기랑 난이도가 오히려 더 중요한 정보라고 생각이 드는데 이걸 위로 올리고 환경정보를 태그로 하자니 너무 지저분할 것 같아요ㅠㅠ 마땅한 대안이 떠오르지는 않네요. 그래도 지금 디자인은 좋아요

> 날짜에 연도는 표현하지 않았는데 어떤가요?

👍 

> 사전 식물 상세의 특별 관리 정보처럼 추가 줄바꿈을 했는데,
참새가 만든 이 로직을 컴포넌트로 추출할지 유틸로 추출할지 고민이에요~

박찬호씨의 후기를 보고
![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/96573331-f842-4a87-84a4-c0eb8492e431)
이런 느낌으로 일정 길이 이상 길어지면 아래쪽을 흐리게 하면서 '더 보기' 같은 글자를 통해서 펼칠 수 있으면 좋겠다는 생각을 했어요. 특정 길이보다 길어지면 더 보기, 접기 글자를 추가해서 글 영역을 제어하는 컴포넌트를 만드는 게 어떨까요? 이렇게 만들면 사전 식물에서 특별 관리 정보가 길어지는 것도 깔끔하게 대처할 수 있을 것 같아요

2023-09-06 12:16 UTC, bassyu commented on frontend/src/components/garden/GardenPostItem/GardenPostItem.stories.tsx
> +} as const;
특별한 이유는 없습니다! 타입을 주는게 명확해보이네요~

2023-09-06 12:17 UTC, bassyu commented on frontend/src/components/garden/GardenPostItem/GardenPostItem.stories.tsx
> +};
이 부분을 해결 안 했었네요! 캬 해결책까지 감사합니다 👍

2023-09-07 01:43 UTC, hozzijeong reviewed
코드 확인했습니다! 빨리 만들어 주셨군요 👍

확실히 환경 정보가 길다 보니까 디자인하기가 어렵네요... 사실 환경 정보가 저렇게 길게 된 것은 사전 식물 상세보기와 같이 하나에 집중되는 페이지의 경우에 좀 더 자세한 설명을 넣기 위함이라고 생각했는데, 여러 개의 아이템들을 다루는 기능에 대해서 환경 정보를 길게 가져가는 게 좋은지 잘 므로겠습니다.

또한 참새가 말한 것 처럼 환경정보가 여러가개 있는데 박찬호씨 처럼 길을 길게 적게 되면 줄어들었을 때의 정보와 펼쳐졌을 때의 정보를 나누는 게 나을 것 같습니다. (약간 인스타 느낌처럼?) 기본적인 아이템의 height가 설정되어 있으면 더욱 좋을 것 같아요! 

코멘트 확인 부탁드려요!

2023-09-07 01:43 UTC, hozzijeong commented on frontend/src/components/garden/GardenPostItem/index.tsx
> +        {content
### C

문단을 나누는 메서드가 2군데에서 사용되는데 분리하는 것에 동의합니다!

2023-09-07 01:43 UTC, hozzijeong commented on frontend/src/components/garden/GardenPostItem/index.tsx
> +  const postingDate = convertDateKorYear(createdAt).slice(5);
### C

저는 년/월/일을 보여주는게 훨씬 낫다고 생각해요! 데이터가 쌓일수록 년도에 혼란이 올 수도 있는데, 명확하게 넣는게 좋을 것 같습니다.

2023-09-11 05:13 UTC, bassyu commented on frontend/src/components/garden/GardenPostItem/index.tsx
> +  const postingDate = convertDateKorYear(createdAt).slice(5);
좋아요! 년/월/일로 적용하겠습니다~

2023-09-11 11:00 UTC, WaiNaat requested changes
더보기 컴포넌트 좋은데요? 저희가 커뮤니티 기능이 셌으면 더 맛있었을 것 같아요

2023-09-11 11:37 UTC, bassyu commented on frontend/src/components/@common/SeeMoreContentBox/index.tsx
> +  children: string;
맞아요! children 이라는 네이밍의 필드면 가져옵니다~

2023-09-11 11:38 UTC, bassyu commented on frontend/src/components/garden/GardenPostItem/index.tsx
> +  const postingDate = convertDateKorYear(createdAt);
저의 스토리북에서는 괜찮은데 혹시 폰트 적용 후에도 짤리시나요?

2023-09-11 11:40 UTC, bassyu commented on frontend/src/components/@common/SeeMoreContentBox/hooks/useShowState.ts
> +
실제로 사용할 때 리뷰를 다시 닫을 것 같지는 않아서 
버튼이 없는게 더 깔끔하지 않을까? 생각했어요~

2023-09-11 11:43 UTC, bassyu commented on frontend/src/components/garden/GardenPostItem/index.tsx
> +        <PetPlantImage src={petPlant.imageUrl} alt="반려식물" />
아마 나중에 포스팅 용 사진이 따로 추가될 것 같습니다~

2023-09-12 03:27 UTC, hozzijeong requested changes
아까 말씀하신것도 반영 부탁드립니다! 식물이름이랑, 전반적인 디자인? 관련해서 수정 부탁드립니다!~!~! 

코멘트도 확인해주세요!

2023-09-12 03:27 UTC, hozzijeong commented on frontend/src/components/garden/GardenPostItem/index.tsx
> +  const postingDate = convertDateKorYear(createdAt);
### R

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/6847f656-a8c9-4b98-96cc-4a28cdf4f209)

'더보기'가 나타나기 화면에서 글의 윗부분만 짤려서 보이는데 해결 부탁드립니당...

2023-09-12 03:27 UTC, hozzijeong commented on frontend/src/components/@common/SeeMoreContentBox/index.tsx
> +            {paragraph}
### R

paragraph에 시맨틱 태그 추가 부탁드려요!

2023-09-12 05:23 UTC, bassyu commented on frontend/src/components/@common/SeeMoreContentBox/index.tsx
> +            {paragraph}
p 태그 말씀하는 것 맞나요? 추가하겠습니다!

2023-09-12 05:24 UTC, bassyu commented on frontend/src/components/@common/SeeMoreContentBox/hooks/useShowState.ts
> +  const wrapperRef = (instance: HTMLDivElement | null) => {
ref로 instance를 받아야만 해서 이렇게 작성하긴 했습니다!
setInitialShow는 어떤가요?

2023-09-12 06:01 UTC, WaiNaat approved these changes
귀찮은 디자인 요구사항들 해결하느라 고생하셨습니다!! 멋져요 쵸파

2023-09-12 15:11 UTC, bassyu commented
latest 입니다~!

<img width="680" alt="스크린샷 2023-09-13 오전 12 10 39" src="https://github.com/woowacourse-teams/2023-pium/assets/54442420/7922a5d5-326c-4b8a-8c27-e27a536f4919">

2023-09-13 01:15 UTC, hozzijeong commented on frontend/src/components/@common/SeeMoreContentBox/hooks/useShowState.ts
> +  const wrapperRef = (instance: HTMLDivElement | null) => {
instance로 받는 것이라면, 그 파라마터의 이름이 instanceRef와 같은 식으로 가고, 변수 명은 행동 위주로 가면 더 좋을것 같긴 하네요!

2023-09-13 01:17 UTC, hozzijeong approved these changes
확인했습니다~ 고생하셨어요~!

2023-09-13 01:17 UTC, merged