feat: 사전 식물 등록 신청 페이지
woowacourse-teams/2023-pium pull request #349
Opened 2023-09-11 07:28 UTC by WaiNaat

# 🔥 연관 이슈

- close #330 

# 🚀 작업 내용

- 사전 식물 검색에서 등록 신청 페이지로 이동하는 링크

<img src="https://github.com/woowacourse-teams/2023-pium/assets/77872742/9d621ec6-9813-4a39-a6d8-4e9feb0a61f2" width="200"><br/>
<img src="https://github.com/woowacourse-teams/2023-pium/assets/77872742/ccb10d22-f14d-48b9-8de9-dc7881fe7854" width="200">

- 등록 신청 페이지

<img src="https://github.com/woowacourse-teams/2023-pium/assets/77872742/ab91db38-d889-4179-87b3-49bd1479f29d" width="500">

# 💬 리뷰 중점사항

사전 식물 등록 신청은 피움 자체의 기능과는 결이 다르다고 생각해서 api 요청 주소를 아예 다르게 설정했어요.
일단 파일 크기는 5MB, 확장자는 이미지면 모두 받도록 해 놓은 상태에요
여기서 보내는 사진은 원본을 보존할 필요는 없다는 생각이 들어서 압축해서 보내는 게 좋을까요?

2023-09-11 11:36 UTC, bassyu requested changes
확인했습니다!
깔끔하고 이쁘게 구현해주셨네요 👍👍👍

결과가 없다면 검색창 컴포넌트에서 링크를 바로 보여줘도 좋을 것 같습니다~

2023-09-11 11:36 UTC, bassyu commented on frontend/src/utils/image.ts
> +  return firstImage || null;
👍

2023-09-11 11:36 UTC, bassyu commented on frontend/src/constants/index.ts
> +  newDictionaryRequest: '/add-this-to-dictionary',
### A

사용자 친화적인 url로 재구성 하신건가요? 이것도 좋은 것 같습니다!

2023-09-11 11:38 UTC, WaiNaat commented on frontend/src/pages/NewDictionaryRequest/RequestDictionaryPlantForm/index.tsx
좋습니다

2023-09-11 11:41 UTC, WaiNaat commented on frontend/src/pages/NewDictionaryRequest/index.tsx
> +        <ContentHeader title="새로운 식물 추가 요청하기" />
앗 헤더였군요..

2023-09-11 11:44 UTC, WaiNaat commented on frontend/src/constants/index.ts
> +  newDictionaryRequest: '/add-this-to-dictionary',
request-new-dictionary-plant 보단 읽기 편하다고 생각했습니다

2023-09-12 05:51 UTC, hozzijeong requested changes
고생하셨습니다 참새! 궁금증이 몇 개 있어서 추가로 달아볼게요!

1. 입력 제출 폼에 선택이 2개 있던데, 둘 다 선택을 하지 않으면 유효성 검증이 통과되지 않더라구요.. 뭔가 선택 2개가 있다라고 하면 둘 다 선택하지 않아도 될 것 같은 느낌이 드는데 워딩을 수정하거나 안내 메시지 같은 것을 추가하는 것은 어떻게 생각하시나요?
2. 식물 이름 입력에서 직접 수정하는 것 자체에 대해서 약간은 회의적인 느낌이 들긴 합니다. 현재 식물 등록 폼 자체가 검색창을 통해서만 들어갈 수 있는데, 식물 이름을 변경할 수 있는 기능을 추가로 넣는 게 괜찮은 방법인지 잘 모르겠습니다.
3. 동일한 이름의 식물을 검색했을 때 일치하는 결과만을 반환하고 식물 등록으로 접근할 수 없던데, 동일한 이름을 갖고 있지만 결과가 없는 경우에 접근할 수 있는 방향이 없는 것 같더라고요... 같은 검색 결과가 나왔을때도 등록 신청하는 기능이 있으면 좋을것 같아요

ps. 약간 추천(?) 해보고 싶은게, 아예 검색 창을 클릭했을 때 `searchResult`를 보여주는 것은 어떤가요??

2023-09-12 05:51 UTC, hozzijeong commented on frontend/.storybook/preview.tsx
> +import dictionaryRegistrationHandlers from '../src/mocks/handlers/dictionaryRegistration';
### R

저희 사전 식물의 prefix를 `dictionaryPlant`통일하기로 기억합니다!! `dictionaryPlantRegistrationHandlers`가 맞는것 같아요!

2023-09-12 05:51 UTC, hozzijeong commented on frontend/src/apis/dictionaryRegistration.ts
> +    method: 'POST',
### C 

헤더에 `multipart/form-data`를 명시하지 않아도 괜찮을까요? (보투게더에서 명시하지 않긴 했지만...)

2023-09-12 05:51 UTC, hozzijeong commented on frontend/src/apis/dictionaryRegistration.ts
> +  const { name, image } = form;
### C

개인적으로 register에서 전달 받은 데이터를 formData로 변환하는게 맞나? 라는생각이 드는데 참새는 어떤가요?

2023-09-12 05:51 UTC, hozzijeong commented on frontend/src/constants/index.ts
> +  newDictionaryRequest: '/add-this-to-dictionary',
### A

this라고 하면 약간 추상적일 수도 있다고 생각이 드는데 저는 좀 더 사용자 행동에 초점을 맞춘 url이 괜찮지 않나? 생각이 듭니다. (request-new-dictionary-plant  <- 이거 괜찮은것 같은데요..?)

2023-09-12 05:51 UTC, hozzijeong commented on frontend/src/hooks/queries/dictionaryRegistration/useDictionaryRegistrationRequest.ts
> +      addToast('success', '식물 등록 신청에 성공했어요.');
### C

같은 식물의 이름이 존재한다면, 일단 등록하고 안내 페이지로 이동하는게 저는 좀 어색하다고 생각하는데 참새 생각은 어떤가요?

2023-09-12 05:51 UTC, hozzijeong commented on frontend/src/pages/NewDictionaryRequest/index.tsx
> +  const initialName = typeof state === 'string' ? state.slice(0, 30) : '';
### C

30자의 기준은 어디서 잡은건지 알 수 있을까요??

2023-09-12 08:04 UTC, WaiNaat commented on frontend/.storybook/preview.tsx
> +import dictionaryRegistrationHandlers from '../src/mocks/handlers/dictionaryRegistration';
api 주소가 dictionary-registrations라서 그거 따라갔는데 굳이 따라갈 필요도 없긴 하네요

2023-09-12 08:12 UTC, WaiNaat commented on frontend/src/apis/dictionaryRegistration.ts
> +    method: 'POST',
저는 명시하면 에러가 나서 찾아보니까 헤더에 넣으면 안된대요 ([링크](https://boomrabbit.tistory.com/245))

2023-09-12 08:24 UTC, WaiNaat commented on frontend/src/constants/index.ts
> +  newDictionaryRequest: '/add-this-to-dictionary',
생각해봤는데 `dict/new-plant-request`는 어떠신가요

2023-09-12 08:44 UTC, WaiNaat commented on frontend/src/apis/dictionaryRegistration.ts
> +  const { name, image } = form;
만들 때는 FormData는 컴포넌트의 관심사가 아니라 api 통신 로직 쪽의 관심사라고 생각했었는데요. 나중에 보내는 형식이 달라질 때 수정하기에도 용이하구요
근데 파일을 다른 형식으로 보낼 수 있을지는 잘 모르겠어요..

2023-09-12 08:46 UTC, WaiNaat commented on frontend/src/pages/NewDictionaryRequest/index.tsx
> +  const initialName = typeof state === 'string' ? state.slice(0, 30) : '';
반려식물 이름 제한이 30글자라서 그걸 따라했습니다. 찾아보니까 상수로 되어있네요 👍

2023-09-12 11:36 UTC, WaiNaat commented
추가한 것들입니다~

### 검색결과가 있어도 검색창에서 링크 표시
<img src="https://github.com/woowacourse-teams/2023-pium/assets/77872742/2d62bbc5-4435-4723-a46b-3aaaa448f940" width="555" alt="검색 결과 창 하단에 '등록 신청하기' 링크가 있다">

### 선택 사항 둘 다 안 골랐을 때 안내
<img src="https://github.com/woowacourse-teams/2023-pium/assets/77872742/efd1bb3d-7af8-48db-8569-62f80a393e18" width="555">

2023-09-13 01:18 UTC, hozzijeong commented on frontend/src/constants/index.ts
> +  newDictionaryRequest: '/add-this-to-dictionary',
좋은 것 같습니다!

2023-09-13 01:21 UTC, hozzijeong commented on frontend/src/apis/dictionaryRegistration.ts
> +    method: 'POST',
헉!! 분명 저도 봤던 글인데.... ㅋㅋㅋㅋㅋㅋ 꼼꼼이 봐야겠군요... override되는지 몰랐네요! 좋은 지식 알아갑니다👍

2023-09-13 01:23 UTC, hozzijeong commented on frontend/src/apis/dictionaryRegistration.ts
> +  const { name, image } = form;
아하! 저는 API 통신 메서드의 역할이 그저 전달 받은 인자를 넘겨주는 것! 이라고만 생각을 했어서요.. 확인했습니다!

2023-09-13 01:24 UTC, hozzijeong commented on frontend/src/pages/NewDictionaryRequest/index.tsx
> +  const initialName = typeof state === 'string' ? state.slice(0, 30) : '';
아하 좋습니다 👍

2023-09-13 01:29 UTC, hozzijeong approved these changes
코드 수정 확인했습니다 멋있어요7 👍

2023-09-13 04:44 UTC, bassyu approved these changes
반영 확인했습니다~!
멋져요 👍

2023-09-13 04:44 UTC, merged