feat: 반려 식물 사진 업로드
woowacourse-teams/2023-pium pull request #351
Opened 2023-09-12 07:29 UTC by Kim0914

# 🔥 연관 이슈

- close #321 

# 🚀 작업 내용

반려 식물 등록 시 반려 식물 사진을 업로드하는 기능을 구현했습니다.

# 💬 리뷰 중점사항

S3를 사용하는 이미지 업로드 객체 `PhotoS3Manager`를 구현했습니다.

S3 클라이언트를 사용하기 위해 빈으로 등록한 객체는 아래와 같습니다.

```java
@Bean
    public AmazonS3 amazonS3() {
        return AmazonS3Client.builder()
                .withCredentials(InstanceProfileCredentialsProvider.getInstance())
                .withRegion(Regions.AP_NORTHEAST_2)
                .build();
    }
```
`InstanceProfileCredentialsProvider.getInstance()`는 인스턴스 내의 IAM을 사용하도록 하는 설정입니다.

`PhotoS3Manager` 테스트는 스프링부트를 이용하지 않고 Mock을 이용해 테스트를 진행했습니다.
외부 API(Rest API가 아님) 테스트이기 때문에 스프링 부트를 이용한 테스트를 사용하지 않고 행위만 검증하는 Mock을 이용했습니다 !

사진 업로드 완료 후 S3 이미지 경로를 반환합니다.
`uploadPhoto` 메서드에서 반환하며 `rootPath + SLASH + directory + SLASH + workingDirectory + SLASH + fileName` 으로 반환합니다.

workingDirectory는 버킷 내에서 저장하는 폴더를 의미합니다. 반려 식물인 경우 `petPlant`입니다.
현재 PetPlantService에서 workingDirectory를 넘겨주고 있는데 이 부분이 조금 애매한 것 같기도 합니다 😂
관련해서 좋은 의견 있으시면 남겨주시면 감사하겠습니다 ㅎㅎ

2023-09-12 12:42 UTC, rawfishthelgh requested changes
그레이 어려운 로직 구현하느라 고생하셨습니다~
리뷰 달아놨으니 확인하시고 그레이 소신에 따라 반영 결정해주세요!

2023-09-12 12:42 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/config/S3Config.java
> +                .withRegion(Regions.AP_NORTHEAST_2)
### A
단순 궁금증인데 지역정보는 드러내도 상관없나요?

2023-09-12 12:42 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/vo/PhotoName.java
> +public class PhotoName {
### C
값을 가지고 있지 않으면서, 정적 기능만 수행하는 유틸성 클래스 같은데 vo 패키지에 위치한 이유가 있을까요?
유틸성 클래스 만든 것 자체는 좋은 것 같네요!!

2023-09-12 12:42 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/PhotoManger.java
> +}
### A
추상화 굿 👍

2023-09-12 12:42 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/PhotoS3Manager.java
> +public class PhotoS3Manager implements PhotoManger {
### A
단순 의견인데요! 지금도 큰 문제는 없지만,
외부 라이브러리 사용 로직이 Service 계층에 있는게 애매한 느낌이 듭니다.
뭔가 외부 라이브러리를 사용하는 패키지를 따로 만드는 것에 대해서는 어떻게 생각하시나요?

2023-09-12 12:42 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/PhotoS3Manager.java
> +            file.delete();
### A
혹시 delete 동작이 사용된 이유 설명 가능할까요??

2023-09-12 12:42 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +
### C
말씀하신대로 디렉토리를 서비스에서 넘겨주는게 애매하긴 하군요!
디렉토리 변경시 비즈니스 코드가 변경 될 위험성도 있는 것 같습니다.

그냥 생각나는 거는 도메인네임을 ENUM으로 관리해서 ENUM 값을 넘겨준 뒤, 
PhotoManager에서 어떤 도메인네임이 넘어오냐에 따라 디렉토리를 설정하는 방법도 있겠네요.

근데 사실 변경 가능성이 큰가를 따지면 그렇지도 않아서...선택의 차이 같습니다ㅋㅋ

2023-09-12 15:19 UTC, Choi-JJunho requested changes
안녕하세요 그레이~! 리뷰어 주노입니다 👍

전체적으로 이미지 업로드 및 반려 식물 등록 개선을 잘 해주셨네요!
파일 관리 및 몇가지 자잘한 부분들에 대해 이야기 나눠보면 좋을 것 같아 Request Change로 남겨둘게요~
확인 부탁드립니다!

2023-09-12 15:19 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/domain/vo/PhotoNameTest.java
> +class PhotoNameTest {
### A

이미지 테스트.. 감동입니다 🥹

2023-09-12 15:19 UTC, Choi-JJunho commented on backend/pium/src/test/resources/application.properties
> +aws.s3.root=https://static.pium.life
### C

실제 가용중인 도메인 주소보다는 임의의 주소로 두는건 어떤가요?
예를들어 `https://test.storage.com` 과 같은 임의의 URL이 있겠네요

2023-09-13 02:35 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/config/S3Config.java
> +                .withRegion(Regions.AP_NORTHEAST_2)
저는 괜찮다고 생각합니다 ㅎㅎ

2023-09-13 02:39 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/vo/PhotoName.java
> +public class PhotoName {
그렇네요 ㅎㅎ.. 값 객체를 의도하고 만들었는데 유틸 클래스가 더 적절하군요 🫢

2023-09-13 02:42 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PhotoS3Manager.java
> +            file.delete();
S3에 이미지가 업로드 되기 위해서는 이미지 파일(File이 로컬에 존재해야합니다 !

현재 `multipartFile.transferTo(convertedFile)`로 multipartFIle을 File로 변환하면서 로컬에 저장하고 있습니다.

S3에 업로드 된 이후에는 로컬에 해당 파일이 존재할 필요가 없기 때문에 delete를 사용해서 삭제해줬습니다 ~

2023-09-13 02:44 UTC, Kim0914 commented on backend/pium/src/test/resources/application.properties
> +aws.s3.root=https://static.pium.life
좋아요 !

2023-09-13 02:53 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +    }
오 너무 좋은데요?

saveImageIfExists 메서드에 defaultImageUrl 파라미터를 하나 더 열어서 null을 반환하지 않도록 수정하겠습니다 !!

2023-09-13 04:37 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +
주노와 하마드 의견을 둘 다 너무 좋은 의견이네요 ㅎㅎ

ENUM을 사용한 경우: Service에 필드를 사용하지 않아도 된다. 라는 장점이 너무 큰 장점인 것 같고
환경변수로 사용한 경우: 필드는 추가해야 하지만, 디렉토리 명이 변경되어도 애플리케이션 코드를 변경할 필요가 없다. 라는 점이 너무 큰 장점인 것 같습니다 !

둘 중에서 환경변수를 이용한 방법을 선택했는데, 그 이유는 필드 하나를 열어준 상태에서 디렉토리 명이 바뀌었을 때 애플리케이션 코드를 변경하는 비용이 더 클 것이라는 생각이 들어요 !

좋은 의견 감사합니다 :)

2023-09-13 04:37 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +    private static final String PET_PLANT = "petPlant";
주노와 하마드 의견을 둘 다 너무 좋은 의견이네요 ㅎㅎ

ENUM을 사용한 경우: Service에 필드를 사용하지 않아도 된다. 라는 장점이 너무 큰 장점인 것 같고
환경변수로 사용한 경우: 필드는 추가해야 하지만, 디렉토리 명이 변경되어도 애플리케이션 코드를 변경할 필요가 없다. 라는 점이 너무 큰 장점인 것 같습니다 !

둘 중에서 환경변수를 이용한 방법을 선택했는데, 그 이유는 필드 하나를 열어준 상태에서 디렉토리 명이 바뀌었을 때 애플리케이션 코드를 변경하는 비용이 더 클 것이라는 생각이 들어요 !

좋은 의견 감사합니다 :)

2023-09-13 04:49 UTC, Choi-JJunho approved these changes
반영해주신 내용 확인했습니다~!
전체적으로 문제없어보여 Approve하겠습니다 👍

magic number에 대한 코멘트 하나 달았습니다
아주아주 간단한 내용이니 확인 후 의견 부탁드립니당

2023-09-13 04:49 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/util/PhotoNameGenerator.java
> +        String fileBaseName = UUID.randomUUID().toString().substring(0, 8);
### A

0, 8로 설정한 이유가 있을까요?
적절한 길이정도라면 magic number를 상수로 표현하는것도 좋을 것 같아요

2023-09-13 05:02 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/util/PhotoNameGenerator.java
> +        String fileBaseName = UUID.randomUUID().toString().substring(0, 8);
UUID에서 첫 대시가 나오기 전까지를 가져오려고 했습니다 😂

상수화 해주는게 좋겠네용 ~

2023-09-13 07:42 UTC, merged