refactor: 348 성능 향상 시키기
woowacourse-teams/2023-pium pull request #355
Opened 2023-09-13 05:07 UTC by hozzijeong

# 🔥 연관 이슈

- close #348 

# 🚀 작업 내용
- [x] analyze 설치
- [x] code spliting 적용
- [x] lazy 적용
- [x] animation 최적화
- [x] image lazy loading 적용
- [x] svgSprite 적용
<img width="1395" alt="스크린샷 2023-09-12 오후 8 24 28" src="https://github.com/woowacourse-teams/2023-pium/assets/50974359/6a88c815-b367-4921-9688-30988282d187">

<img width="1432" alt="스크린샷 2023-09-12 오후 8 24 42" src="https://github.com/woowacourse-teams/2023-pium/assets/50974359/7ff5edad-5a4d-423b-8506-ade5fca8177b">

svgSprite를 사용함으로써 용량 30kb를 줄일 수 있었습니다. 

SVG-in-JS 자체를 컴파일 하는 것 자체가 비효율적인 계산이라고 생각해서 적용해보긴 했는데, `SVGSprite`라는 파일의 반환 형태가 JSX형태인데 이게 js로 반환하는 것과 어떤 차이가 있지? 라는 의문이 스스로 들었습니다... 메모리 측면에서 뭔가 가시적인 변화가 있을것이라고는 생각하지는 않았지만, 메모리 비교 자체 하는 방법을 몰라서 before after 확인이 메모리 줄이는 것 밖에 없었습니다. 이 부분은 좀 아쉽긴 하네요...

코드 보다가 이해 안가시는 부분 있으면 말씀해주세요!

# 💬 리뷰 중점사항
우선은 모든 페이지에 대해서 lazy를 적용했는데, 이게 괜찮은건지에 대해서는 의문이 있습니다. 실제 사용자들이 자주 방문하는 페이지 위주로 추후에 다시 적용하는 방식으로 접근해 보는게 나을것 같은데, 다른 분들 생각은 어떤지 궁금합니다. 

font에 preload를 적용했는데 이게 좀 애매한 것 같습니다. 잘 모르겠어요... 확장자가 `.css`이기 때문에 적용이 안되는것 같기도 합니다. 아니면 실제 폰트 파일을 `assets`에 넣어서 `preload`하는 방식도 있는데 어떻게 생각하시나요?

2023-09-13 11:27 UTC, bassyu reviewed
클린 최적화 진행하시느라 수고하셨습니다!!
궁금한 점만 Comment 남겨봤어요~
Navbar도 너무 이뻐졌네요! 👍👍👍👍👍

저는 개인적으로 SVG로 인한 큰 불편함이나 구조 개선 필요성을 간절하게 느끼지 못했어요.
그래서 개선 체감이 많이 안됐던 것은 조금 아쉽네요!

> 우선은 모든 페이지에 대해서 lazy를 적용했는데, 이게 괜찮은건지에 대해서는 의문이 있습니다. 실제 사용자들이 자주 방문하는 페이지 위주로 추후에 다시 적용하는 방식으로 접근해 보는게 나을것 같은데, 다른 분들 생각은 어떤지 궁금합니다.

저는 자주 방문하는 페이지는 청크를 분리하지 않고, 특정 사용자가 방문할 것 같은 페이지만 lazy를 적용하는 게 좋겠다고 생각했어요~
그런데 현재 저희 서비스에서 그런 페이지를 나눌 수 있을까? 생각해봤을 때 잘 떠오르진 않네요!
우선은 이대로도 좋을 것 같습니다~

> font에 preload를 적용했는데 이게 좀 애매한 것 같습니다. 잘 모르겠어요... 확장자가 .css이기 때문에 적용이 안되는것 같기도 합니다. 아니면 실제 폰트 파일을 assets에 넣어서 preload하는 방식도 있는데 어떻게 생각하시나요?

local에서 돌렸을 때 빠르게 가져오는 것 같은데 저는 LGTM 입니다..

2023-09-13 11:27 UTC, bassyu commented on frontend/webpack.config.js
> +    filename: '[name].[contenthash].bundle.js',
### C

이친구만 contenthash인 이유가 궁금합니다~!

2023-09-13 11:27 UTC, bassyu commented on frontend/webpack.config.js
> +        use: ['@svgr/webpack'],
오 svg는 svgr을 사용하는 것이 더 빠른가요?

2023-09-13 11:27 UTC, bassyu commented on frontend/webpack.config.js
> +          test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
react, react-dom을 청크로 추출한 이유가 궁금합니다!
항상 받는 파일이라면 큰 번들을 압축하는 것이 효율이 좋다고 들었는데 합치는 건 어떤가요?

2023-09-13 11:27 UTC, bassyu commented on frontend/src/pages/Main/Main.style.tsx
👍👍👍

2023-09-13 11:27 UTC, bassyu commented on frontend/src/router.tsx
> +const Login = lazy(() => import(/* webpackChunkName: "Login" */ 'pages/Login'));
저는 번들에 chunkName을 꼭 안줘도 될 것 같은데 어떻게 생각하시나요~?

2023-09-13 11:27 UTC, bassyu commented on frontend/.storybook/decorators.tsx
> +const SvgIcons = () => (
### C

헉.. 이 파일은 어쩔 수 없는 건가요?
이정도면 아예 파일로 빼도 좋을 것 같습니다..!

2023-09-14 02:29 UTC, WaiNaat requested changes
svg 스프라이트 기가 막히네요 너무 신기해요

### 폰트 관련

폰트 관련해서는 코멘트 남겼어요! 만약 다른 방법을 선택해야 한다면 클린이 말씀하신대로 아예 저희가 s3에 파일을 담아서 캐시정책을 통해 보내는 게 좋아보여요

### lazy

저는 개인적으로 모든 페이지에 lazy를 먹이는 건 SPA의 강점을 약화한다고 생각해서 회의적인 입장입니다. 그래서 lazy를 먹인다면 반대로 '자주 방문하지 않는 페이지'에 주는 게 낫지 않나 싶어요. 반려식물 등록이나 사전식물 등록신청 페이지처럼 일반적으로는 자주 방문하지 않는 페이지에 주는 게 불필요한 페이지 다운로드를 줄일 수 있지 않을까요??

2023-09-14 02:29 UTC, WaiNaat commented on frontend/public/index.html
> +    />
### C

이런 느낌으로 해당 css 안에서 받아오는 폰트를 preload하면 개선이 가능할 것 같아요~

![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/f527388a-1468-447a-92b5-ee5ace0573d4)

```suggestion
    <link
      rel="preload"
      as="font"
      type="font/woff2"
      crossorigin
href="https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.woff2"
    />
    <style>
      @font-face {
        font-family: 'GmarketSans';
        font-weight: 500;
        font-style: normal;
        src: url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.eot');
        src: url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.eot?#iefix')
            format('embedded-opentype'),
          url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.woff2')
            format('woff2'),
          url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.woff')
            format('woff'),
          url('https://cdn.jsdelivr.net/gh/webfontworld/gmarket/GmarketSansMedium.ttf')
            format('truetype');
        font-display: swap;
      }
    </style>
```

2023-09-14 06:32 UTC, hozzijeong reviewed
반영 사항들 코멘트 남겼습니다.

추가적으로 변경한 사항들이 있습니다.

- [x] 자주 사용되지 않는 페이지 (로그인, 마이페이지, 인증페이지)만 lazy loading 적용
- [x] font preload 적용
- [x] svg확장자 png로 변경

하나의 고민 상황이 있었는데, svg symbol이 있는 파일이(`SvgIcons)` src 내부에 있다는 것이 JS엔진이 굳이 필요 없는 태그를 파싱하는 것이라고 생각되어서 public/assets에 넣으려고 했습니다.

하지만 link형식으로 업로드 하려고 했지만, 인식을 하지 못핶고, 결국 남은게 html body에 직접 작성하는 것이 있었습니다. 

하지만, 추후에 icon이 추가될때마다 index.html 파일을 수정한다는게 상당히 껄끄러운 일이고, 차라리 매번 index.html파일을 수정하기 보다 Javascript 파싱을 하는게 더 낫다고 생각이 되어서 src내부로 옮겼습니다. (다른 방법이 있는지 모르겠네요ㅠ)

CC. @WaiNaat @bassyu

2023-09-14 07:34 UTC, bassyu approved these changes
font 감동적이에요 😭

2023-09-14 12:29 UTC, WaiNaat requested changes
캬 기가 막힙니다
svg는 저도 html에 넣기보다는 그냥 js에 넣는 게 낫다고 생각해요!
충돌 해결되면 머지할게용

2023-09-15 01:56 UTC, WaiNaat approved these changes
멋져요 고생하셨습니다 클린!

2023-09-15 01:56 UTC, merged