feat: 사진 등록 기능 추가
woowacourse-teams/2023-pium pull request #357
Opened 2023-09-13 08:17 UTC by hozzijeong

# 🔥 연관 이슈

- close #321 

# 🚀 작업 내용

- [x] 반려식물 등록 시에 이미지 등록 기능
- [x] 반려식물 수정 시에 이미지 수정 기능
- [x] 10MB이상의 이미지일 때 등록 되지 않음
- [x] 가능한 이미지 확장자 png, jpg, jpeg, heic

# 💬 리뷰 중점사항
반려식물 사진 이미지 최적화는 쉽지 않네요.... 일단 한번 해보고 문제가 생긴다면 다시 시도해 보는 방식으로 가야할 것 같습니다.

2023-09-13 12:06 UTC, WaiNaat requested changes
동시에 두 개의 이슈를 해결하시느라 고생하셨습니다ㅠㅠ
훅을 좀 가볍게 만들 수 있을 것처럼 보여서 그 부분 위주로 코멘트 남겼어요!

2023-09-13 12:06 UTC, WaiNaat commented on frontend/src/components/petPlant/PetPlantEditForm/index.tsx
> +              <HiddenLabel>이미지 변경하기</HiddenLabel>
### R

굳이 라벨을 안 숨기고 글자를 눌러도 변경 가능하게끔 하면 좋을 것 같아요!

2023-09-14 06:47 UTC, hozzijeong commented on frontend/src/components/@common/Icons/CirclePuls.tsx
헉... 그렇게 될것 같습니다

2023-09-14 06:48 UTC, hozzijeong commented on frontend/src/components/@common/ImageButton/ImageButton.stories.tsx
> +  component: ImageButton,
추가하겠습니다!

2023-09-14 06:49 UTC, hozzijeong commented on frontend/src/components/@common/ImageButton/hooks/useFileUpload.ts
> +          '지원하지 않는 확장자 입니다!jpg, jpeg, png, heic 확장자를 사용해주세요'
맞습니다... 짤리더라구요...

2023-09-14 06:49 UTC, hozzijeong commented on frontend/src/components/@common/ImageButton/index.tsx
> +        id="customImage"
괜찮은데요?

2023-09-14 06:56 UTC, hozzijeong commented on frontend/src/components/@common/ImageButton/index.tsx
> +        accept="image/*"
image/* 형태로 accept를 설정해야지, 카메라 접근이 가능하다고 합니다! [여기](https://web.dev/media-capturing-images/#file-input)

2023-09-14 06:57 UTC, hozzijeong commented on frontend/src/mocks/handlers.ts
> +     */
🥲🥲🥲🥲🥲

2023-09-14 06:57 UTC, WaiNaat commented on frontend/src/components/@common/ImageButton/index.tsx
> +        accept="image/*"
멋져요 👍

2023-09-14 06:58 UTC, hozzijeong commented on frontend/src/hooks/useOptimizeImage.ts
> +  ph: number;
명시적이군요! 좋습니다

2023-09-14 06:59 UTC, hozzijeong commented on frontend/src/hooks/useOptimizeImage.ts
> +  const [optimizedImage, setOptimizedImage] = useState<Blob>();
분리해보겠습니다!

2023-09-14 07:00 UTC, hozzijeong commented on frontend/src/components/@common/ImageButton/index.tsx
> +        <CirclePlus color={theme.color.primary} />
svg컴포넌트여서 배경 설정이 잘 되지 않아서 최대한 안겹치도록 설정해 봤는데, 외부 태그 하나 놓고 한번 해보겠습니다.

2023-09-14 07:01 UTC, hozzijeong commented on frontend/src/components/@common/ImageButton/hooks/useFileUpload.ts
> +    if (files && files.length > 0) {
조건문을 통과하지 않으면 ref안에 있는 값을 초기화 하는 방식으로 file을 초기화 했습니다. 이미지 자체를 null로 만드는것도 괜찮은 방법이네요!

2023-09-14 07:02 UTC, hozzijeong commented on frontend/src/components/petPlant/PetPlantEditForm/index.tsx
> +              <HiddenLabel>이미지 변경하기</HiddenLabel>
좋습니다!

2023-09-14 10:33 UTC, bassyu reviewed
확인했습니다! 
생소한 개념이 많은데, 궁금한 부분 따로 알려주셔서 감사해요~!
코멘트 남긴 부분만 확인해주세요!

2023-09-14 10:33 UTC, bassyu commented on frontend/src/apis/petPlant.ts
> +const register = (form: FormData) => {
### C

지금은 API가 원하는 타입이 FormData여서 더 구체적인 요구사항이 있으면 좋을 것 같아요!
어떤 타입을 원하는지 param으로 알려주고, 데이터를 어떻게 구성해서 요청 보낼지는 이곳에서 정의해도 좋을 것 같습니다!

```suggestion
const register = (imageBlob, petPlantForm) => {
```

2023-09-14 10:33 UTC, bassyu commented on frontend/src/apis/petPlant.ts
> +    body: form,
이미지 요청은 'Content-Type': 'application/json' 헤더를 주지 않아야 하고, 
body도 form 타입으로 보내는군요!
배워갑니다 👍👍

2023-09-14 10:33 UTC, bassyu commented on frontend/src/components/@common/ImageButton/hooks/useFileUpload.ts
> +      if (firstFile.size > 10000000) {
세심한 예외처리 좋네요! 😄
코드를 줄이는 것보다 이렇게 예외를 처리하는 것이 더 중요한데 저도 리마인드 해야겠습니다..

2023-09-15 01:11 UTC, hozzijeong commented on frontend/src/apis/petPlant.ts
> +const register = (form: FormData) => {
데이터 타입이 헷갈릴거라곤 생각 못해봤네요!! 너무 좋습니다 👍

2023-09-15 03:42 UTC, hozzijeong reviewed
리뷰해 주신 부분들 반영했습니다!

추가적으로 변경된 내용들이 있어서 같이 공유드려요! 한번 확인 해주세요

- [x]  이미지 등록/수정 관련 e2e테스트 추가
- [x] formData관련 타입 선언 및 수정
- [x] 이미지 최적화 유틸 함수로 분리
- [x] 불필요한 상태 제거
- [ ] 식물 수정 페이지에서 텍스트 클릭 시에 이미지 변경

마지막은 이미지 수정 버튼 자체가 라벨이어서 중복 라벨이 되지 않네요... 아이디어가 있으면 조언 부탁드립니다...!

CC.
@bassyu @WaiNaat

2023-09-15 06:28 UTC, WaiNaat requested changes
바꾸신 부분들 확인했어요!
궁금한 것들 코멘트로 남겼습니다~

2023-09-15 06:28 UTC, WaiNaat commented on frontend/src/utils/optimizeImage.ts
> +  };
### C
요 부분이 잘 이해가 안 가는데 promise를 쓰는거랑
```suggestion
    canvasRef.toBlob((blob) => {
      if (blob) resolveCallback(blob);
    }, targetFile.type);
  };
```
이렇게 resolveCallback을 바로 불러주는거랑 차이가 있나요???

2023-09-15 06:53 UTC, bassyu approved these changes
잘 적용해주신 것 확인했습니다!
질문 답변만 확인해주세요~

2023-09-15 06:53 UTC, bassyu commented on frontend/src/apis/petPlant.ts
> +const register = ({ imageData, requestForm }: ImageFormData<NewPetPlantRequest>) => {
야무지네요~!

2023-09-15 06:53 UTC, bassyu commented on frontend/src/components/petPlant/PetPlantEditForm/index.tsx
> +            <ImageButton ref={imgRef} changeCallback={fileUploadHandler} size={16} />
> 마지막은 이미지 수정 버튼 자체가 라벨이어서 중복 라벨이 되지 않네요... 아이디어가 있으면 조언 부탁드립니다...!

라벨 2개에 같은 id를 줘도 잘 동작하는 것 같아요!
다만 여기 Text를 label 태그로 만들어서 useId를 줘야할 것 같은데, 밖으로 빼는 과정이 번거로울 수 있겠네요..

```suggestion
            <Text htmlFor={imageButtonId}>이미지 변경하기</Text>
            <ImageButton htmlId={imageButtonId} ref={imgRef} changeCallback={fileUploadHandler} size={16} />
```

2023-09-15 07:46 UTC, hozzijeong commented on frontend/src/utils/optimizeImage.ts
> +function calculateSize(img: HTMLImageElement, maxWidth: number, maxHeight: number) {
헉! 외부 코드를 참조하다보니...ㅎ 수정하겠습니다~

2023-09-15 07:47 UTC, hozzijeong commented on frontend/src/utils/optimizeImage.ts
> +  return [width, height];
좋습니다~

2023-09-15 07:49 UTC, hozzijeong commented on frontend/src/utils/optimizeImage.ts
> + *  height 압축을 적용할 최대 height
``` typescript
**
 * Assign the project to a list of employees.
 * @param {Object[]} employees - The employees who are responsible for the project.
 * @param {string} employees[].name - The name of an employee.
 * @param {string} employees[].department - The employee's department.
 */
```
(여기)[https://jsdoc.app/tags-param.html]서는 위에 처럼 한다고 합니다!

2023-09-15 07:56 UTC, hozzijeong commented on frontend/src/utils/optimizeImage.ts
> +  };
어ㅏ... 별 차이 없어보이네요.. promise에 너무 꽃혀있었습니다... 햐...수정하겠습니다!

2023-09-15 08:00 UTC, bassyu approved these changes
👍👍👍 확인했습니다!

2023-09-18 07:47 UTC, WaiNaat approved these changes
고생하셨어요 클린!!!!!!!

2023-09-18 07:47 UTC, merged