feat: 모두의 정원 페이지
woowacourse-teams/2023-pium pull request #361
Opened 2023-09-14 12:04 UTC by bassyu

# 🔥 연관 이슈

- close #350 

# 🚀 작업 내용

- 무한 스크롤로 모두의 정원 페이지를 구현했습니다.
- 식물 검색 컴포넌트에서 검색 결과 리스트를 모달로 변경했습니다.

<img width="500" alt="스크린샷 2023-09-14 오후 8 53 46" src="https://github.com/woowacourse-teams/2023-pium/assets/54442420/90440704-55e6-4aab-bc5a-365ac7906d74">

# 💬 리뷰 중점사항

- MSW 구현은 최소한으로 해서 필터링까지 구현하지는 않았는데, 유의해서 테스트 해주세요.
API 요청은 정상적으로 보내집니다!

- 해당 페이지에서만 사용하는 훅이랑 컴포넌트 모두 co-location 했는데 어떤 것 같나요?
트리구조가 한눈에 보여서 좋으면서도 구조가 깊어지는 건 어쩔 수 없어보이네요..
이번 PR 외에도 곳곳에 co-location이 되어있는데, 언제 한번 리팩터링을 해야할 것 같아요.

2023-09-15 01:54 UTC, WaiNaat requested changes
안녕하세요 쵸파
필터 디자인 너무 괜찮은데요? 검색창도 모달형으로 변하면서 깔끔해진 것 같아요
개인적으로는 검색창도 esc로 닫히면 좋겠지만 일단은 희망사항으로 남겨봅니다..

2023-09-15 01:54 UTC, WaiNaat commented on frontend/src/components/search/SearchBox/SearchBox.style.ts
> +export const InputBox = styled.div<{ openBottom: boolean }>`
### R

transient props가 필요해요

2023-09-15 01:54 UTC, WaiNaat commented on frontend/src/pages/GardenPostList/index.tsx
> +            Array(SKELETON_LENGTH).fill(null).map(GardenPostItemSkeleton)}
### C
여기서 key를 달라고 빨간줄을 띄우긴 합니다.. 근데 key가 의미있을지는 저도 모르겠어요

2023-09-15 01:54 UTC, WaiNaat commented on frontend/src/components/search/SearchBox/index.tsx
>      onEnter?.(searchName, searchResults);
### C
여기서도 onEnter 이후에 close해주면 좋을 것 같아요

2023-09-15 01:54 UTC, WaiNaat commented on frontend/src/pages/GardenPostList/components/GardenPostListHeader/index.tsx
> +              <DeleteFilterButton onClick={clear}>✕</DeleteFilterButton>
👍

2023-09-15 02:22 UTC, bassyu commented on frontend/src/components/search/SearchBox/index.tsx
>      onEnter?.(searchName, searchResults);
그러네요 👍

2023-09-15 02:30 UTC, bassyu commented on frontend/src/components/search/SearchBox/SearchBox.style.ts
> +  z-index: ${(props) => (props.openBottom ? props.theme.zIndex.dropdown + 1 : 'none')};
dropdownBackdrop 괜찮은데요?
적용해볼게요~

2023-09-15 06:11 UTC, hozzijeong requested changes
고생하셨습니다 쵸파 멋지게 만들어 주셨네요 👍 

디자인 부분에 대한 피드백은 확인 부탁드립니다!

2023-09-15 06:11 UTC, hozzijeong commented on frontend/src/pages/GardenPostList/components/GardenPostItem/GardenPostItem.styles.ts
>    flex-wrap: wrap;
### C 

TagArea를 좌,우로 넣는게 어떤가요?

2023-09-15 06:56 UTC, bassyu commented on frontend/src/components/search/SearchBox/index.tsx
>                    <Image alt={name} src={image} type="circle" size="40px" />
좋습니다~!

2023-09-15 06:56 UTC, bassyu commented on frontend/src/components/search/SearchBox/index.tsx
> +              &nbsp;&nbsp;&nbsp;
머지하면서 없에보겠습니다~

2023-09-15 06:57 UTC, bassyu commented on frontend/src/components/search/SearchBox/index.tsx
> +              {searchResults?.length ? '찾는 식물이 없으신가요?' : MESSAGE.noSearchResult}
참새의 이전 PR에서 2줄로 바뀌어서 그게 적용될 것 같아요!

2023-09-15 06:59 UTC, bassyu commented on frontend/src/hooks/queries/history/useYearList.ts
> +    gcTime: 0,
현재 gcTime이 없어도 예전의 오류상황이 안나는 상황이라...
gcTime, invalidation 둘다 안해줘도 잘 동작됩니다.
혹시몰라서 우선 냅뒀어요~

2023-09-15 07:00 UTC, bassyu commented on frontend/src/hooks/useDictionaryNavigate.ts
👍👍

2023-09-15 07:01 UTC, bassyu commented on frontend/src/pages/GardenPostList/components/GardenPostItem/GardenPostItemSkeleton.tsx
> +          <SkeletonItem width="45%" height="1.2rem" />
height는 폰트 크기에따라 영향을 받는데 폰트도 rem으로 되어있어서 이렇게 했어요!

2023-09-15 07:08 UTC, bassyu commented on frontend/src/pages/GardenPostList/components/GardenPostListHeader/index.tsx
> +              <DeleteFilterButton onClick={clear}>✕</DeleteFilterButton>
디자인은 적극 반영해보겠습니다!

> 또한, 취소를 했을 때 Search창이 초기화 되어야 된다고 생각하는데 쵸파는 어떻게 생각하시나요?

저도 동의합니다~ 반영할게요!

2023-09-15 07:09 UTC, bassyu commented on frontend/src/pages/GardenPostList/components/GardenPostItem/index.tsx
>        </TagArea>
좋은 것 같아요! height도 고정되겠네요~

2023-09-15 07:12 UTC, bassyu commented on frontend/src/pages/GardenPostList/hooks/useGardenPostList.ts
오.. 실시간 데이터 변경은 생각 안해봤네요!
데스크톱은 새로고침을 하면 되겠지만, 모바일 타겟을 생각해서 
위로 스크롤 하면 새로고침 하는 UX는 어떤가요?

2023-09-15 07:15 UTC, bassyu commented on frontend/src/apis/garden.ts
> +  return fetch(url);
var는 확실하게 지양하는 친구지만, let은 적절하게 써도 괜찮다고 생각했어요~!

2023-09-18 06:24 UTC, hozzijeong requested changes
훨씬 좋아졌네요!! 고생하셨습니다! 코멘트 확인해주세요!!

MSW 필터 적용이 안되어 있으니까 UI 변화 확인이 쉽지 않네요 ㅠ

2023-09-18 06:24 UTC, hozzijeong commented on frontend/src/pages/GardenPostList/index.tsx
> +  };
### R
![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/f2805d0b-adcc-4095-b19e-9edcc7b0ead1)

태그를 지웠을 때 검색창에 있는 검색어가 같이 지워지지 않는데 제거가 되어야 될 것 같습니다.

2023-09-18 06:24 UTC, hozzijeong commented on frontend/src/pages/GardenPostList/GardenPostItem/GardenPostItem.styles.ts
> +  column-gap: 16px;
### C

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/86696d57-663f-4055-b288-6df35f0b43cf)

gap이 너무 큰 것 같은데 쵸파는 어떻게 생각하시나요? 화면이 인프런 같은 경우는 8 ~ 10px로 하고 있더라구요!

2023-09-18 06:24 UTC, hozzijeong commented on frontend/src/pages/GardenPostList/index.tsx
> +
### R

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/6c523f7b-f291-41a0-9ad2-fccf15d65209)

검색어가 검색되었을 때 검색창에 있는 input의 값이 아예 지워지거나 선택한 값으로 바뀌면 좀 더 좋을 것 같아요!

2023-09-18 06:30 UTC, hozzijeong requested changes
추가적인 리뷰 생겨서 새로 합니다...ㅎ

2023-09-18 06:30 UTC, hozzijeong commented on frontend/src/hooks/queries/history/useYearList.ts
> +    gcTime: 0,
둘 다 안해줘도 잘 작동하는 것이라면 빼는게 낫다고 생각합니다! gcTime을 0으로 해버리면 불필요한 쿼리 요청이 계속 갈 수도 있어서요!

2023-09-18 06:30 UTC, hozzijeong commented on frontend/src/pages/GardenPostList/GardenPostListHeader/index.tsx
> +            <DeleteFilterButton onClick={clear}>✕</DeleteFilterButton>
### R

버튼 타입이랑 aria-label 추가..22

2023-09-18 10:37 UTC, WaiNaat requested changes
크 디자인이 훨씬 더 이뻐졌네요 고생하셨습니다 쵸파

2023-09-18 10:37 UTC, WaiNaat commented on frontend/src/components/search/SearchBox/index.tsx
> +  height?: `${number}px`;
### C

이번에 미션하면서 배웠는데 요런건 어떠신가요
```suggestion
  height?:  React.CSSProperties['height'];
```

2023-09-18 10:37 UTC, WaiNaat commented on frontend/src/pages/GardenPostList/GardenPostItem/index.tsx
> +        <TagRow>
### C
css상 이거 두 개를 합쳐도 될 것 같은데 분리하신 이유가 있나요?

2023-09-18 10:37 UTC, WaiNaat commented on frontend/src/components/search/SearchBox/index.tsx
> +  const validOpen = (searchName: string) => {
### C
요거 이름을 한번에 이해 못했는데 좀더 풀어서 쓰는건 어떠신가요

2023-09-18 10:37 UTC, WaiNaat commented on frontend/src/components/search/SearchBox/index.tsx
> +    close();
### R

식물 등록이나 모두의 정원 검색처럼 엔터 처리가 없는 데에서도 엔터 시 모달이 닫히는 현상이 나타나요! 막아야 할 것 같습니다

```suggestion
    if (onEnter) {
      onEnter(searchName, searchResults);
      close();
    }
```

2023-09-18 10:55 UTC, WaiNaat commented on frontend/src/hooks/queries/history/useYearList.ts
> +    gcTime: 0,
알파~베타버전 모든 release note를 확인했는데 관련된 얘기가 아예 없네요.. 애초에 저희만 겪었던 문제기도 해서 확신하기에도 무리가 있긴 해요
일단 "실제 사용자가 불편을 느끼기" 전까지 한번 빼보는 선택지가 있긴 한데 그래도 되는걸까요? 진짜 모르겠습니다

\+) 여담으로 useSuspenseQuery는 두 달도 안 된 따끈따끈한 신기술이었습니다 ([링크](https://github.com/TanStack/query/releases/tag/v5.0.0-alpha.90))

2023-09-19 04:10 UTC, bassyu commented on frontend/src/pages/GardenPostList/GardenPostItem/GardenPostItem.styles.ts
> +  column-gap: 16px;
줄여보고 이쁘면 반영할게요!

2023-09-19 04:10 UTC, bassyu commented on frontend/src/pages/GardenPostList/index.tsx
> +
동의합니다!

2023-09-19 04:12 UTC, bassyu commented on frontend/src/components/search/SearchBox/index.tsx
> +  const validOpen = (searchName: string) => {
좋습니다!

2023-09-19 06:20 UTC, bassyu commented on frontend/src/pages/GardenPostList/GardenPostItem/index.tsx
> +        <TagRow>
이거는 레이아웃이 분리되어야 스크롤이 생기더라구요!

2023-09-19 07:36 UTC, Choi-JJunho commented on frontend/src/pages/GardenPostList/index.tsx
> +            Array(SKELETON_LENGTH).fill(null).map(GardenPostItemSkeleton)}
저도 모르겠네요 😅

2023-09-19 07:39 UTC, Choi-JJunho commented on frontend/src/components/search/SearchBox/index.tsx
> +              &nbsp;&nbsp;&nbsp;
### R

머지하면서 없`애`보겠습니다
로 정정 부탁드립니다.

2023-09-19 07:39 UTC, Choi-JJunho commented on frontend/src/hooks/queries/history/useYearList.ts
> +    gcTime: 0,
너무 따끈따끈해서 데일뻔했네요 🔥

2023-09-19 11:54 UTC, bassyu commented
페이지는 아래처럼 변경됐습니다~!

| 사전 식물 | 모두의 정원 |
| --- | --- |
| <img width="300" alt="스크린샷 2023-09-19 오후 8 49 46" src="https://github.com/woowacourse-teams/2023-pium/assets/54442420/4272857e-83ed-4477-a2cf-d82ad25cc037"> | <img width="300" alt="스크린샷 2023-09-19 오후 8 49 58" src="https://github.com/woowacourse-teams/2023-pium/assets/54442420/378adf49-0070-4879-aa81-bc955b05be09"> |

2023-09-19 12:10 UTC, WaiNaat requested changes
👍

2023-09-19 12:10 UTC, WaiNaat commented on frontend/src/pages/GardenPostList/index.tsx
> +      </FixedButtonArea>
### R
요기에 aria-label이랑 type button 넣어주세용

2023-09-19 12:10 UTC, WaiNaat commented on frontend/src/pages/PetPlantRegister/Form/Form.style.ts
> +  backdrop-filter: blur(4px);
😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍

2023-09-19 12:10 UTC, WaiNaat commented on frontend/src/components/search/SearchBox/index.tsx
>      close();
https://github.com/woowacourse-teams/2023-pium/pull/361#discussion_r1328535101

엔터처리 관련해서 반영 부탁드려요

2023-09-19 12:28 UTC, bassyu commented on frontend/src/pages/GardenPostList/index.tsx
> +      </FixedButtonArea>
👍 반영했습니다!

2023-09-19 12:42 UTC, hozzijeong requested changes
고생하셨습니다~ 코멘트 확인해주세요!! (거의 다와가는군요!)

2023-09-19 12:42 UTC, hozzijeong commented on frontend/src/mocks/handlers/gardenHandlers.ts
> +    return res(ctx.delay(200), ctx.status(201));
💯💯💯

2023-09-19 12:42 UTC, hozzijeong commented on frontend/src/pages/GardenPostList/index.tsx
> +        <FixedButton onClick={goGardenRegisterPick}>
### R 

button type aria-label 추가해주세요!

2023-09-19 12:42 UTC, hozzijeong commented on frontend/src/pages/DictionaryPlantDetail/index.tsx
>      </>
### C

이 버튼이 footer는 아닌것 같은데 어떻게 생각하시나요?

2023-09-19 12:48 UTC, bassyu commented on frontend/src/pages/DictionaryPlantDetail/index.tsx
>      </>
버튼은 footer가 아니지만 영역은 footer라고 생각했습니다~

2023-09-20 00:50 UTC, hozzijeong commented on frontend/src/pages/DictionaryPlantDetail/index.tsx
>      </>
영역은 Footer라고 하는게 좀 주관적이라고 생각이 듭니다. footer라는 시맨틱 태그가 가지는 의미가 있는데, 여기서 사용되는 button의 역할과 footer의 역할이 관련 없다고 생각이 드는데 쵸파 생각은 어떤가요?

2023-09-20 00:57 UTC, bassyu commented on frontend/src/pages/DictionaryPlantDetail/index.tsx
>      </>
> footer라는 시맨틱 태그가 가지는 의미

이거는 몰랐네요! 수정하겠습니다~

2023-09-20 03:37 UTC, hozzijeong approved these changes
멋져요

2023-09-20 03:37 UTC, merged