feat : 사전 식물 등록 요청 기능
woowacourse-teams/2023-pium pull request #363
Opened 2023-09-15 05:21 UTC by rawfishthelgh

# 🔥 연관 이슈

- close #345 

# 🚀 작업 내용
사전 식물 등록을 요청하고, 이를 조회 및 삭제하는 기능입니다!

# 💬 리뷰 중점사항
 로직 특성상 `Null` 이 들어가게 되는 코드들이 많습니다.
그만큼 예외가 발생할 확률도 존재하게 되니 null을 사용하면서 발생할 수 있는 가능성을 고려하면서 리뷰해주시면 감사하겠습니다!

2023-09-16 06:24 UTC, Kim0914 requested changes
마드 안녕하세요 ㅎㅎ 그레이입니당

기능 구현 야무지게 잘 해주셨네요 !
컨벤션과 관련한 부분 코멘트 몇개 남겼어요.
확인부탁드려요 ~

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/admin/controller/RegistrationController.java
> +            @PathVariable @Positive(message = "등록 요청 ID는 1이상의 값이어야 합니다.") Long id) {
### R

```suggestion
            @PathVariable @Positive(message = "삭제 요청 ID는 1이상의 값이어야 합니다.") Long id) {
```

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/admin/domain/Registration.java
> +        this.imageUrl = imageUrl;
### A

클래스 단에 `@Builder` 어노테이션을 붙이지 않고 생성자에 붙여주신 이유가 궁금합니다 ㅎㅎ

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/admin/mapper/RegistrationMapper.java
> +
### R

공백 !

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/admin/service/RegistrationService.java
> +            throw new AuthorizationException();
### C

예외 메세지도 추가하면 좋을 것 같은데, 예외 메시지를 따로 명시하지 않은 이유가 궁금해요 !

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/admin/service/RegistrationService.java
> +    }
### C

바로 리턴해줘도 될 것 같아요 !

```java
return DataResponse.<List<RegistrationResponse>>builder()
                .data(registrationResponses)
                .build();
```

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/admin/service/RegistrationService.java
> +            throw new AuthorizationException();
### C

여기도 예외메시지 한번 생각해주세용 !

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
> +        ).isInstanceOf(IllegalArgumentException.class).hasMessage("이름과 이미지 중 하나는 존재해야 합니다");
### A

사소하지만 줄바꿈을 이렇게 가져가는건 어때보이나요? 🙃

```java
assertThatThrownBy(() -> registrationService.save(null, null))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("이름과 이미지 중 하나는 존재해야 합니다");
```

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
> +        assertThat(responses.size()).isEqualTo(2);
### A

줄바꿈 없이 붙여주는게 가독성이 더 좋을 것 같아요 !(then의 의미가 뚜렷하도록 ㅎㅎ)

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
> +        assertThat(deleted).isEmpty();
### A

줄바꿈 없이 붙여주는게 가독성이 더 좋을 것 같아요 !(then의 의미가 뚜렷하도록 ㅎㅎ)

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
> +        ).isInstanceOf(AuthorizationException.class);
`ditto`

2023-09-16 06:24 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
> +    }
`ditto`

2023-09-16 09:37 UTC, yeonkkk requested changes
안녕하세요 하마드! 조이입니다 ~

빠르게 구현해주셨네요 ~ 코드도 넘 깔끔해서 리뷰하기도 편했습니다 ㅎ
코멘트 조금 남겨두었으니 확인 부탁드려요!

고생하셨습니다~

2023-09-16 09:37 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/admin/controller/RegistrationControllerTest.java
> +
### R
요기 공백이 있네용

2023-09-16 09:37 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/admin/controller/RegistrationControllerTest.java
> +            responses.add(registration);
### A
이렇게 작성할수도 있을 것 같아요!

```suggestion
            List<RegistrationResponse> responses = List.of(registration);
```

2023-09-16 09:37 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
> +    private AmazonS3 amazonS3;
### R
개행을 넣어주면 읽기 더 좋을 것 같아요!

```suggestion
    @Autowired
    private RegistrationService registrationService;
    
    @Autowired
    private RegistrationRepository registrationRepository;
    
    @MockBean
    private AmazonS3 amazonS3;
```

2023-09-16 09:37 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
> +    void 식물_요청의_이름과_이미지가_모두_들어오면_함께_저장한다() {
### C

다른 service test들 이랑 통일되게 `식물_요청의_이름과_이미지가_모두_들어오면_함께_저장()` 로 이름을 변경해보면 어떨까요?

2023-09-16 12:11 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/admin/domain/Registration.java
> +        this.imageUrl = imageUrl;
Entity id 값의 수정을 방지하기 위함입니다!

2023-09-16 12:14 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/admin/service/RegistrationService.java
> +            throw new AuthorizationException();
@Kim0914 권한 정보를 필요로 하는 동작인 만큼,
요청이 왜 실패하는지를 드러내면 안 될 것 같은 느낌이라 넣지 않았습니다!
그런데 식물 등록 요청 정보가 과연 크리티컬한가? 라고 생각해 보면 그렇지 않은 것 같네요!
그래도 조금 추상적으로 "허가되지 않은 동작입니다"라는 메세지를 추가해 봤습니다.

2023-09-16 12:16 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/admin/service/RegistrationService.java
> +            throw new AuthorizationException();
@yeonkkk checkAdmin 메소드로 분리했습니다!

2023-09-16 12:31 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/admin/service/RegistrationServiceTest.java
> +        ).isInstanceOf(AuthorizationException.class);
예외 메세지 추가에 대한 내용인가요???

2023-09-16 12:33 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/admin/controller/RegistrationController.java
> +        return ResponseEntity.created(URI.create("/dictionary-registrations")).build();
`새로 생성된 자원에 대한 정보 위치`를 의미하는 것이 정확합니다!
현재 관리자 페이지에서 각 등록 요청별 상세 조회가 존재하지 않고,
모든 등록 요청을 전체조회에서 처리하고 있습니다.
따라서 새로 생성된 자원의 위치는 `/dictionary-registrations` 에 해당하기에 해당 uri로 찾을 수 있도록 로케이션을 명시했습니다!

2023-09-16 12:38 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/admin/service/RegistrationService.java
> +            registrationRepository.save(registration);
해당 검증 추가했습니다! 이미지 정보가 Null 일 경우에만 검증을 수행하는게 올바르게 보이네요!
(이름이 null이나 blank여도 이미지 정보가 존재하면 의미 있는 요청이니)

2023-09-16 12:46 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/admin/controller/RegistrationControllerTest.java
> +            responses.add(registration);
더 깔끔하네요!

2023-09-17 06:18 UTC, yeonkkk approved these changes
하마드! 
리뷰 반영해주신거 확인해서 이만 approve 하겠습니다.  
고생하셨습니다~🫡

2023-09-17 08:02 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/admin/domain/Registration.java
> +public class Registration extends BaseEntity {
그렇네용 !

이전에는 패키지가 나뉘어져 있지 않았었는데 계층을 추가했기 때문에 마드가 해주신 것 처럼 유지해도 좋겠네요 ㅎㅎ

2023-09-17 08:04 UTC, Kim0914 approved these changes
리뷰 반영 확인했습니다 ㅎㅎ

고생많으셨어요 🙇🏻

2023-09-17 08:04 UTC, merged