feat: 모두의 정원 구현
woowacourse-teams/2023-pium pull request #365
Opened 2023-09-17 09:38 UTC by yeonkkk

# 🔥 연관 이슈

- close #339 

# 🚀 작업 내용
모두의 정원 게시글 등록 및 조회 기능 구현했습니다.  

# 💬 리뷰 중점사항
- 놓치거나 부족한 테스트가 없는지 확인 부탁드립니다!!

2023-09-17 15:31 UTC, Choi-JJunho requested changes
안녕하세요 조이~ 리뷰어 주노입니다 💪
테스트 정말 꼼꼼하게 잘 짜주셨네요 🥹

몇가지 코멘트 남겼으니 확인 부탁드려요~

2023-09-17 15:31 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/GardenController.java
> +            @RequestBody @Valid GardenCreateRequest request,
### C

문든 생각난 내용인데 다른 Controller 클래스에서는 클래스 레벨에 `@Validated`를 붙이는 방식으로 사용하고있었네요
`@Valid`와 중복 사용을 하는 경우도 보이는데 통일성을 위해 다른 컨트롤러들의 `@Validated`를 제거하는것을 부탁드려도될까요?? 🙏

2023-09-17 15:31 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/domain/Garden.java
> +import jakarta.validation.constraints.*;
### R

import 관련 컨벤션 확인 부탁드릴게요!
[관련 Wiki](https://github.com/woowacourse-teams/2023-pium/wiki/%5BBE%5D-%EC%9D%B8%ED%85%94%EB%A6%AC%EC%A0%9C%EC%9D%B4-%ED%99%98%EA%B2%BD%EC%84%A4%EC%A0%95#import-%EC%84%A4%EC%A0%95)

2023-09-17 15:31 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/repository/GardenCustomRepositoryImpl.java
> +                .fetch();
### R

Garden을 조회하면서 Member 혹은 DictionaryPlant를 LazyLoad 하면서 조회 쿼리가 여러번 나갈 것 같아요!
1번 조회에 2회 이상의 쿼리가 발생할 여지가 있으니 다음과 같이 fetchJoin을 하면 어떨까요?

```suggestion
                .where(validateDictionaryPlantIds(dictionaryPlantIds))
                .orderBy(new OrderSpecifier<>(Order.DESC, garden.createdAt))
                .leftJoin(garden.dictionaryPlant, dictionaryPlant) // QDictionaryPlant.dictionaryPlant
                .fetchJoin()
                .offset(pageable.getOffset())
                .limit(pageable.getPageSize())
                .fetch();
```

> 참고 Comment
- https://github.com/woowacourse-teams/2023-pium/issues/347#issuecomment-1719043118

### join과 fetchJoin 간략 설명
join: 쿼리(JPQL)에서 조회하는 주체만 영속화된다.
fetchJoin: 연관된 Entity도 영속화된다.

2023-09-17 15:31 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/dto/SingleGardenResponse.java
> +}
### R

![image](https://github.com/woowacourse-teams/2023-pium/assets/49794401/00c6c6d3-ad44-4754-9339-6309f3580b50)

No newline at end of file이 뜨네요! 설정 확인 부탁드려요~

[관련 Wiki](https://github.com/woowacourse-teams/2023-pium/wiki/%5BBE%5D-%EC%9D%B8%ED%85%94%EB%A6%AC%EC%A0%9C%EC%9D%B4-%ED%99%98%EA%B2%BD%EC%84%A4%EC%A0%95#%ED%8C%8C%EC%9D%BC-%EB%A7%88%EC%A7%80%EB%A7%89-%EA%B0%9C%ED%96%89-%EC%84%A4%EC%A0%95)

2023-09-17 15:31 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/controller/GardenControllerTest.java
> +        }
### R

RestDocs 관련 코드 추가부탁드려요!

[참고자료](https://blog.pium.life/restdocs-start/)

2023-09-17 15:31 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/controller/GardenControllerTest.java
> +        }
### R
ditto

> RestDocs 관련 코드 추가부탁드려요!
[참고자료](https://blog.pium.life/restdocs-start/)

2023-09-18 08:08 UTC, yeonkkk reviewed
@Choi-JJunho 주노! 
남겨주신 리뷰 반영했습니다 ㅎㅎ
확인 부탁드려요!🫡

2023-09-18 08:09 UTC, rawfishthelgh approved these changes
조이 구현하느라 고생하셨습니다~!
저는 크게 변경할 부분은 없어 보이고, 공백 하나랑 의견 하나만 묻는 부분이 있어서 approve 해도 될 것 같아요!

2023-09-18 08:12 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/repository/GardenCustomRepositoryImpl.java
> +    }
찾아보니

2023-09-18 09:20 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/GardenController.java
> +            @RequestBody @Valid GardenCreateRequest request,
헉 맞네요... 제가 저걸 미처 확인 못했네요 😅
일깨워주셔서 감사합니다!

2023-09-18 10:28 UTC, Choi-JJunho approved these changes
반영해주신 사항 확인했습니다~
구현 고생하셨습니다  👍

2023-09-18 10:28 UTC, merged