feat: 반려 식물 이미지 수정 기능
woowacourse-teams/2023-pium pull request #380
Opened 2023-09-19 16:05 UTC by yeonkkk

# 🔥 연관 이슈

- close #373 

# 🚀 작업 내용
반려 식물 수정 시 이미지 수정도 가능하도록 추가 구현했습니다.

# 💬 리뷰 중점사항
기존 테스트 잘못 수정했는지, 부족한 테스트 없는지 한번씩 확인해주시면 감사하겠습니다!

2023-09-19 16:21 UTC, Choi-JJunho requested changes
조이~ 엄청 빠르게 작업해주셨네요!!

몇가지 확인할 내용에 대해 코멘트 남겼습니다~

2023-09-19 16:21 UTC, Choi-JJunho commented on backend/pium/src/docs/asciidoc/petPlant.adoc
> +include::{snippets}/petPlant/update/httpie-request.adoc[]
### A
다른 문서들은 `http-request.adoc`를 사용하는데 특별히 httpie문서로 선택한 이유가 있나요?

2023-09-19 16:21 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +            throw new IllegalArgumentException("반려 식물 이미지 URL은 빈 값이 될 수 없습니다. date: null");
오타가 있네요~
```suggestion
            throw new IllegalArgumentException("반려 식물 이미지 URL은 빈 값이 될 수 없습니다. imageUrl: null");
```

2023-09-19 16:21 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        String imageUrl = saveImageIfExists(image, petPlant.getImageUrl());
### A
이미지 수정 시 기존 이미지는 삭제 안하나요?

2023-09-19 16:21 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/acceptance/PetPlantApiTest.java
> +            MultiPartSpecification data = getMultiPartSpecification(request);
### A

data 대신 multipartData와 같은 네이밍은 어떤가요?

2023-09-19 16:21 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +                    .hasMessageContaining("반려 식물 이미지 URL은 빈 값이 될 수 없습니다. date: null");
### R

위에 오타가 있던 부분과 연관되어있네요~

```suggestion
                    .hasMessageContaining("반려 식물 이미지 URL은 빈 값이 될 수 없습니다. imageUrl: null");
```

2023-09-19 16:21 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +                    "통풍이 잘 됨", 10, LocalDate.of(2022, 7, 1), LocalDate.of(2022, 7, 8), "imageUrl");
### C

추후 imageUrl에 대한 검증이 추가될 것을 우려하여 테스트의 url 형태는 https://testimage.com 과 같은 형태로 작성하는건 어떨까요?

> 참고 PR Comment
- https://github.com/woowacourse-teams/2023-pium/pull/67#discussion_r1266072592

2023-09-20 00:46 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +        if (imageUrl == null) {
### C

`imageUrl == null || imageUrl.isBlank()`면 좀 더 꼼꼼할 것 같아요 !

2023-09-20 01:39 UTC, yeonkkk reviewed
주노, 그레이 리뷰 감사해요 ~~
 피드백 반영했습니다!

2023-09-20 01:39 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +            throw new IllegalArgumentException("반려 식물 이미지 URL은 빈 값이 될 수 없습니다. date: null");
수정했습니다!

2023-09-20 01:39 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +                    "통풍이 잘 됨", 10, LocalDate.of(2022, 7, 1), LocalDate.of(2022, 7, 8), "imageUrl");
좋은 것 같네요! 수정하겠습니다.

2023-09-20 01:39 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/domain/PetPlantTest.java
> +                    .hasMessageContaining("반려 식물 이미지 URL은 빈 값이 될 수 없습니다. date: null");
수정하겠습니다~

2023-09-20 03:41 UTC, rawfishthelgh approved these changes
조이 고생하셨습니다~!
저는 주노가 리뷰한 부분만 반영해주면 괜찮은 것 같아서 approve 하도록 할게요!

2023-09-20 04:30 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        String imageUrl = saveImageIfExists(image, petPlant.getImageUrl());
새로운 이미지가 들어오면 이미지 이름도 변경될 것 같아요 !

그러면 기존에 존재하는(교체가 되어 삭제되는) 사진을 별도로 삭제해야 하지 않을까용?!

2023-09-20 04:41 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        String imageUrl = saveImageIfExists(image, petPlant.getImageUrl());
엥 저 왜 새로운 이미지랑 이전 이미지 이름이 같다고 생각했죠..? 수정하겠습니다^^;;🤔

2023-09-20 06:59 UTC, Choi-JJunho approved these changes
반영해주신 내용 확인했습니다~
고생하셨습니다

2023-09-20 06:59 UTC, merged