feat: PWA 기본 조건 설정
woowacourse-teams/2023-pium pull request #411
Opened 2023-09-28 12:45 UTC by hozzijeong

# 🔥 연관 이슈

- close #404 

# 🚀 작업 내용
- [x] manifest.json 작성
- [x] serviceWorker 작성
- [x] icons 수정

# 💬 리뷰 중점사항

안녕하세요? 

pwa를 작성하기 위한 기본 조건들을 만족해서 일단은 올립니다. localhost에서 배포를 해보고 싶은데, https가 필수여서 이게 쉽지 않네요. [ngrok](https://dashboard.ngrok.com/get-started/setup)이라는 서비스를 통해서 localhost를 외부에서 접근하도록 url을 만들어서 테스트 해보려 했는데 기존 api의 host 주소가 달라서 구조상 불가능 한 것 같더라구요... (실행을 할때마다 url이 바뀌어서 미리 저장을 해놓지도 못합니다) 따라서 dev서버에 올려보고 pwa의 조건이 충족되는지 우선적으로 확인해 보려고 합니다. 

### 참고 자료
https://www.pwabuilder.com/
https://web.dev/learn/pwa/progressive-web-apps/

2023-09-28 13:16 UTC, WaiNaat requested changes
신성한 연휴 첫날에도 고생하셨습니다 클린!
이제야 알아챈 건데 페이지 설명에서 단어 하나가 빠져서 그 부분 수정 요청 남겨요

2023-09-28 13:16 UTC, WaiNaat commented on frontend/src/index.tsx
> +// }
### C

msw부분이 주석처리된 이유가 있나요??

2023-09-28 13:16 UTC, WaiNaat commented on frontend/public/serviceWorker.js
> +      // 캐시로 저장할 파일을 지정. 어떤 파일을 넣을지는 차후 얘기해 보며 좋을 듯.
👍

2023-09-28 13:16 UTC, WaiNaat commented on frontend/public/index.html
>        content="피움은 여러분의 관리 경험을 기록할 수 있도록 도와주고 각자에게 알맞은 관리법을 빠르게 찾도록 도와주고 있어요."
여기도 빠졌었네요..

2023-09-29 11:02 UTC, bassyu approved these changes
연휴에도 고생하셨습니다! PWA를 위해 뭐가 필요한지 모르겠어서 일단 Approve할게요!

+) 피움 앱 아이콘으로 `피움` 로고 쓰는건 어떤지 제안해봅니다..!

2023-09-29 14:27 UTC, hozzijeong commented on frontend/public/serviceWorker.js
> +this.addEventListener('fetch', (event) => {
PWA에서 오프라인인 경우에 캐시되어 있는 데이터를 가져오는 역할을 합니다!

2023-09-29 14:29 UTC, hozzijeong commented on frontend/public/assets/manifest.json
> +  "description": "피움은 여러분의 관리 경험을 기록할 수 있도록 도와주고 각자에게 알맞은 관리법을 빠르게 찾도록 도와주고 있어요.",
헉!! 그대로 복붙을 했었는데.... 수정하겠습니다

2023-09-29 14:29 UTC, hozzijeong commented on frontend/public/assets/manifest.json
> +  "categories": ["lifestyle", "personalization"]
확실히 괜찮은 것 같네요! 감사합니다 참새

2023-09-29 14:29 UTC, hozzijeong commented on frontend/src/index.tsx
> +// }
깜빡했습니다... 수정하게씃빈다

2023-09-30 00:40 UTC, WaiNaat approved these changes
멋있어요

2023-09-30 00:41 UTC, merged

2023-09-30 01:39 UTC, bassyu commented on frontend/src/swDev.ts
아하! 좋아요 코드 양이 많지 않아서 index.tsx에 들어가도 괜찮아보이네요~