feat: 토스트 고도화
woowacourse-teams/2023-pium pull request #412
Opened 2023-09-30 02:55 UTC by bassyu

# 🔥 연관 이슈

- close #409

# 🚀 작업 내용

로그인이 필요한 페이지에 이동했을 때 로그인 페이지로 바로 이동하면 사용자의 자유를 제한하는 느낌이고,
그렇다고 토스트만 사용해서 알려주는 것은 가이드가 부족하다고 생각했습니다.

그래서 토스트에 버튼을 추가해서 사용자에게 가이드와 선택지를 제공하고, 
토스트가 언제 사라지는지 알려줌으로서 불편함을 덜어내고자 했습니다.

디자인은 [이곳](https://spectrum.adobe.com/page/toast/)을 많이 참고했습니다! (특히 버튼의 위치)

![토스트고도화](https://github.com/woowacourse-teams/2023-pium/assets/54442420/cbe1b17d-ffc2-49a1-b483-b87d999d756e)

# 💬 리뷰 중점사항

토스트를 사용하는 곳이 너무 많아서 기능 추가와는 또 다른 느낌으로 쉽지 않았네요..
사용처에서 버튼이 있는지 없는지, 있다면 내용과 액션은 무엇인지 정해줘야해서 addToast의 params가 매우 많아졌습니다.
(토스트에 버튼이 추가돼서 `실행 취소`기능도 가능할 것 같아요.)

- 토스트가 올라가지 않고 겹치도록 했는데 어떤가요? 
- 토스트를 사용할 곳 추가 또는 제목이나 메세지 수정도 추천해주시면 감사하겠습니다!
- 같은 내용의 토스트라면 하나의 버튼이 하나의 토스트만 올라가도록 하는 건 어떤가요?

2023-09-30 05:05 UTC, WaiNaat requested changes
안녕하세요 쵸파~ 연휴에도 빠르게 작업을 해 주셨군요!

### 디자인

은 이쁘고 좋아요 👍 

#### 스토리북

이 작동을 안해요 😭

#### 같은 내용의 토스트 관련

저는 지금처럼 사용자 행동과 그에 따른 결과가 일대일 대응되는 방식이 더 낫다고 생각합니다

#### 겹치기 관련

여러 토스트가 겹쳤을 때 먼저 등록된 뒤쪽 친구들이 먼저 사라지는 건 의도한 결과인가요? 만약 그렇다면 그렇게 의도하신 이유도 궁금해요

#### 멘트 관련

[이걸](https://spectrum.adobe.com/page/toast/#Use-an-instructive-tone) 보고 생각을 해 봤는데 param도 줄일 겸 제목을 아예 없애는건 어떠신가요??

\+ 이해는 안 되지만 [단일 문장일 경우 마침표를 쓰지 않는 것](https://spectrum.adobe.com/page/toast/#Write-in-sentence-case-with-no-period)도 추천하긴 하네요

2023-10-01 05:21 UTC, hozzijeong requested changes
쵸파 고생하셨습니다~ 멋있네요 ㅎ

nav 바에서 로그인 페이지로 이동하는게 쵸파 생각에 별로(?)라고 생각을 하셔서 button으로 구현을 하셨는데, 그 이유에 대해서 좀 더 자세히 듣고 싶네요!!

디자인도 이쁘게 잘 해주셨네요 :) 다만 알림 글씨가 너무 작아서 잘 안보입니다... 폰트 크기를 좀 키워 보는 것은 어떤가요?

2023-10-01 05:21 UTC, hozzijeong commented on frontend/src/components/@common/Toast/Toast.style.ts
> +  font-size: 1.2rem;
### C

개인적인 의견인데 글씨가 너무 작은것 같습니다... 1.6 정도까지 키우는 것은 어떤가요?

2023-10-02 04:30 UTC, bassyu commented on frontend/src/components/@common/Navbar/index.tsx
> +          <NavButton key={index} onClick={needLoggedIn && !isLoggedIn ? askLogin : goPath}>
클린말처럼 link, 토스트 버튼 2개의 경우가 있는지라 버튼으로 일단 통일했는데요,
해결하려면 map 으로 돌리는게 아니라 그냥 상황에 따라서 작성하면 될 것 같아요

2023-10-02 04:34 UTC, bassyu commented on frontend/src/components/@common/Toast/Toast.style.ts
> +  font-size: 1.2rem;
참새 코멘트도 참고해서 title도 합칠겸 키워보겠습니다~

2023-10-02 06:12 UTC, bassyu commented
리뷰 반영 해봤습니다! 
특히 Navbar는 반복문을 돌면서 구현 했었는데, 중복보다 분기가 더 커지는 시점이라고 판단돼서 반복문을 뺐습니다.

> 여러 토스트가 겹쳤을 때 먼저 등록된 뒤쪽 친구들이 먼저 사라지는 건 의도한 결과인가요? 만약 그렇다면 그렇게 의도하신 이유도 궁금해요

직접 닫지 않는 이상 같은 내용의 토스트 여러개가 오래 떠있으면 사용자가 불편할 것 같아서 이렇게 했습니다.
클릭과 반응을 1대1로 하면서, 토스트가 빨리 사라지려면 새로운 토스트 추가 대신 동일한 토스트의 시간 초기화는 어떨까요?

2023-10-02 07:47 UTC, hozzijeong commented on frontend/src/components/@common/Navbar/index.tsx
> +    const active = path === location.pathname;
### C

NavItem에 사용되는 icon들만 따로 선언하는 것은 어떤가요??

2023-10-02 08:12 UTC, bassyu commented on frontend/src/components/@common/Navbar/index.tsx
Navbar를 만들 때 토스트만 보여줄지 바로 이동시켜줄지 논의 했었는데요, 그 중간 지점이라고 생각했습니다!
사용자마다 다르겠지만 로그인 페이지로 바로 이동하길 원하지 않을 수도 있다고 생각했어요

2023-10-02 08:45 UTC, bassyu commented on frontend/src/components/@common/Navbar/index.tsx
> +    const active = path === location.pathname;
혹시 타입 말씀하시는 건가여?

2023-10-02 08:46 UTC, WaiNaat reviewed
스토리북도 잘 되네요 멋져요

> 직접 닫지 않는 이상 같은 내용의 토스트 여러개가 오래 떠있으면 사용자가 부담될 것 같아서 이렇게 했습니다~

여러 식물에 대한 물주기나 미루기처럼 다른 내용의 토스트가 나오는 경우까지 고려된 사항인지 궁금해요. 저는 이런 경우 때문에 이전 토스트가 끝나고 다음 토스트가 나와야 한다고 생각했거든요

> 반응을 1대1로 하면서 부담을 덜어내기 위해, 같은 버튼을 클릭했을 때 새로운 토스트 추가 대신 동일한 토스트의 시간 초기화는 어떨까요?

👍

2023-10-02 08:47 UTC, hozzijeong commented on frontend/src/components/@common/Navbar/index.tsx
> +    const active = path === location.pathname;
넵넵!

2023-10-02 10:09 UTC, bassyu commented on frontend/src/components/@common/Navbar/index.tsx
> +    const active = path === location.pathname;
음 아이콘 id와 label을 묶어줄 수 있으면 좋겠는데 지금은 그게 안돼서 애매하네요..

2023-10-02 13:03 UTC, bassyu commented
> 여러 식물에 대한 물주기나 미루기처럼 다른 내용의 토스트가 나오는 경우까지 고려된 사항인지 궁금해요. 저는 이런 경우 때문에 이전 토스트가 끝나고 다음 토스트가 나와야 한다고 생각했거든요

이전 토스트가 가려지는 것은 치명적일 수 있겠네요! 
앞의 토스트가 끝나야 다음 토스트의 시간이 가도록 변경했습니다~
이것도 생각보다 쉽지 않네요..


https://github.com/woowacourse-teams/2023-pium/assets/54442420/221c28d0-a1cf-41a3-839e-b04f106358e5

2023-10-02 13:34 UTC, hozzijeong approved these changes
멋져요

2023-10-03 12:30 UTC, WaiNaat approved these changes
멋있어요

2023-10-03 12:30 UTC, merged