feat: 반려 식물 등록 기능 구현
woowacourse-teams/2023-pium pull request #42
Opened 2023-07-13 02:48 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #17 

# 🚀 작업 내용

- [ ] 반려식물 등록 기능

# 💬 리뷰 중점사항

잘부탁드립니다 (업데이트 예정)

2023-07-14 06:18 UTC, Kim0914 commented
Jenkins 연동 이슈로 인한 Close

2023-07-14 06:26 UTC, yeonkkk commented
Jenkins 연동 이슈로 인한 Close 2

2023-07-14 06:31 UTC, yeonkkk commented
Jenkins 연동 이슈로 인한 Close 3

2023-07-16 07:46 UTC, yeonkkk requested changes
안녕하세요 주노! 🌱

코드를 너무 잘 작성해주셔서 리뷰하기가 너무 수월했던 것 같습니다👍  
코멘트 조금 남겨두었으니 참고 부탁드려요!

2023-07-16 07:46 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/controller/dto/PetPlantRequest.java
> +    private LocalDate lastWaterDate;
### C

```suggestion
    @NotNull
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate birthDate;

    @NotNull
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private LocalDate lastWaterDate;
```

`@NotBlank`는 `String` 을 검증하는 애너테이션이라고 알고 있는데, `@NotNull`로 변경해보면 어떨까요? 🙂

2023-07-16 07:46 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
> +    public ResponseEntity<Void> create(PetPlantRequest request, Member member) {
### R

```suggestion
    public ResponseEntity<Void> create(@Valid PetPlantRequest request, Member member) {
```

DTO에 작성한 검증 로직이 적용되려면 `@Valid`를 붙여줘야 할 것 같습니다.

2023-07-16 12:57 UTC, rawfishthelgh requested changes
안녕하세요 주노ㅎㅎ 고생하셨습니다.
몇 가지 사항에 대해서 리뷰 달아놨어요. 
큰 변경 요청사항은 없으니 주노에 판단에 의해 잘 결정해주세요!

2023-07-16 12:57 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/config/JpaAuditingConfig.java
> +}
### A
Application에 선언하지 않는 이유가 있을까요?(순수한 궁금증입니다)

2023-07-16 12:57 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
> +        return ResponseEntity.created(URI.create("/")).build();
### R
201 상태 코드로 응답할 때 Location 헤더는 생성된 리소스의 위치를 나타낸다고 합니다!([참고](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/201)).

저희가 식물 개별 조회 api를 `/pet-plants/{id}` 로 지정해놓았기에 조이의 의견처럼 해당 리소스 위치를 location에 명시하는게 더 옳다고 생각이 드네요!

2023-07-16 12:57 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/controller/dto/PetPlantRequest.java
> +public class PetPlantRequest {
### A
@AllArgsConstructor 는 필드 변수순서의 영향 문제 등으로 최대한 지양하는 것으로 알고 있는데, 사용하신 이유가 있을까요?

2023-07-16 12:57 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +                .orElseThrow(() -> new NoSuchElementException("사전 식물이 존재하지 않습니다. id : " + request.getDictionaryPlantId()));
### A
반영 요청사항은 아닌데, 위와 같은 상황에 대해서 다른 팀원들도 NoSuchElementException을 사용하기로 정해지면 좋겠네요 👍

2023-07-16 13:10 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/fixture/MemberFixture.java
> +    public static Member 주노 = Member.builder()
### A

라인 공백 😙

2023-07-16 14:57 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
> +    @PostMapping("/pet-plant")
반영했습니다 👍

2023-07-16 14:57 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
> +        return ResponseEntity.created(URI.create("/")).build();
작성하면서 미처 생각 못한부분이였네요  😂
반영했습니다 👍

2023-07-16 14:58 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/dto/PetPlantRequest.java
> +    private LocalDate lastWaterDate;
반영했습니다 👍

2023-07-16 14:58 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
> +    public ResponseEntity<Void> create(PetPlantRequest request, Member member) {
이걸 빼먹었네요... 반영했습니다 👍

2023-07-16 15:03 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/config/JpaAuditingConfig.java
> +}
Application에 선언할 경우 슬라이스테스트 작성간 `BeanCreationException`문제가 발생하게 됩니다.

대략적인 이유는 다음과 같습니다.
- Test를 수행할 때 Application 클래스를 참조한다.
- 이때 `@EnableJpaAuditing`이 같이 붙어서 동작한다.
- `@EnableJpaAuditing`이 적용되기 위해 Jpa로 등록된 Bean을 탐색하고 없다면 `BeanCreationException`이 발생한다.

위와같은 상황 때문에 슬라이스 테스트를 수행하는 데 문제가 발생했습니다.
때문에 `@EnableJpaAuditing`과 관련된 설정을 분리해야할 필요성을 느껴 위와같이 작성했습니다

[관련 글](https://everydayidid.tistory.com/77)로 가볍게 정리해뒀습니다.
[다른 글](https://velog.io/@suujeen/Error-creating-bean-with-name-jpaAuditingHandler)을 참고해서 작성한 내용이니 해당 글도 확인해보시면 좋을 것 같아요!

2023-07-16 15:08 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +                .orElseThrow(() -> new NoSuchElementException("사전 식물이 존재하지 않습니다. id : " + request.getDictionaryPlantId()));
현재로서는 특별한 상황이 예상되지 않으니 자바에서 제공하는 표준 예외로 컨벤션을 맞춰보는것도 좋을 것 같아요~!

2023-07-16 15:45 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/fixture/MemberFixture.java
> +    public static Member 주노 = Member.builder()
반영했습니다 👍

2023-07-16 15:46 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/dto/PetPlantRequest.java
> +public class PetPlantRequest {
해당 사이드이펙트를 고려하지 않고 작성했던 것 같네요 😅
별도의 생성자를 생성한 뒤 `@Builder`를 붙이는 방식으로 리팩터링했습니다.

2023-07-16 15:52 UTC, Choi-JJunho commented
요청사항 반영했습니다~!
추가로 작업한 내용중 변경사항이 몇가지 있어 말씀드립니다!

- Builder를 사용하기 위해 만든 생성자의 접근제어자 private로 변경
- PetPlantResponse DTO생성
- 통합테스트를 수행하기 위한 Member, DictionaryPlant, PetPlant Support Fixture 생성

2023-07-17 07:47 UTC, yeonkkk approved these changes
리뷰 요청 드린 부분 잘 반영해주셨네요. 
고생하셨습니다!!👍

2023-07-17 07:57 UTC, rawfishthelgh approved these changes
확인했습니다! 요청사항 반영해주셔서 감사해요

2023-07-17 07:57 UTC, merged

2023-07-17 14:28 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
> +    }
@Choi-JJunho 
주노! 리뷰하다가 놓친부분이 있어서 늦게 나마 리뷰 달아봐요!😓
`PetPlantResponse`를 생성하는 매퍼에서 `dictionaryPlant`에 대한 부분이 빠져있는 것 같아서요. 
테스트에도 들어있지 않아서 아마 터지지 않은 것 같아요..!
혹시 해당 로직이 있는 코드가 따로 있는데 제가 놓친거면 알려주세요. 
확인 한번 부탁드립니다!

2023-07-18 00:55 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/mapper/PetPlantMapper.java
> +    }
앗! 해당 부분 [반려식물 전체조회 PR](https://github.com/woowacourse-teams/2023-pium/pull/68)에서 반영하겠습니다 😅