feat: 전역 suspense 개선
woowacourse-teams/2023-pium pull request #427
Opened 2023-10-09 14:26 UTC by bassyu

# 🔥 연관 이슈

- close #426

# 🚀 작업 내용

안녕하세요!!
생각보다 변경사항이 많아져서.. 설명을 많이 하게 되었네요 😢 
미리 시간 내주셔서 감사합니다!

### 상황

현재는  `스켈레톤이 어울린다고 판단한 페이지`를 제외하면 보통 전역 Suspense를 통해 로딩 상태임을 표현합니다.
이 프로세스를 간단하게 표현하면 아래처럼 나타낼 수 있습니다.

`A페이지` -> `피우미` -> `B페이지`

여기서 발생하는 아쉬운점이 있었습니다.

1. `B페이지`가 비동기이면서 로드가 빠른 경우(예를들면 React.lazy가 먹혀있는 마이페이지) 아주 잠깐 Suspense가 보이면서 깜빡이는 현상
2. `A페이지`와 `B페이지`의 레이아웃이 비슷해도 관련 없는 범용 UI의 Suspense가 보여서 연결성이 떨어지는 현상

### 개선

이를 해결하기 위해 아래와 같은 Suspense를 생각했습니다.

`A페이지` -> `A페이지 + 로딩 프로그래스 바` -> `B페이지`

이렇게 되는 경우 이전의 아쉬운 점을 해결할 수 있습니다.

1. 페이지 전환 속도가 빠르더라도, 유저 입장에서는 `A페이지` -> `B페이지`로 보이기 때문에 깜빡임이 없습니다.
2. `A페이지`와 `B페이지`가 유사한 레이아웃을 가졌을 때, 해당 레이아웃이 사라졌다가 다시 생기지 않습니다.

이러한 로딩 UI를 적용한 곳은`GitHub`이나 `Web Instagram` 등이 있습니다.

아래는 MSW delay 1000으로 테스트해본 결과입니다.

| 개선 선 | 개선 후 |
| --- | --- |
| <img width=200 src="https://github.com/woowacourse-teams/2023-pium/assets/54442420/3253d4cf-9948-4440-92a0-06e52e81c1de" /> | <img width=200 src="https://github.com/woowacourse-teams/2023-pium/assets/54442420/94580728-767e-432a-a9f8-41d606605409" /> |

### 구현

아래처럼 구현했습니다.

1. `A페이지` 렌더링 후 페이지 컴포넌트 자체를 전역 상태에 저장
2. Suspense에서 저장된 페이지를 가져와서 렌더링 후 상단 로딩바를 보여줌
만약 `마지막 페이지`가 없으면(첫 페이지면) 피우미가 보여짐
3. `B페이지` 렌더링 후 로딩바를 가림

이때, 2번 3번 모두 로딩바가 존재하는 것이 부드러워서 Suspense와 분리해서 관리했습니다.

# 💬 리뷰 중점사항

1. 이것 저것 만들고 지우고 반복하느라 놓친 부분이 있을 수 있습니다..!

2. 로딩바는 기본적으로 5초동안 느리게 흐르고 페이지 로딩이 완료되면 채워진 다음 사라집니다.
여기에 욕심을 좀 내자면 axios의 onProgress 콜백을 활용해서 실제 네트워크 상태를 상단 로딩 바에 반영할 수 있는데요, 
하면 좋을 것 같으면서도, 아직 오래 걸리는 요청은 없으니 과하다는 생각도 들었어요.

3. 결국 `마지막 페이지`를 전역 상태로 관리해야 하는데요, 이 책임을 현재는 모든 페이지가 가지고 있습니다.
전역적으로 깔끔하게 해결해보려 했지만, RootTemplate은 어디에서나 1번만 렌더링 되어서 이대로 두었어요.

4. 새로운 suspense의 fallback이 어울릴 것 같은 페이지나 어울리지 않는 페이지 추천도 해주시면 감사하겠습니다!

2023-10-10 07:00 UTC, hozzijeong requested changes
코멘트 남겼습니다!

다만, 최상단 레이아웃을 Wrapper로 통일하기로 했던 것 같은데 어디는 Main으로 바뀌는게 보이는데 그 이유를 물어봐도 될까요?

2023-10-10 07:14 UTC, WaiNaat requested changes
안녕하세요! 디자인 진짜 이쁘게 잘 나왔네요 💯 

> axios의 onProgress 콜백

찾아보니까 axios를 쓰지 않더라도 response header의 Content-Length랑 response.body의 길이를 이용해서 계산하는 기법이 있긴 하더라구요. 쵸파 말씀대로 지금은 사실 그렇게까지 큰 요청이 없다는 생각이 들지만 기술적인 챌린지를 원하신다면 충분히 도전해볼 만한 문제라고 생각합니다!

> 이 책임을 현재는 모든 페이지가 가지고 있습니다. 전역적으로 깔끔하게 해결해보려 했지만

이거는 진짜 흘러가는 구름같네요.. 자꾸 여러 개의 상태를 이펙트로 물리는 방법밖엔 생각이 안납니다ㅠㅠ

> 새로운 suspense의 fallback이 어울릴 것 같은 페이지

PetPlantDetails <-- 여기에도 있으면 좋을 것 같아요!

2023-10-13 01:36 UTC, bassyu commented on frontend/src/components/@common/PageLoadingBar/index.tsx
> +  }, [isShowPageLoading]);
이부분은 다음 페이지가 로드 되었을 때 마무리 애니메이션이라 항상 상수로 넣어도 됩니다!

2023-10-13 01:40 UTC, bassyu commented on frontend/src/components/@common/PageLoadingBar/index.tsx
> +  const root = useMemo(() => document.getElementById('root')!, []);
사실 없을리가 없으니 지금은 둘다 비슷할 것 같긴 하네요.. 
타입 자체를 바꿀 수 있는 단언보다, 타입은 같지만 있다는걸 확신해주는 !를 사용하는게 조금 더 안전한 코드라고 생각했습니다~

2023-10-13 01:46 UTC, bassyu commented on frontend/src/pages/@common/LastPageLoading/index.tsx
어렵네요.. RootTemplate의 Outlet이 전부 페이지면서, Outlet 대신 들어가는 fallback이라 페이지라고 생각했어요! (원래의 Loading이 페이지에 있기도 했구요)
Outlet을 감싸는 Suspense는 페이지로 보고, 대신 그 안에서 감싸는 Suspense는 컴포넌트로 하는 건 어떤가요?

2023-10-13 01:53 UTC, bassyu commented on frontend/src/pages/auth/MyPage/MyPage.style.ts
> +export const Main = styled.main`
> 다만, 최상단 레이아웃을 Wrapper로 통일하기로 했던 것 같은데 어디는 Main으로 바뀌는게 보이는데 그 이유를 물어봐도 될까요?

페이지마다 헤더와 푸터가 다르기 때문에 헤더와 푸터도 페이지의 구성요소라고 생각했습니다.
그래서 현재 MyPage에서 최상단 레이아웃 또는 최상단 엘리먼트는 사실 PageLogger라고 생각했습니다!
형재요소와 함께 Wrapper가 존재하면 오히려 컨벤션에 맞지 않다고 생각했어요~

2023-10-13 02:18 UTC, bassyu commented on frontend/src/components/@common/PageLogger/index.tsx
> +  }, []);
children을 넣어야 하겠네요! 좋아요 👍

2023-10-13 02:21 UTC, bassyu commented on frontend/src/components/@common/PageLoadingBar/index.tsx
> +  }, [isShowPageLoading]);
아쉽긴 합니다... 😢

2023-10-13 02:28 UTC, bassyu commented on frontend/src/components/@common/PageLoadingBar/index.tsx
> +  const root = useMemo(() => document.getElementById('root')!, []);
특별한 이유는 없었습니다! 혹시 body에 넣으면 장단점이 있을까요?

2023-10-13 06:02 UTC, hozzijeong approved these changes
멋져요~

2023-10-13 06:53 UTC, WaiNaat approved these changes
멋있어요

2023-10-13 06:53 UTC, merged

2023-10-14 15:39 UTC, WaiNaat commented on frontend/src/components/@common/PageLoadingBar/index.tsx
> +  const root = useMemo(() => document.getElementById('root')!, []);
불필요한 non-null assertion이 없어집니다

2023-10-15 12:19 UTC, bassyu commented on frontend/src/pages/@common/LastPageLoading/index.tsx
Outlet에 들어가는 내용이 페이지라고 생각했는데 url 기준도 좋네요!