feat: 웹 푸시 구현
woowacourse-teams/2023-pium pull request #429
Opened 2023-10-11 11:02 UTC by hozzijeong

# 🔥 연관 이슈

- close #415 

# 🚀 작업 내용
- [x] FCM을 통해 푸시 알림을 주고 받는다
- [x] 토글을 통해서 알림을 on/off 할 수 있다.
- [x] pwa 조건을 맞춘다
- [x] service worker를 등록한다.
- [x] 처음 로그인 했을 때 사용자에게 바로가기 설치를 물어본다

# 💬 리뷰 중점사항

# 안녕하세요?

끝나고 보니 별거 아니지만 막상 할때는 너무 막막했던 기능입니다 하하

일단 기본적은 구조는 아래와 같습니다.

<img width="728" alt="스크린샷 2023-10-11 오후 6 59 39" src="https://github.com/woowacourse-teams/2023-pium/assets/50974359/7bb21dde-8abc-4e05-a21f-057e3cb6286d">

클라이언트에서는 서비스 워커를 실행하고, firebase 토큰을 생성하는 역할을 합니다.

클라이언트에서 생성한 FCM 토큰은 알림을 허락하면 백엔드에 post하게 됩니다. 이 FCM  토큰은 DB에 저장되어 있다가 시간이 되었을 때 서버에서 Firebase로 알림을 보내게 됩니다.

여기서 주의할 점이 사용자가 브라우저 알림을 꺼놓는다면 알림을 받을 수 없게 됩니다. 그리고 저희가 코드를 통해서 프롬프트를 띄울 수 없다는 것이 좀 치명적이긴 합니다. 

사용자가 브라우저 알림을 설정 했다면 마이 페이지 > 리마인더 알림 받기를 통해 토큰을 등록, 삭제할 수 있습니다. ( 정책상 2달에 한번 토큰 갱신을 해야 한다는데 이건 서버에서 하면 될 것 같아요)

pushManager를 사용해서 subscription을 하지 않고도web-push가 가능한 이유는 firebase를 initial 함으로써 가능하지 않았나 생각이 드네요

삽질을 좀 많이해서 일관적이지 못한 코드가 곳곳에 있을 것 같네요... 리뷰 잘 부탁드립니다!

---
TODO: 토큰이 자동으로? expire되는데 그 기간을 잘 모르겠더라구요;; 좀 치명적이긴 하네요

2023-10-12 07:51 UTC, bassyu reviewed
안녕하세요 클린! 알림 구현하느라 정말 고생 많으셨어요! 👍 
코드 리뷰 전에, 전체적인 흐름이 아직 이해가 안되네요 😢  궁금한점 질문 하겠습니다..!
(토글 UI 넘 이뻐요)

> 클라이언트에서는 서비스 워커를 실행하고, firebase 토큰을 생성하는 역할을 합니다.

firebase는 처음 보는 키워드라 어렵네요.. 잘은 모르지만 서비스 워커에서 알람을 주면 될 것 같은데, 혹시 서비스 워커의 어떤 한계가 있었는지, firebase 어떤 기능이나 장점이 있는지 궁금해요~

> 클라이언트에서 생성한 FCM 토큰은 알림을 허락하면 백엔드에 post하게 됩니다. 이 FCM 토큰은 DB에 저장되어 있다가 시간이 되었을 때 서버에서 Firebase로 알림을 보내게 됩니다.

firebase를 모르니 이 부분도 이해가 잘 안가네요.. 
백엔드를 거치지 않고 서비스 워커에서 구독, 시간을 기억해서 cilent - filrebase 둘이서 소통하는 것은 구조적으로 불가능한지, 또는 단점이 있는지 궁금합니다~

2023-10-12 07:51 UTC, bassyu commented on frontend/src/pages/auth/Login/Authorization.tsx
> +  const { mutate } = useLogin();
이렇게 어떤가요?
```suggestion
  const { mutate: login } = useLogin();
```

2023-10-12 07:51 UTC, bassyu commented on frontend/src/components/@common/Toggle/index.tsx
> +  toggleOffCallback,
동사이기 때문에 함수인걸 알 것 같아서 Callback을 표현 안해줘도 될 것 같은데 어떤가요?
네이밍은 매우 주관적인 것이긴 해서 가볍게 제안해봅니다~

2023-10-12 07:51 UTC, bassyu commented on frontend/src/components/@common/Toggle/index.tsx
> +  toggleOffCallback?: () => void;
onChange 로 통일해서 `!state`를 넘겨주는 interface는 어떤지 제안해봅니다!
```suggestion
  onChange?: (state: boolean) => void;
```

```
<ToggleBtn
        onClick={() => { onChange?.(!state) }}
```

2023-10-12 08:02 UTC, WaiNaat requested changes
안녕하세요 클린~ 완전히 새로운 기능 구현하느라 고생하셨습니다!
알림을 주고받는 부분은.. 일단 돌아간다고 믿고 코드에 관련해서 궁금한 점들 코멘트로 남겼어요

추가로 로컬에서 msw + firebase-sw가 같이 돌아가면 좋겠다는 생각이 들어서 연구한 코드 남겨요
`localDevServiceWorker.js` 같은 파일을 만들고 안에서 `importScripts`로 두 서비스워커를 받아온 후 이걸 키면 됩니다

```ts
if (process.env.NODE_ENV === 'development') {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { worker } = require('./mocks/browser');
  registerServiceWork('/localDevServiceWorker.js');

  worker.start({
    serviceWorker: {
      url: 'http://localhost:8282/localDevServiceWorker.js',
    },
  });
}

if (process.env.NODE_ENV === 'production') {
  registerServiceWork('/firebase-messaging-sw.js');
}
``` 
이거보다 깔끔하게 짤 순 있겠지만 일단 돌쓰 올려봅니다

2023-10-12 08:06 UTC, hozzijeong commented on frontend/src/pages/auth/Login/Authorization.tsx
> +  const { mutate } = useLogin();
좋아요~

2023-10-12 08:10 UTC, hozzijeong commented on frontend/src/components/@common/Toggle/index.tsx
> +  toggleOffCallback,
함수인 것은 아는데 함수의 역할까지 네이밍에 포함된다고 생각해서 callback을 추가했습니다! toggleOn으로 작성하고서 handler로 사용이 될 수도 있기 때문에 최대한 명시적으로 사용하려고 했습니다

2023-10-12 08:13 UTC, hozzijeong commented on frontend/src/components/@common/Toggle/index.tsx
> +  toggleOffCallback?: () => void;
현재 toggle에 넘기는 state가 서버에서 받아온 상태인데 그 상태를 임의로 !해서 넘기는 것은 잘 모르겠네요 ㅠㅠ. 저도 Toggle을 작성하면서 범용성이 있어보이지는 않아서 고민이긴 합니다.

현재 구독 정보를 반환하는 메서드에 낙관적 업데이트를 적용해놔서 저희가 직접적으로 상태를 변경시키는 것보다는 인자로 넘어온 것을 사용하는게 좋다고 생각합니다!

2023-10-12 08:15 UTC, hozzijeong commented on frontend/src/components/@common/Toggle/index.tsx
> +  }, [state]);
의존성 배열이 모자란 것은 사실이긴 한데, 결국 Callback이 state의 값에 따라 실행되는 메서드라고 생각해서 의도적으로 추가하지 않았습니다. 혹시 예상되는 문제가 있을까요..?

2023-10-12 08:16 UTC, hozzijeong commented on frontend/src/pages/auth/Login/Authorization.tsx
> +  }, []);
여기는 추가해야겠네요 ㅋㅋㅋㅋ

2023-10-12 08:16 UTC, hozzijeong commented on frontend/src/hooks/@common/useInstallApp.ts
>      const showPrompt = JSON.parse(getCookie('PromptVisible') || 'true');
좋아요~~!

2023-10-12 08:18 UTC, hozzijeong commented on frontend/src/hooks/@common/useInstallApp.ts
> +  // TODO: 왜 '/'에서만 beforeinstallprompt가 이벤트 추가가 되나?  prompt가 나오고 나머지는 나오지 않는가?
이 주석을 작성했을 때가 처음에 로그인하고 Reminder에서 prompt가 나타나도록 작성했었는데 reminder에서는 나타나지 않고 home에 들어가야지만 나왔을 때 작성한 거였어서... 타임라인 맞추겠습니다..ㅎ

2023-10-12 08:18 UTC, hozzijeong commented on frontend/src/components/@common/Toggle/Toggle.style.ts
> +  cursor: pointer;
오 좋습니다!

2023-10-12 09:04 UTC, hozzijeong reviewed
# 안녕하세요 쵸파 참새?

우선 쵸파가 질문한 것에 대해서 답변을 남겨봅니다! 

> 서비스 워커에서 알람을 주면 될 것 같은데, 혹시 서비스 워커의 어떤 한계가 있었는지, firebase 어떤 기능이나 장점이 있는지 궁금해요~

우선 서비스 워커에서 알람을 주는데, 어떤 종류의 알림을 어느 내용으로 주는지가 명확하지 않습니다. 저희의 경우에는 리마인더 알림을 허용한 사용자의 식물이 오늘 알람을 줘야 하는데 "알림을 허용한" "사용자"의 "식물"에 대한 정보가 서비스 워커에 없기 때문에 해당 정보를 갖고 있는 백엔드가 필요합니다. 만약에 해당 정보를 서비스 워커가 갖고 있다고 한다면 보안 사고라고 생각합니다. 

firebase의 역할에 대해서는 너무 많아서 저도 자세히는 설명을 못드리겠네요 ㅠㅠ 하지만 우선은 클라우드 메세지 서비스를 지원하는 것 하나만 알고 있으면 될 것 같습니다! 
간단하게는 개발 플랫폼이라고 생각하시면 되는데, 데이터 베이스, 알림, A/B 테스트 GA 등등을 지원하고 있습니다. 
지금 저희가 알람 기능을 구현하는게 Web Push를 통해서 기능을 구현하고 있는데 이 Web Push를 구현하기 위해서는 [Web Push Protocol](https://web.dev/articles/push-notifications-web-push-protocol?hl=ko)을 준수해야 합니다. 여기에서 서버, 클라이언트 그리고 "푸시 서비스"가 필요한데 앞에서 말한 firebase에서 푸시 서비스 기능을 같이 지원하고 있습니다.

 왜 firebase를 사용했냐고 물어보시는 것이라면 문서화가 잘 되어 있어서 러닝 커브가 낮고 푸시 서비스 뿐만 아니라 GA와 연동도 되기 때문입니다!!

> 백엔드를 거치지 않고 서비스 워커에서 구독, 시간을 기억해서 cilent - filrebase 둘이서 소통하는 것은 구조적으로 불가능한지, 또는 단점이 있는지 궁금합니다~

앞에서 말씀드린 protocol이 있어서 불가능하고, 전송할 데이터 역시 클라이언트에 없어서 불가능합니다! 그리고 [서비스 워커의 lifeCycle](https://web.dev/articles/service-worker-lifecycle?hl=ko)이 존재하는데, 만약에 버전이 업데이트 된다고 하면 데이터가 업데이트 돼야 하는데 그 과정에서 데이터가 유실될 수도 있습니다.  또한 사용자의 정보를 다루는 것이기 때문에 보안에도 문제가 있고 firebase에서 제공하는 token을 유지하려면 살아있는 서버에서 관리해주는게 보안상 더 좋습니다. 그래서 중간에 서버가 필수로 필요합니다!

참새가 말씀하신 serviceWorker와 firebase의 합작품은 한번 츄라이 해보겠습니다.

2023-10-12 09:04 UTC, hozzijeong commented on frontend/src/components/@common/Toggle/Toggle.style.ts
> +  cursor: pointer;
오 좋습니다!

2023-10-12 09:04 UTC, hozzijeong commented on frontend/src/components/@common/Toggle/index.tsx
> +  toggleOffCallback?: () => void;
현재 toggle에 넘기는 state가 서버에서 받아온 상태인데 그 상태를 임의로 !해서 넘기는 것은 잘 모르겠네요 ㅠㅠ. 저도 Toggle을 작성하면서 범용성이 있어보이지는 않아서 고민이긴 합니다.

현재 구독 정보를 반환하는 메서드에 낙관적 업데이트를 적용해놔서 저희가 직접적으로 상태를 변경시키는 것보다는 인자로 넘어온 것을 사용하는게 좋다고 생각합니다!

2023-10-12 09:04 UTC, hozzijeong commented on frontend/src/components/@common/Toggle/index.tsx
> +  toggleOffCallback,
함수인 것은 아는데 함수의 역할까지 네이밍에 포함된다고 생각해서 callback을 추가했습니다! toggleOn으로 작성하고서 handler로 사용이 될 수도 있기 때문에 최대한 명시적으로 사용하려고 했습니다

2023-10-12 09:04 UTC, hozzijeong commented on frontend/src/components/@common/Toggle/index.tsx
> +  }, [state]);
의존성 배열이 모자란 것은 사실이긴 한데, 결국 Callback이 state의 값에 따라 실행되는 메서드라고 생각해서 의도적으로 추가하지 않았습니다. 혹시 예상되는 문제가 있을까요..?

2023-10-12 09:04 UTC, hozzijeong commented on frontend/src/hooks/@common/useInstallApp.ts
>      const showPrompt = JSON.parse(getCookie('PromptVisible') || 'true');
좋아요~~!

2023-10-12 09:04 UTC, hozzijeong commented on frontend/src/hooks/@common/useInstallApp.ts
> +  // TODO: 왜 '/'에서만 beforeinstallprompt가 이벤트 추가가 되나?  prompt가 나오고 나머지는 나오지 않는가?
이 주석을 작성했을 때가 처음에 로그인하고 Reminder에서 prompt가 나타나도록 작성했었는데 reminder에서는 나타나지 않고 home에 들어가야지만 나왔을 때 작성한 거였어서... 타임라인 맞추겠습니다..ㅎ

2023-10-12 09:04 UTC, hozzijeong commented on frontend/src/pages/auth/Login/Authorization.tsx
> +  const { mutate } = useLogin();
좋아요!!

2023-10-12 09:04 UTC, hozzijeong commented on frontend/src/pages/auth/Login/Authorization.tsx
> +  }, []);
여기는 추가해야겠네요 ㅋㅋㅋㅋ

2023-10-13 01:31 UTC, bassyu approved these changes
> 지금 저희가 알람 기능을 구현하는게 Web Push를 통해서 기능을 구현하고 있는데 이 Web Push를 구현하기 위해서는 [Web Push Protocol](https://web.dev/articles/push-notifications-web-push-protocol?hl=ko)을 준수해야 합니다. 여기에서 서버, 클라이언트 그리고 "푸시 서비스"가 필요한데 앞에서 말한 firebase에서 푸시 서비스 기능을 같이 지원하고 있습니다.

> 앞에서 말씀드린 protocol이 있어서 불가능하고, 전송할 데이터 역시 클라이언트에 없어서 불가능합니다! 

질문을 조금 드렸는데도 자세하게 설명해주셔서 전체적인 흐름이 잘 이해됐어요! 감사합니다 👍👍

2023-10-13 01:31 UTC, bassyu commented on frontend/src/components/@common/Toggle/index.tsx
> +  toggleOffCallback?: () => void;
오 현재 낙관적 업데이트긴 하네요
장바구니 미션의 개수 버튼처럼 토글 클릭 한번에 로딩과 에러를 다 핸들링하는 방향은 어떤가요?

2023-10-13 01:50 UTC, WaiNaat requested changes
변경하신 부분들 확인했습니다~

2023-10-13 02:10 UTC, bassyu commented on frontend/src/components/@common/Toggle/index.tsx
> +  toggleOffCallback?: () => void;
현재 에러는 핸들링 하네요! 꼼꼼하게 못봐서 죄송합니다ㅠ
실패하는 일이 크게 일어날 것 같진 않아서 이대로도 괜찮을 것 같아요!

2023-10-13 04:04 UTC, bassyu commented on frontend/src/components/@common/Toggle/index.tsx
> +  }, [state]);
> 리액트의 주장을 떠나서 실용주의적인 관점에서 본 제 의견을 말씀드리면 이게 결국엔 리액트에서 기본적으로 제공하는 린트에서 잡아주는 값이고, 많은 CD툴이 린트 경고가 있을 때 빌드를 거부한다는 것과 다음 사람들이 저희 코드를 본다는 점을 고려했을 때 지금부터 의존성 배열을 관리하는 연습을 하는 게 좋다고 생각해요

좋습니다! 공식문서를 보니 공감되는 근거가 많네요~ 좋은 자료 공유해주셔서 감사합니다 👍

2023-10-13 04:24 UTC, WaiNaat approved these changes
멋있어요
개발서버에서 잘 됐으면 좋겠네요

2023-10-13 04:25 UTC, merged