feat: 푸시 알림 기능
woowacourse-teams/2023-pium pull request #430
Opened 2023-10-11 17:53 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #417 

# 🚀 작업 내용

- [x] Member 엔티티 필드 추가
  - [x] 알림 구독을 위한 deviceToken 컬럼 추가
- [x] 알림 구독 / 해지 API 추가
  - [x] 알림 구독 시 deviceToken 추가
  - [x] 알림 해지 시 deviceToken Null
- [x] FCM 서버로 푸시알림 전송
  - [x] 매일 아침 7시 푸시알림 전송하도록 Scheduled 구성
- [x] 사용자에게 푸시알림을 보낼 수 있는 Admin 페이지 구성

# 💬 리뷰 중점사항

> FCM의 요청 흐름은 다음 discussion을 참고해주세요
> - https://github.com/woowacourse-teams/2023-pium/discussions/416

클린과 함께 FCM을 이용한 푸시알림 전송 기능을 구현해봤습니다.
고민한것보다 기능이 많이 없어 다행이라고 생각되네요

나름 꼼꼼하게 봤다고 생각하지만 놓친 부분이 있을 것 같아 전체적으로 한번 봐주시면 감사하겠습니다 🙇‍♂️

2023-10-12 15:08 UTC, yeonkkk requested changes
주노 알림 기능 구현하시느라 고생하셨습니다! 👍
테스트, 문서화 다 놓치지 않고 꼼꼼하게 해주셨네요 ㅎㅎ 역시🚀 

컨벤션 관련 코멘트와 궁금한 부분에 대해 조금 남겨 보았어요.
확인 부탁드려요!

2023-10-12 15:08 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/controller/TestController.java
> +    }
### A

이 컨트롤러는 어떤 용도로 사용되는건가요?
AdminPageController에서도 동일한 작업을 수행하는 것 같아서 여쭤봅니닷

2023-10-12 18:08 UTC, rawfishthelgh requested changes
주노! 고생했어요
몇 가지 의견 교환 후 수정 처리 결정을 해야 할 것 같아 rc 하겠습니다ㅎㅎ

2023-10-12 18:08 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/ReminderService.java
> +    @Scheduled(cron = "0 0 7 * * *")
### A
이게 그 말로만 듣던 스케줄러군요...

2023-10-12 18:08 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/event/notification/NotificationEventListener.java
> +    }
### C
궁금한 내용인데, 알림 이벤트를 이벤트 호출 메소드와 동일 트랜잭션으로 처리하나요?
 
만약 비동기 처리를 의도했다면, @Async 어노테이션을 사용해야 한다는 글을 봐서요!
[참고1](https://devvkkid.tistory.com/269)
[참고2](https://leeheefull.tistory.com/25)

2023-10-13 00:33 UTC, Kim0914 requested changes
안녕하세요 주노 ~ 그레이에요 ㅎㅎ

미션과 병행하는 상황에서 바쁜 일정에도 기능 구현을 야무지게 잘 해주셨네요 !

궁금한 부분 코멘트 남겼어요.
확인 부탁 드려요 !

2023-10-13 00:38 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/repository/PetPlantCustomRepositoryImpl.java
> +                .where(petPlant.nextWaterDate.eq(date), member.deviceToken.isNotNull())
@rawfishthelgh 
저는 잘 나와요 ㅎㅎ build clean -> build 한번 해보셨나요 ?!

2023-10-13 00:39 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/FcmMessageSender.java
> +public class FcmMessageSender {
### A

외부 API를 이용하는 서비스(S3)는 util 패키지에 분리하기로 했었는데, 서비스 패키지에 위치시켜주신 이유가 있을까요?

2023-10-13 00:40 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/MemberService.java
> +        member.updateDeviceToken(null);
### A

구독 중이지 않은 회원이 구독 취소하면 예외를 발생시키는건 어떨까요?

2023-10-13 00:43 UTC, Kim0914 commented on backend/pium/src/main/resources/application.properties
> +fcm.api.url=https://fcm.googleapis.com/v1/projects/project-id/messages:send
### A

실제 사용하는 주소는 아니겠죠?!

2023-10-13 00:44 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/acceptance/MemberApiTest.java
> +class MemberApiTest extends AcceptanceTest {
### C

어떤 인수테스트는 Public 접근자가 있고 어떤 인수테스트는 Public 접근자가 없는데 구분해주신 이유가 있을까요?

2023-10-13 03:55 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/notification/NotificationEvent.java
> +    public static NotificationEvent of(String targetToken, String title, String body) {
미션 코드와 왔다갔다 하다보니 저도모르게...
Builder 형태로 수정하겠습니다 👍

2023-10-13 03:56 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/FcmMessageSender.java
> +    private final ObjectMapper objectMapper;
앗 리팩터링 과정에서 제거하는걸 누락했네요
감사합니다~!

2023-10-13 03:57 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/dto/FcmMessageResponse.java
> +    private boolean validate_only;
FCM에서 저 데이터를 받는 형식이 스네이크케이스여서 어쩔수 없었습니다 ㅠㅜ

2023-10-13 04:17 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/MemberServiceTest.java
> +        Member saveMember = memberRepository.save(member);
오~! 감사합니다~
기존에 있던 테스트코드에도 적용했습니다

2023-10-13 04:17 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/TestController.java
> +    }
아.. 로컬에서 테스트용으로 작성했던건데 언제 커밋에 들어갔죠..ㅠㅠㅜㅠㅜㅠ
바로 제거해버리겠습니다 😅

2023-10-13 04:19 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/admin/controller/AdminPageController.java
> +    }
해당 서비스를 Admin, Event에서도 활용중이기도 하고 알림이라는 도메인이 다양한 도메인과 연관지어질 것도 우려되는 부분중 하나였기 때문에 하나의 Dto에 의존하게 만들고 싶지 않아서 값을 직접 꺼내썼습니다

2023-10-13 04:20 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/exception/FcmException.java
> +    }
넵 차후 FCM의 다른 기능을 확장적으로 사용하게 될 여지가 있어보여 이너클래스로 묶었습니다

2023-10-13 04:27 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/NotificationService.java
> +    private final FcmMessageSender fcmMessageSender;
확실히 FCM이라는 외부 라이브러리에 의존하고 있는 모습이 불편하네요
MessageSendManager로 추상화 시켜보겠습니다~

2023-10-13 04:34 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/admin/controller/AdminPageController.java
> +    }
헉... 감사합니다
디테일이 부족했네요 😅

2023-10-13 04:36 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/MemberController.java
> +    public ResponseEntity<Void> checkNotificationStatus(@Auth Member member, @RequestBody NotificationSubscribeRequest request) {
엇 맞습니다! 복붙하다가 메소드명을 신경 못썼네요 😅

2023-10-13 04:41 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/dto/NotificationSubscribeRequest.java
> +        private String deviceToken;
오! 역시 꼼꼼한 그레이 👍
NotNull 검증조건을 추가해주겠습니다

2023-10-13 04:42 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/MemberService.java
> +    }
오! 좋습니다~!

2023-10-13 04:45 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/MemberController.java
> +        return ResponseEntity.noContent().build();
구독 추가는 Location헤더에 뭘 담아야할지 고민하다가 자원 생성이 아니라고 생각하여 OK로 반환했습니다.
이렇게 생각하니 구독 해제도 마찬가지로 OK를 날리는게 맞아보이네요

그레이는 어떻게 생각하시나요?

2023-10-13 04:46 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/TestController.java
> +    public ResponseEntity<Void> test(@Param("deviceToken") String deviceToken, @Param("title") String title, @Param("body") String body) {
> 아.. 로컬에서 테스트용으로 작성했던건데 언제 커밋에 들어갔죠..ㅠㅠㅜㅠㅜㅠ
> 바로 제거해버리겠습니다 😅

ditto...

2023-10-13 04:47 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/TestController.java
> +    private final MemberService memberService;
> 아.. 로컬에서 테스트용으로 작성했던건데 언제 커밋에 들어갔죠..ㅠㅠㅜㅠㅜㅠ
> 바로 제거해버리겠습니다 😅

흑흑 잘못올린 컨트롤러에도 정성스러운 피드백 감사합니다...

2023-10-13 04:48 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/notification/NotificationEvent.java
> +@Validated
오 event 실행측에서 nullsafe한 객체를 다루는게 좋겠다~ 하고 아래 필드에 적용을 안했네요 😅

필드에 NotNull을 적용하겠습니다!

2023-10-13 04:53 UTC, Choi-JJunho commented on backend/pium/src/main/resources/application.properties
> +fcm.api.url=https://fcm.googleapis.com/v1/projects/project-id/messages:send
네네~!

> 관련 문서입니다
> https://firebase.google.com/docs/cloud-messaging/auth-server?hl=ko#use-credentials-to-mint-access-tokens

2023-10-13 04:56 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/MemberController.java
> +        return ResponseEntity.noContent().build();
`OK`이든 `NO_CONTENT` 일관성만 맞춰준다면 상관없을 것 같아요 ㅎㅎ

2023-10-13 04:57 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/FcmMessageSender.java
> +public class FcmMessageSender {
위 하마드의 리뷰 내용으로부터 생각나서 반영했습니다~

- https://github.com/woowacourse-teams/2023-pium/pull/430#discussion_r1357194131

2023-10-13 04:58 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/acceptance/MemberApiTest.java
> +class MemberApiTest extends AcceptanceTest {
구분의 의미는 없고 다 없애려고했습니다~!

굳이 public class로 선언될 이유가 없는 것 같습니다

2023-10-13 07:23 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/service/dto/FcmMessageResponse.java
> +    private boolean validate_only;
고정된 형식이군요 ㅎㅎ 이해 완.
(링크는 재귀네요)

2023-10-13 16:45 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/dto/FcmMessageResponse.java
> +    private boolean validate_only;
앗 링크가 왜 저렇게.. ㅠㅠㅠㅠ
여기 정상적인 링크입니다
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send?hl=ko#request-body

2023-10-14 01:14 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/admin/dto/AdminSendNotificationRequest.java
> +    private String body;
javascript 짜면서 예외 처리를 안해줬던거같아서 확인해봤는데 되어있네요 ㅎㅎ
`@NotNull` 검증조건 추가했습니다~


```javascript
// resources/templates/admin/member/requests.html

function submitForm(e) {
    e.preventDefault();
    if (confirm('정말로 테스트 알림을 보내겠습니까?')) {
        const formData = new FormData(formElement);
        fetch(`/admin/notification`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(Object.fromEntries(formData))
        })
            .then(function (response) {
                if (response.ok) {
                    alert('알림을 전송했습니다.');
                } else {
                    alert('알림 전송중 오류가 발생했습니다.');
                }
            })
            .catch(function (error) {
                console.error('Fetch 오류:', error);
                alert('오류가 발생했습니다.');
            });
    } else {
    }
}
```

2023-10-14 01:19 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/event/notification/NotificationEventListener.java
> +    }
오..! 확실히 동기로 처리할 이유가 없는 이벤트네요
`@Async`를 사용하여 비동기로 처리하는게 좋겠군요 👍

2023-10-14 06:20 UTC, yeonkkk approved these changes
주노 ~ 피드백 잘 반영해주셨네요🙂

코멘트 추가로 조금 남겨봤어요. 
컨벤션 관련한 내용은 적용 해주시고, 나머지는 확인해보고 필요하다고 판단되면 추가해주세요~~

approve 하겠습니다, 고생하셨어요 ~!

2023-10-14 06:20 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/fcm/service/FcmMessageSender.java
> +public class FcmMessageSender implements MessageSendManager {
### C

`FcmMessageSender`에 대한 테스트도 작성해보면 어떨까요?

2023-10-14 18:15 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/fcm/service/FcmMessageSender.java
> +@Service
저도 궁금하네요 이거ㅎㅎ

2023-10-14 18:18 UTC, rawfishthelgh approved these changes
주노 야무진 리뷰 반영 감사합니다.
크게 코멘트 할 부분 없어 approve할게요!

2023-10-15 06:01 UTC, Kim0914 approved these changes
꼼꼼하게 수정 잘 해주셨네요 ㅎㅎ

조이가 남긴 코멘트만 한번 확인해주시면 좋을 것 같네요 ^.^

Approve 하겠습니다 !

2023-10-15 13:47 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/admin/dto/AdminSendNotificationRequest.java
> +import lombok.*;
인텔리제이 설정이 자꾸 오락가락하네요 ㅠㅜ
감사합니다

2023-10-15 13:47 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/fcm/service/FcmMessageSender.java
> +@Service
아 처음에 Service 패키지에 있던 친군데... 바꾸는걸 깜빡했군요
Component로 수정하겠습니다.

2023-10-16 02:01 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/fcm/service/FcmMessageSender.java
> +public class FcmMessageSender implements MessageSendManager {
googleCredentials, ClassPathResource, Fcm Api 와 묶여있어서 테스트하기가 좀처럼 쉽지가 않네요 ㅠㅜ

설정을 다른 방향으로 빼줘야할 것 같은데 조금 더 생각해보고 추후에 리팩터링하면서 추가해봐도 될까요?! 🙏

2023-10-16 03:16 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/fcm/service/FcmMessageSender.java
> +public class FcmMessageSender implements MessageSendManager {
🥕 입니다.

2023-10-16 03:17 UTC, yeonkkk commented
주노 ~ 리뷰 반영해주신거 확인했습니다!
고생하셨어요 !!

2023-10-16 03:17 UTC, merged