feat: 내비게이션 바 애니메이션 추가
woowacourse-teams/2023-pium pull request #435
Opened 2023-10-14 16:25 UTC by WaiNaat

# 🔥 연관 이슈

- close #425 

# 🚀 작업 내용

- 페이지 이동 시 내비게이션 바 애니메이션 추가
    - 만약 로딩중이라 상단에 로딩 바가 보이는 상황이라면 로딩이 다 끝나고 이동
- 내비게이션 바 RootTemplate으로 분리
- 자잘한 코드 리팩터링
    - 컴포넌트 렌더링 함수 내에서 다른 컴포넌트를 정의하는 문제
    - 불필요한 non-null assertion, useMemo
    - exhaustive deps

![ezgif com-crop](https://github.com/woowacourse-teams/2023-pium/assets/77872742/40da76f1-63bb-49f3-88d9-e371f77796fe)

# 💬 리뷰 중점사항

css 쉽지 않네요..

대략적인 로직은 아래와 같습니다
1. grid로 배치
2. border-top은 div로 분리
3. resizeObserver로 nav item들의 좌표 계산
4. pathname을 비교해서 2번의 div 위치 조정

페이지도 같은 방향으로 넘어가게 하는 것도 하고 싶었는데 이건 진짜 쉽지 않더라구요
리코일로 현재 페이지와 이전 페이지 두 개를 기억하는 쪽으로 구현해서 돌아가게는 할 수 있었는데 여러모로 부족한 부분이 많아 그냥 버렸습니다. 다가가는 방향 자체를 잘못 잡은 것 같아요

2023-10-17 05:53 UTC, bassyu approved these changes
깔끔하네요~!
Navbar가 전역으로 가니 간단하게 해결됐군요 👍
갠적으로는 내려가는 애니메이션도 맘에 드네용

2023-10-17 11:34 UTC, hozzijeong requested changes
참새 멋있습니다 진짜 감동의 네브바 슬라이드네요...

프레임 드랍만 어느정도 해결되면 좋을 것 같아요!

2023-10-17 11:34 UTC, hozzijeong commented on frontend/src/components/@common/Navbar/index.tsx
### R 

전체적으로 Roof관련된 로직을 훅으로 분리하면 좀 더 깔끔할 것 같아요!

2023-10-17 11:34 UTC, hozzijeong commented on frontend/src/components/@common/Navbar/index.tsx
### R 

아까 말한 프레임 드랍도 같이 해결하면 좋을 것 같아요!

2023-10-17 11:34 UTC, hozzijeong commented on frontend/src/hooks/@common/useIntersectionRef.ts
> +    [observer]
크~ 멋있ㅅ습니다

2023-10-17 11:34 UTC, hozzijeong commented on frontend/src/pages/garden/GardenPostList/index.tsx
> +  .map((_, index) => <GardenPostItemSkeleton key={index} />);
### C 

스켈레톤을 반환하는 값은 어차피 한번만 호출하면 되기 때문에 컴포넌트 밖으로 뺀 것인가요??

2023-10-17 12:40 UTC, WaiNaat commented on frontend/src/pages/garden/GardenPostList/index.tsx
> +  .map((_, index) => <GardenPostItemSkeleton key={index} />);
네 기존의 컴포넌트 내부에서 컴포넌트 정의하는 문제를 해결하려고 밖으로 뺐는데 굳이 스켈레톤 목록이 컴포넌트여야 하는가라는 생각이 들어서 분리했어요

2023-10-17 12:40 UTC, WaiNaat commented on frontend/src/components/@common/Navbar/index.tsx
근데 이걸 훅으로 분리한다고 관심사 분리가 잘 될지는 모르겠네요..

2023-10-19 01:03 UTC, hozzijeong approved these changes
멋져요!

2023-10-19 01:03 UTC, hozzijeong commented on frontend/src/hooks/@common/useChildrenLeftPositions.ts
👍

2023-10-19 01:03 UTC, merged