feat: 세션 동기화 구현
woowacourse-teams/2023-pium pull request #442
Opened 2023-10-18 00:53 UTC by Kim0914

# 🔥 연관 이슈

- close #436 

# 🚀 작업 내용
### DB를 이용한 세션 동기화를 구현했습니다.

세션을 구현하는 과정에서 `Clock` 객체를 빈으로 등록해서 사용했는데요 !
세션이 `시간`과 밀접한 관계가 있다고 판단했고 세션 연장/만료 테스트를 하기 위해 추가했습니다.
`LocalDateTime.now()`의 내부 구현을 보면 `now(Clock.systemDefaultZone());`로 반환을 하는데 이 때 사용되는 Clock 객체입니다.

---

### 어드민은 기존 세션 인증 방식 구조를 유지했습니다.

현재 세션 서비스 -> (캐싱) -> DB 의 과정으로 구성하려고 하는데 `(캐싱)`은 아직 완료까지 조금 남아서 이후에 별도로 PR 올리겠습니다 !

세션 인증 구현 흐름은 다음과 같습니다.

1. `MemberArgumentResolver`에서 `HttpSession`의 ID를 이용해 `SessionGroup` 조회
```java
String sessionValue = sessionGroupService.findBySessionIdAndKey(session.getId(), SESSION_KEY);
```
2. 이후 회원 조회 과정은 기존 세션 방식과 동일

SessionGroupService의 주요 로직은 다음과 같습니다.
* findBySessionIdAndKey: 일치하는 세션을 조회합니다. 세션 만료기간 7일 이내에 요청이 발생하면 세션 유효기간을 연장시킵니다.
* add: 새로운 세션을 추가합니다. 기존 세션이 있으면 예외 발생
* delete: 세션을 삭제합니다. 기존 세션이 없으면 예외 발생

`add`, `delete`는 빈번이 일어나는 요청이 아니기 때문에 `JPARepository`에서 제공하는 쿼리 메서드를 사용했습니다.

# 💬 리뷰 중점사항

테스트 및 세션 인증 흐름을 따라가며 잘못된 부분이 있는지 확인해주세요 !

2023-10-18 06:31 UTC, yeonkkk requested changes
그레이 세션 동기화 구현하시느라 고생 많으셨어요 ~~
이번에도 잘 짜주셨네요 !
코멘트 남겼으니 확인 부탁드려요!
고생하셨습니다 ~

2023-10-18 06:31 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/controller/AuthController.java
>          }
### A
로그인할 때 톰캣에서 세션을 생성하고 있으니, DB에서 세션을 제거할 때 메모리에서도 세션을 제거해주면 어떨까요? 
물론 이후에 해당 세션으로 요청을 안하면 일정 시간 후에 메모리에서 제거되지만, 로그아웃한 세션 ID로 요청을 보내면 tomcat 내에서 연장을 해서 메모리에 일정시간 더 남아 있을 것 같아용.
사실 지금 로직에서 큰 문제는 없어서 불필요한 것 같으면 적용은 안하셔도 됩니다 ㅎ
```
session.invalidate();
```

2023-10-18 07:01 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/MemberArgumentResolver.java
> +            Long kakaoId = Long.valueOf(sessionValue);
헉 감사합니다...

2023-10-18 07:02 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/repository/SessionGroupRepository.java
> +    Optional<SessionGroup> findBySessionIdAndSessionKey(String sessionId, String sessionKey);
Session 객체 내에 (key1, value1), (key2, value2)로 저장될 수 있기 때문에 sessionId와 HashMap의 Key인 sessionKey를 복합키(유니크)로 설정했습니다 !!

2023-10-18 07:12 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/MemberArgumentResolver.java
> +        String sessionValue = sessionGroupService.findBySessionIdAndKey(session.getId(), SESSION_KEY);
좋아요 ! 반영했습니다 ㅎㅎ

2023-10-18 07:12 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java
> +
위와 동일하게 해결했습니다 !

2023-10-18 07:53 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/AuthController.java
>          }
좋아요 ! 꼼꼼하게 해주는게 좋을 것 같네용

2023-10-18 08:03 UTC, yeonkkk approved these changes
그레이 리뷰 반영해주신거 확인했습니다 ~
고생하셨어유👍

2023-10-19 00:22 UTC, Choi-JJunho approved these changes
잘 구현해주신것 같아 Approve 하겠습니다 👍
중간에 개행 한줄만 확인해주세용

2023-10-19 02:22 UTC, rawfishthelgh requested changes
그레이 고생했어요 코멘트 두개만 달아주면 바로 merge 진행시킬게여ㅎㅎ

2023-10-19 02:22 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/domain/SessionGroup.java
> +    public final boolean equals(Object o) {
A
제가 아무리 찾아봐도 안보이는데 동등비교가 어디서 수행될까요????

2023-10-19 02:22 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java
> +    public String findBySessionIdAndKey(String sessionId, String key) {
C
어제 얘기했긴 한데,  조회 시 extends 행위가 있어서 @Transactional 어노테이션과 findBy 네이밍이 혼재하는게 어색하긴 하네요ㅎㅎ(피움의 그레이 후임 개발자가 멋대로 readonly로 바꿔버릴까봐...)
`findOrExtendBySessionIdAndKey`같은 네이밍은 어떨까요

2023-10-19 02:27 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/SessionGroup.java
> +    public final boolean equals(Object o) {
현재는 동등비교를 하는 상황이 없는데 엔티티에 일괄적으로 equals and hashcode를 정의해주는게 좋을 것 같아서 함께 정의했어요 !

2023-10-19 02:27 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/SessionGroup.java
> +    @Id
어이쿠 !

2023-10-19 02:27 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/SessionGroupService.java
> +    public String findBySessionIdAndKey(String sessionId, String key) {
오 너무 좋아요 ㅎㅎ
확실하게 메서드 명으로 드러내주는게 좋을 것 같네요 !

2023-10-19 02:34 UTC, rawfishthelgh approved these changes
확인했습니다~~! 고생했어요 글에이

2023-10-19 04:55 UTC, merged