feature/44 메인 페이지 구현 msw 연결
woowacourse-teams/2023-pium pull request #53
Opened 2023-07-14 07:03 UTC by bassyu

# 🔥 연관 이슈

- close #44 

# 🚀 작업 내용

라우팅 작업과 함께 메인 페이지를 만들어 봤습니다.

이슈 내용 외적으로 자잘하게 추가한 부분이 많습니다!
커밋 내용 확인해 주시면 감사하겠습니다.

# 💬 리뷰 중점사항

라우터 적용해봤는데, 네이밍이나 구조 확인해주세요!

2023-07-14 10:06 UTC, hozzijeong reviewed
고생하셨습니다! 귀찮은 세팅이 많았을텐데 전부 해주셨네요..ㅎ

코멘트 달아놓은 것들 한번 확인해주세요!!

2023-07-14 10:06 UTC, hozzijeong commented on frontend/src/components/SearchBox/SearchBox.style.ts
> +  font-size: 1.8rem;
### A

일반적인 제안인데, 폰트 크기를 통일해 보는것은 어떤가요?

2023-07-14 10:06 UTC, hozzijeong commented on frontend/src/components/SearchBox/index.tsx
> +    if (name === '') {
###C

공백과 같은 문자열은 상수화 해놓으면 좋을것 같아요!

2023-07-15 05:10 UTC, WaiNaat requested changes
깔끔한 메인 페이지 만들어주셔서 감사해요 쵸파

2023-07-15 05:21 UTC, bassyu commented on frontend/src/pages/Main/Main.style.tsx
> +  margin-top: 8vh;
현재로서는 특별하게 쓸 이유가 없겠네요!
%로 해보고 비슷하면 %로 통일하는게 좋아보입니다.

2023-07-15 05:22 UTC, bassyu commented on frontend/src/components/SearchBox/SearchBox.style.ts
> +  font-size: 1.8rem;
글로벌 스타일에 있는 폰트라면 최대한 활용해 볼게요!

2023-07-15 05:25 UTC, bassyu commented on frontend/src/components/SearchBox/index.tsx
> +    if (name === '') {
저도 참새와 동의합니다!
빈 문자열이 다른 의미라면 상수화를 하곤 하는데요, 빈 문자열 그대로의 의미라면 그대로 두는 편입니다.

2023-07-15 05:28 UTC, bassyu commented on frontend/src/pages/Main/index.tsx
> +import logo from 'assets/logo.svg';
오 이런 방법도 있었네요!?
적용해 볼게요!

2023-07-15 07:03 UTC, bassyu commented on frontend/src/pages/Main/index.tsx
> +import logo from 'assets/logo.svg';
그런데 뭔가 에러가 나네요..

2023-07-15 13:42 UTC, WaiNaat approved these changes
반영해주신 부분들 확인했습니다!!

2023-07-15 14:48 UTC, hozzijeong commented on frontend/src/components/SearchBox/SearchBox.style.ts
> +  font-size: 1.8rem;
당연히 폰트 크기에 맞춰 UI를 지정하는게 위험하다고 생각합니다. 하지만, 폰트 크기가 갖는 의미가 있고, 앞으로 개발할때 있어서 각각의 의미를 통용하는 UI들이 나올것이라고 생각이 들어서요. 그 부분을 글로벌 스타일로 맞춰서 통일해 보자는 얘기였습니다!

2023-07-15 14:50 UTC, hozzijeong commented on frontend/src/pages/Main/index.tsx
> +import logo from 'assets/logo.svg';
궁금한게, svg를 컴포넌트로 사용하게 된다면 <img/> 태그의 역할이 같이 동반되는 것일까요? 만약에 그렇지 않다면 저는 회의적인 입장입니다...!

2023-07-16 07:02 UTC, hozzijeong approved these changes
고생하셨습니다 쵸우파~

2023-07-17 04:29 UTC, merged