Feature/21 달력 입력을 위한 컴포넌트 구현
woowacourse-teams/2023-pium pull request #58
Opened 2023-07-14 08:21 UTC by hozzijeong

# 🔥 연관 이슈

- close #21 

# 🚀 작업 내용
![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/edbebbb1-f19a-465c-9108-bdf0b2fefab2)
 - 날짜 입력 컴포넌트 생성
 - 기본 값은 오늘 날짜로 설정
 - 상태에 저장되는 값 형태는 YYYY-MM-DD.
 - YYYY-MM-DD 형태를 YYYY년 MM월 DD일로 변환하는 유틸 함수 생성
 - 인풋 클릭시에 달력 입력창이 나타나며 날짜 선택 가능

# 💬 리뷰 중점사항
 - 디자인 괜찮은지를 우선적으로 봐주세요!
 - 일단은 컴포넌트 안에 상태를 구현해 놨지만 form에 사용되는 값들을 어떻게 할 것인지 (전역 vs 상태 끌어올리기) 정해지지 않았기에 우선을 컴포넌트 내부에 상태로 값을 선언했습니다!

2023-07-15 06:17 UTC, WaiNaat requested changes
멋진 달력 입력 컴포넌트 감사해요 클린
초록색 밑줄은 나중에 진짜라벨 + 인풋 + 밑줄 이런 형태로 합칠 때 넣는 계획인거죠??

2023-07-15 06:17 UTC, WaiNaat commented on frontend/src/utils/date.ts
> +};
### R

```suggestion
export const convertToKorDateString= (date: string) => (
  new Date(date).toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
);
```
좀 더 범용성 있는 코드 추천드립니다 👍

2023-07-15 06:17 UTC, WaiNaat commented on frontend/src/utils/date.ts
> +};
### C

```suggestion
export const getToday = () => {
  const timezoneOffset = new Date().getTimezoneOffset() * 60 * 1000;
  const localTime = new Date(Date.now() - timezoneOffset);
  return localTime.toISOString().slice(0, 10);
};
```
여기도 이런 느낌으로 바꿀 순 있을 것 같아요

2023-07-15 06:50 UTC, bassyu commented on frontend/src/components/DateInput/index.tsx
> +      <Date name="date-input" type="date" value={date} onChange={changeHandler} max={getToday()} />
([제 프롤로그도 봐주세요](https://prolog.techcourse.co.kr/studylogs/3742))

2023-07-15 06:59 UTC, bassyu approved these changes
작은 단위로 매우 빠르게 개발해주셨네요!
수고하셨습니다!

2023-07-15 06:59 UTC, bassyu commented on frontend/src/utils/date.ts
> +  return [year, month, day].join('-');
### A

하드하긴 하지만 해석하기에는 매우 잘 읽히는 코드라고 생각되네요!

2023-07-15 06:59 UTC, bassyu commented on frontend/src/components/DateInput/DateInput.style.ts
> +  &::-webkit-calendar-picker-indicator {
### A

생각해보면 달력 입력이 브라우저에서 지원하는 것이라 스타일이 복잡해지네요 ㅠㅠ
파이어폭스는 -webkit 대신 -moz를 사용하는데, 어쩔 수 없는 부분인 것 같습니다.

2023-07-15 07:12 UTC, bassyu commented on frontend/src/components/DateInput/index.tsx
> +  const changeHandler: React.ChangeEventHandler<HTMLInputElement> = (event) => {
### A

타입 이야기 해보면 좋을 것 같아요! https://github.com/woowacourse-teams/2023-pium/discussions/59

2023-07-15 15:02 UTC, hozzijeong commented on frontend/src/components/DateInput/index.tsx
> +    setDate(value);
크으 좋아요 좋아요!

2023-07-15 15:03 UTC, hozzijeong commented on frontend/src/components/DateInput/index.tsx
> +      <Date name="date-input" type="date" value={date} onChange={changeHandler} max={getToday()} />
`useId()` 좋네요! 중복 생각해서 name으로 할당했었는데, 좋은 생각인것 같습니다.

2023-07-16 03:35 UTC, hozzijeong commented on frontend/src/components/DateInput/DateInput.style.ts
> +  &::-webkit-calendar-picker-indicator {
범용성 생각하면 -moz도 추가해야겠군요...

2023-07-16 11:17 UTC, WaiNaat approved these changes
반영해주신 부분들 확인했습니다. 고생하셨어요 클린

2023-07-16 11:21 UTC, merged