feat: 반려 식물 단일 조회
woowacourse-teams/2023-pium pull request #67
Opened 2023-07-17 11:46 UTC by Kim0914

# 🔥 연관 이슈

- close #18 

# 🚀 작업 내용

- 반려 식물 단일 조회 기능을 추가했습니다.

# 💬 리뷰 중점사항

- 물주기 남은 날짜 계산, 함께한 날 계산은 `PetPlant` 도메인 로직으로 위임했습니다. 
- 해당 로직 꼼꼼하게 봐주시면 감사하겠습니다.

2023-07-17 15:57 UTC, rawfishthelgh requested changes
그레이 개발하느라 고생 많았어요ㅎㅎ
변경 요청부분보다는 의견이 궁금한 부분이 몇 가지 있어 코멘트 남겼어요!
본인의 의사에 따라서 반영 or 그대로 진행 해주시면 될 것 같아요

2023-07-18 01:14 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/PetPlantController.java
> +@Validated
넵 맞습니다 ~
컨트롤러 메서드 파라미터를 검증하기 위해서는 AOP 기반의 검증이 필요합니다 !
그래서 `@Validated`를 사용했습니다 !

2023-07-18 01:15 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +            throw new IllegalArgumentException("물주기 남은 날짜는 음수가 될 수 없습니다.");
놓쳤던 부분이네요 ㅎㅎ
반영하겠습니다 !!

2023-07-18 01:17 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/domain/PetPlant.java
> +            throw new IllegalArgumentException("함께한 날은 음수가 될 수 없습니다.");
`birthDate`는 도메인 내부 값이기 때문에 드러내지 않는 것이 좋다는 생각이 듭니다 !

하마드가 말씀해주신 것 처럼 localDate는 클라이언트 입력 값이기 때문에 명시해서 알려줘도 좋을 것 같네요 😄

2023-07-18 01:22 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/exception/dto/GlobalExceptionResponse.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
놓쳤던 부분입니다 ㅜㅜ !

반영하겠습니다 ㅎㅎ

2023-07-18 01:32 UTC, Choi-JJunho requested changes
고생하셨습니다~
예외 검증 구성해주셔서 감사합니다 👍
몇가지 궁금한 내용 코멘트로 남겨놨습니다

2023-07-18 01:32 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
> +                    .append(" Value: ")
### A
문자열 시작부분에 공백이 들어가는 이유가 있을까요?
사소한 내용입니다 😅

2023-07-18 01:32 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        Long daySince = petPlant.calculateDaySince(LocalDate.now());
### C
제가 기존에 작성해뒀던 코드에서는 Service단에서 해당 변환로직을 수행하고있네요 ㅠㅠ
혹시 create 메서드의 로직을 그레이가 작성한 방식으로 통일시켜주실 수 있을까요??

2023-07-18 01:32 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
> +            .imageUrl("image.url")
### C
향후에 URL 형태를 validate하는 조건을 걸 수도 있을 것 같다고 생각합니다
따라서 Fixture에 `http://image.com` 과 같이 URL 형태로 구성하는건 어떨까요?

2023-07-18 01:32 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
> +        PetPlant savsavePetPlant = petPlantRepository.save(petPlant);
### R
변수 네이밍이 알기 어려운것 같아요!
`savePetPlant`, `save` 와 같은 네이밍으로 수정할 필요가 있어보이네요

2023-07-18 02:13 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/controller/GlobalExceptionHandler.java
> +                    .append(" Value: ")
컨트롤러의 `@Positive(message = "반려식물 ID는 음수가 될 수 없습니다.")`의 예외 메세지와 원인을 담기 위해서 사용했습니다 !
공백으로 한 글자 띄어주기 위해서요 !

2023-07-18 02:15 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        Long daySince = petPlant.calculateDaySince(LocalDate.now());
넵 반영하겠습니다 !

2023-07-18 02:18 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
> +            .imageUrl("image.url")
오 넵 좋습니당 ~

2023-07-18 02:20 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/repository/PetPlantRepositoryTest.java
> +        PetPlant savsavePetPlant = petPlantRepository.save(petPlant);
헉,,, 복붙하다가 이상하게 만들어졌네요..
반영했습니다 !

2023-07-18 03:48 UTC, Choi-JJunho approved these changes
고생하셨습니다

2023-07-18 05:41 UTC, rawfishthelgh approved these changes
확인했습니다! 고생하셨어요~

2023-07-18 05:41 UTC, merged