feat: 반려 식물 전체 조회
woowacourse-teams/2023-pium pull request #68
Opened 2023-07-17 11:47 UTC by Choi-JJunho

# 🔥 연관 이슈

- close #19

# 🚀 작업 내용

- [x] 반려식물 전체 조회

# 💬 리뷰 중점사항

기능적으로는 크게 변경사항이 없어 테스트를 중심적으로 리뷰해주시면 좋을 것 같아요 :)

2023-07-18 02:31 UTC, rawfishthelgh requested changes
주노 리뷰 남겨놨어요ㅎㅎ
개발하느라 고생하셨습니다 편하게 보고 필요하다 싶으면 반영해줘요!

2023-07-18 02:31 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        List<PetPlant> petPlants = petPlantRepository.findAllByMemberId(member.getId());
### C
해당 멤버의 반려식물이 없는 상황의 예외 고려가 필요할 듯 해요!

2023-07-18 02:31 UTC, rawfishthelgh commented on backend/pium/src/main/java/com/official/pium/service/dto/DataResponse.java
> +    }
### A
제네릭을 리스트 타입으로 걸지, 아니면 T로 걸지 협의가 필요할 듯 해요!

2023-07-18 02:31 UTC, rawfishthelgh commented on backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
> +        public static PetPlantResponse 피우미_응답 = PetPlantResponse.builder()
### A
static import를 해제한 것은 위의 PetPlantRequest.builder()와 명시적으로 구분하기 위해선가요?

2023-07-18 05:27 UTC, yeonkkk reviewed
안녕하세요 주노! 🌱

이번에도 잘 작성해주셨네요! 
코멘트 조금 남겨뒀으니 확인 부탁드려요~
고생하셨습니다!

2023-07-18 05:27 UTC, yeonkkk commented on backend/pium/src/main/java/com/official/pium/service/dto/SinglePetPlantResponse.java
> +public class SinglePetPlantResponse {
### A

이건 개인적으로 궁금증이 생겨서 여쭤봅니다!
`SinglePetPlantResponse` 라는 이름은 전체 반려식물 중에 하나의 반려 식물에 대한 응답을 나타내는 것 일까요?!
사실 `PetPlantResponse`도 하나의 반려 식물에 대한 응답 값이라서 두 개가 조금 헷갈릴  수 있을 것 같아요.
이에 대한 주노의 생각이 궁금합니다!🙂

2023-07-18 05:27 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
> +                                        .imageUrl("https://imgae.com")
### A
```suggestion
                                        .imageUrl("https://image.com")
```
중요한건 아니지만 오타가 있네용✅

2023-07-18 05:27 UTC, yeonkkk commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +    void 반려_식물_조회() {
### A
이름이 `반려_식물_전체_조회`면 단건 조회랑 구분되어 이해가 쉬울 것 같아요!

2023-07-18 06:52 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +        List<PetPlant> petPlants = petPlantRepository.findAllByMemberId(member.getId());
전체 조회의 경우 반려식물이 없는 상황에서 빈 리스트를 반환하도록 구성합니다!

[해당 disscussions](https://github.com/woowacourse-teams/2023-pium/discussions/76)

2023-07-18 06:52 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/dto/DataResponse.java
> +    }
T로 변경하는게 확장성 측면에서 좋아보이네요!

T로 수정하겠습니다.

2023-07-18 07:44 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
> +        public static PetPlantResponse 피우미_응답 = PetPlantResponse.builder()
넵 builder만 존재하면 명시적으로 확인하기 어려울 것 같아 명시적으로 작성했습니다

2023-07-19 02:29 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
> +    List<PetPlant> findAllByMemberId(Long id);
### A

PetPlantRepository에서 MemberId로 조회하기 때문에 파라미터 네이밍을 memberId로 설정해주는 건 어떨까요?!

2023-07-19 02:29 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/service/dto/SinglePetPlantResponse.java
> +public class SinglePetPlantResponse {
> SinglePetPlantResponse 라는 이름은 전체 반려식물 중에 하나의 반려 식물에 대한 응답을 나타내는 것 일까요?!

네 맞습니다! 
단일조회의 `PetPlantResponse`와 전체조회의 반려 식물 정보가 다르기 때문에 별도의 DTO를 생성해야했습니다.

또한 현재 배열 형태의 데이터들을 DataResponse라는 클래스로 묶어서 관리하고있기 때문에 단일 객체에 대한 네이밍이 필요하다고 생각하여 위와같이 `SinglePetPlantResponse`라는 이름으로 구성했습니다

2023-07-19 02:30 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/PetPlantService.java
> +                .collect(Collectors.toList());
### A

자바 17부터는 `toList()`로 한번에 컬렉션으로 만들 수 있답니다 ~~ 참고만해주세용

2023-07-19 02:30 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/fixture/PetPlantFixture.java
> +                                        .imageUrl("https://imgae.com")
확인했습니다!

2023-07-19 02:31 UTC, Choi-JJunho commented on backend/pium/src/test/java/com/official/pium/service/PetPlantServiceTest.java
> +    void 반려_식물_조회() {
확인했습니다!

2023-07-19 02:31 UTC, Choi-JJunho commented on backend/pium/src/main/java/com/official/pium/repository/PetPlantRepository.java
> +    List<PetPlant> findAllByMemberId(Long id);
좋습니다! 반영하겠습니다

2023-07-19 05:22 UTC, yeonkkk approved these changes
주노!
리뷰 내용 잘 반영해주셨네요.
고생하셨습니다~

2023-07-19 06:51 UTC, rawfishthelgh approved these changes
코드 변경사항 확인했습니다! 검색 쿼리 파라미터 검증까지 추가해주셔 감사해요 👍 
Approve & Merge 하겠습니다~~

2023-07-19 06:51 UTC, merged