feat: 입력 폼 공통 컴포넌트 구현
woowacourse-teams/2023-pium pull request #70
Opened 2023-07-17 12:47 UTC by hozzijeong

# 🔥 연관 이슈

- close #65 

# 🚀 작업 내용
![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/489e313a-14c3-4ab0-afe5-b7dcf5b7de66)

입력 컴포너트를 children을 넘기는 방식으로 구현했습니다. 
폼과 관련한 컴포넌트인데 아직 폼에 대한 명확한 디자인이나 구현 방법이 나오지 않아서 컴팩트하게 구현만 하고, 이후에 폼을 만들면서 기능 등을 추가해야 할 것 같습니다.

# 💬 리뷰 중점사항
전반적인 디자인에 대한 이야기를 해주시면 감사하겠습니다!

2023-07-18 01:09 UTC, WaiNaat requested changes
피그마처럼 이쁘게 만들어주셔서 감사해요 클린
전반적인 디자인은 좋은 것 같아요!!

2023-07-18 01:09 UTC, WaiNaat commented on frontend/src/components/FormInputBox/index.tsx
> +        <button type="button" onClick={nextHandler}>
![image](https://github.com/woowacourse-teams/2023-pium/assets/77872742/f2fb7d14-d2dd-44c8-a656-899d24f9aacc)

요 버튼도 디폴트로 오른쪽에 있으면 좋을것같아요!

2023-07-18 04:18 UTC, hozzijeong commented
@WaiNaat @bassyu 
오전에 회의한 내용 기반으로 리팩터링 해서 반영해 봤습니다! 확인 부탁드려요!

2023-07-19 02:07 UTC, WaiNaat approved these changes
변경하신 부분들 확인했어요 고생하셨습니다 클린

2023-07-19 02:13 UTC, bassyu approved these changes
이쁘게 잘 만들어주셨네요!! 감사합니다!

2023-07-19 02:13 UTC, bassyu commented on frontend/src/components/FormInputBox/index.tsx
> +      {status === 'error' && <ErrorMessage>{error}</ErrorMessage>}
### A

에러가 없더라도 높이는 고정되면 좋을 것 같네요!

2023-07-19 02:13 UTC, merged