feat: 사전 식물 상세 정보 조회 기능 구현
woowacourse-teams/2023-pium pull request #72
Opened 2023-07-17 16:59 UTC by yeonkkk

# 🔥 연관 이슈

- close #15 

# 🚀 작업 내용
- [x] 사전 식물 상세 정보 조회 기능 구현  

# 💬 리뷰 중점사항
특별한 로직이 많이 들어가는 기능은 아니라서 전반적으로 봐주시면 좋을 것 같아요.
잘 부탁드립니다 🌱

2023-07-18 02:18 UTC, Choi-JJunho requested changes
고생하셨습니다~ 
전체적으로 잘 작성해주셨는데 develop 브랜치 내용이 반영이 안된 것 같아요~!

```git
git checkout feature/15-사전_식물_상세_정보_조회_기능
git pull origin develop
git push
```
브랜치 최신화 및 충돌 해결 이후  리뷰요청 한번 더 부탁드릴게요

2023-07-18 04:50 UTC, Kim0914 requested changes
조이 !! 고생많았습니다 ㅎㅎ

꼼꼼히 개발해주신 덕분에 리뷰 남길 부분이 많이 없는 것 같아요 !
궁금한 점은 코멘트로 남겼습니다 😄

2023-07-18 04:50 UTC, Kim0914 commented on backend/pium/src/main/java/com/official/pium/service/DictionaryPlantService.java
> +                .orElseThrow(() -> new NoSuchElementException("사전 식물이 존재하지 않습니다. id : " + id));
### A

별건 아니지만..! `id:` 콜론과 앞 단어는 붙여서 쓰는 방식으로 통일하면 어떨까요?!

2023-07-18 04:50 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +    }
### R

사전 식물 상세 정보 조회의 실패하는 경우에 대한 테스트를 추가해보는건 어떨까요?!
컨트롤러에서 `@Positive`로 검증하고 있는데 해당 테스트가 없는 것 같아요 !

2023-07-18 04:50 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/service/DictionaryPlantServiceTest.java
> +    void 사전_식물_상세_정보를_조회한다() {
### C

`dictionaryPlant`가 해당 테스트에서만 사용되고 있는데 `@BeforeEach`로 생성하는 이유가 궁금합니다 😀

2023-07-18 04:50 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +                .andExpect(MockMvcResultMatchers.status().isOk())
꼼꼼한 검증 👍👍

2023-07-18 04:50 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +                .andExpect(jsonPath("$.postingPlace").isArray())
### A

`isArray()`는 어떤 내용을 검증하는 테스트 메서드인가요?!
단순 궁금증입니다 !

2023-07-18 07:41 UTC, yeonkkk reviewed
@Choi-JJunho @Kim0914 

주노, 그레이! 꼼꼼하게 리뷰해주셔서 감사해요🍀
리뷰주신 부분 모두 반영했습니다.
혹시 추가적으로 수정해야할부분이 있다면 알려주세요.
감사합니다!

2023-07-18 08:50 UTC, Kim0914 commented on backend/pium/src/test/java/com/official/pium/controller/DictionaryPlantControllerTest.java
> +                .andExpect(jsonPath("$.postingPlace").isArray())
꼼꼼한 검증 좋아요 ~!

2023-07-18 08:52 UTC, Kim0914 approved these changes
리뷰 반영해주신 부분 확인했습니다 !

Approve 할게요 ㅎㅎ 고생많으셨습니다.

방금 하마드 PR이 머지되어서 pull로 최신화한 후에 merge를 해야할 것 같아요.
pull 할 때 `git config pull.rebase false`한 후에 `git pull origin develop`을 실행해야 Push reject가 발생하지 않을 것 같네요 🙃

확인 부탁드려요 !

2023-07-18 08:56 UTC, Choi-JJunho commented
리뷰 반영내용은 이상없는 것 같아요!
다만 위에서 그레이가 이야기한것처럼 develop 브랜치 변경사항을 반영한 뒤에 다시 확인해볼 필요가 있는 것 같아 approve는 잠시 미뤄두겠습니다~

2023-07-18 12:32 UTC, yeonkkk commented
@Choi-JJunho 
반영 완료했습니다~🎶

2023-07-19 01:31 UTC, Choi-JJunho approved these changes
고생하셨습니다~

2023-07-19 01:32 UTC, merged