feat: 반려 식물 등록 입력 컴포넌트 생성 (number 생성)
woowacourse-teams/2023-pium pull request #80
Opened 2023-07-18 08:31 UTC by hozzijeong

# 🔥 연관 이슈

- close #73 

# 🚀 작업 내용

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/de0e518a-c9ec-42a2-887a-22db8e8905cc)

- 먄약에 숫자 관련 input을 생성하고자 한다면, useNumberInput hooks를 사용해서 기존의 값들을 막을 수 있습니다.

![image](https://github.com/woowacourse-teams/2023-pium/assets/50974359/5fbbdac4-5afb-4b80-a637-1e1b3d468a57)
- 에러 처리나 `nextHandler`같은 경우는 현재 비워뒀습니다.

# 💬 리뷰 중점사항
- 범용성 있는 Input 컴포넌트를 만들려고 했습니다. 따라서 로직과 관련된 부분들을 hook으로 분리했습니다.
- number input 뿐만 아니라 date input도 hooks로 분리할 수 있는 부분들 따로 분리했습니다. 
- 범용적으로 사용하기에 어떤지를 위주로 리뷰해 주시면 감사하겠습니다

# 걸린 시간
3시간 반
github 이슈 1시간

2023-07-18 12:49 UTC, WaiNaat requested changes
범용성 좋은 컴포넌트 감사해요 클린 👍 

각 입력의 값과 검증 절차를 훅으로 분리한 점이 마음에 듭니다 범용성은 괜찮은 것 같아요!

![inputError](https://github.com/woowacourse-teams/2023-pium/assets/77872742/998b462d-194e-46ab-9288-8d9b402db746)

저도 정확한 이유는 못 찾았는데 한글 입력하면 뭔가 꼬이는 것 같아요 😢 확인 부탁드려요!

2023-07-19 01:23 UTC, bassyu requested changes
빠르게 구현해주셨네요 수고하셨습니다!
살짝의 이슈가 있는건 코멘트 확인해주세요!

2023-07-19 01:23 UTC, bassyu commented on frontend/src/components/FormInput/FormInput.stories.tsx
> +        type="number"
### R

input type이 number이면 한글을 입력할 때 일단 기다리는 이슈가 있습니다. 그래서 살짝 꼬여요
반면에 input type을 text로 해두고, 숫자만 입력하도록 검증하면 한글을 제대로 막고 숫자만 입력받을 수 있습니다.

FormInput의 type 까지는 컴포넌트 안으로 고정해둬도 좋을 것 같아요

2023-07-19 02:22 UTC, hozzijeong commented on frontend/src/hooks/useNumberInput.ts
> +      setNumberValue(undefined);
좋습니다. 처음에는 `null`을 할당하려 했는데 Input에 null은 넣을 수 없다고 하더라구요... ㅎ 맞춰서 변경했습니다!

2023-07-19 02:32 UTC, hozzijeong commented
@bassyu @WaiNaat  남겨주신 코멘트 기반으로 코드 수정 완료했습니다! 한번 확인 부탁드려요

2023-07-19 04:17 UTC, bassyu approved these changes
반영 확인했습니다!
수고하셨어요!

2023-07-19 04:17 UTC, bassyu commented on frontend/src/hooks/useNumberInput.ts
> +  const changeCallback: React.ChangeEventHandler<HTMLInputElement> = (e) => {
### A

관심사 분리 측면에서 제안드려봅니다!
커스텀 훅에서는 이벤트 객체는 모르는 상태에서 숫자를 검증하는 행동만 작성하고
사용처에서 이벤트 핸들러를 작성하는 것도 좋아보입니다.

2023-07-19 09:29 UTC, merged